
     "<FONT COLOR=\"#6285C6\" >来源：电龙、红电龙</FONT><BR><BR><FONT COLOR=\"#C6B262\">电龙及亚种特有的分泌物，产量很少，可以用来调配“觉醒药”。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：王立委托</FONT><BR><BR><FONT COLOR=\"#C6B262\">高级装备素材</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：王立精英委托</FONT><BR><BR><FONT COLOR=\"#C6B262\">高级装备素材</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园鱼塘。</FONT><BR><BR><FONT COLOR=\"#C6B262\">湖底坚硬的石头，调和异常状态攻击类子弹和填充器必备的素材之一。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园鱼塘。</FONT><BR><BR><FONT COLOR=\"#C6B262\">常见的水草，调和属性攻击类子弹和填充器必备的素材之一。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：猎团商店；猎团赛、间接竞技等活动兑换。</FONT><BR><BR><FONT COLOR=\"#C6B262\">可以用来兑换高级技能珠配方的素材券，同时也是调和高级技能珠必不可少的原料之一。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：所有难度黄速龙。</FONT><BR><BR><FONT COLOR=\"#C6B262\">黄速龙的牙齿，具有一定的麻痹作用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：所有难度精灵鹿，雪山麋鹿。</FONT><BR><BR><FONT COLOR=\"#C6B262\">具有滋补效用的鹿角，能从各种鹿身上剥取。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：所有难度野生艾露，野生梅露。</FONT><BR><BR><FONT COLOR=\"#C6B262\">似乎具有一定价值的宝物。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：所有难度小沙龙。</FONT><BR><BR><FONT COLOR=\"#C6B262\">鱼龙种的牙齿，前端被稍稍磨平。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：所有难度大名盾蟹，镰蟹。</FONT><BR><BR><FONT COLOR=\"#C6B262\">蟹的背壳，似乎会被拿去收藏……</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：所有难度蓝速龙。</FONT><BR><BR><FONT COLOR=\"#C6B262\">蓝速龙的鳞片。能串在一起编织成装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：密境掘宝</FONT><BR>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植空心果可产出；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">里面是空的果实，种在任何地方都能生长的植物。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植黏着草可产出；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">叶子表面带有强烈黏性的草，不小心粘在身上的话就取不下来了</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2、3级种子概率产出；直接种植火药草可产出；20级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">能够引起火星的奇异植物。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级种子概率产出；直接种植解毒草可产出；20级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">带有解毒功效的草，但是效果不稳定。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植睡眠草可产出；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">有睡眠效果的草。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植常春藤叶可产出；狩猎场采集。</FONT><BR><BR><FONT COLOR=\"#C6B262\">具有良好柔韧度的草。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级种子概率产出；直接种植仙人掌花可产出；20级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">含有解毒成分的花朵，但是无法单独服用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植落阳草可产出；狩猎场采集。</FONT><BR><BR><FONT COLOR=\"#C6B262\">只能在阴暗的背光处培养，气味极香，经常作为调合素材使用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级种子概率产出；直接种植怪力果实可产出；40级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">由怪力之种长成的奇异果实，看上去不太能吃。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级种子概率产出；直接种植忍耐果实可产出；40级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">由忍耐之种长成的奇异果实，看上去不太能吃。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2、3级种子概率产出；直接种植曼陀罗花可产出；狩猎场采集。</FONT><BR><BR><FONT COLOR=\"#C6B262\">据说会夺取人生命的植物，非常危险。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植染色果可产出；狩猎场采集。</FONT><BR><BR><FONT COLOR=\"#C6B262\">果子破裂后会散发出强烈气味的种子。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植爆裂核桃可产出；狩猎场采集。</FONT><BR><BR><FONT COLOR=\"#C6B262\">外部受到冲击，内部就会爆裂的核桃。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植针果可产出；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">果核如果针般锋利，可以作为弹药素材的果实。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级种子概率产出；直接种植野生辣椒可产出；20级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">放在嘴里吃一口就能感到如火般的辣味，常用来制作调味料使用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园矿场；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">含有铁元素的矿石，加工后可以提炼出多种金属。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级庄园矿场；20~40级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">比铁矿石更为优质的金属矿石，加工后的金属更加坚韧耐用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级庄园矿场；40级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">能精炼出更为优质金属的稀有矿石。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级庄园矿场；5~20级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">圆盘形状的石头，在装备制作时经常用到。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级庄园矿场；20~40级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">微生物的遗骸与动植物腐败结晶后产生的石头，蕴含大地的活力，工匠制作装备经常用到的素材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级庄园矿场；40级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">纯度极高且闪耀光辉的水晶，具有很强的硬度。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：4级庄园矿场；35~45级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">闪耀光芒的水晶，硬度较强，被猎人们收纳后用来制作装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~6级庄园矿场；5~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">即使在常温下也不会融化的冰之结晶，具有提高矿石浓度的作用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级庄园虫栖地；5~20级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">释放出裂龙鱼类喜爱味道的蚂蚱，经常被用来做为鱼饵使用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级庄园虫栖地；20~40级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">建巢技术高超的蚁类，拥有粘度极高的体液和锐利的下颚。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级庄园虫栖地；40级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">拥有特殊红色触角的美丽蝴蝶。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级庄园虫栖地；5~20级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">释放出金枪鱼喜欢气味的昆虫，做为鱼饵的效果非常的好。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级庄园虫栖地；20~40级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">甲壳极为坚硬，同时具有亮丽光泽的甲虫，加工后可以做为研剂使用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级庄园虫栖地；40级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">释放出黄金鱼喜欢气味的昆虫，做为鱼饵的效果非常的好。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园虫栖地；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">拥有自然愈合能力的昆虫，味道较苦。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2~3级庄园虫栖地；20级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">传说中具有千年寿命的虫类。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园虫栖地；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">在危险时刻会释放出强烈闪光的虫。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园虫栖地；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">施加冲击就会放电的昆虫，被猎人们广泛采用在生活中或制作装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园育菇木床；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">蕴含了增强效果的蘑菇。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园育菇木床；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">蕴含麻痹效果的蘑菇。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园育菇木床；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">蕴含了毒素的蘑菇，食用的话会陷入中毒状态。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园育菇木床；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">蕴含高温的稀有蘑菇。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：5~20级狩猎场；狩猎补给品商店。</FONT><BR><BR><FONT COLOR=\"#C6B262\">猎人狩猎生活中必不可缺的素材，能够加工成各种东西。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：20~40级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">大小适中的骨头，坚固柔软，与金属和木料的结合度非常高。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：40级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">大型龙种的骨头，是加工高级优质物品绝对不可缺少的素材，同时也能够连接骨头与甲壳素材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：狩猎场；狩猎补给品商店。</FONT><BR><BR><FONT COLOR=\"#C6B262\">非常普通的骨头，已经风化到完全无法分辨是何种生物的了。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：狩猎场；狩猎补给品商店。</FONT><BR><BR><FONT COLOR=\"#C6B262\">被风化后的骨头，由于过于脆弱已经无法再进行任何加工。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：狩猎场</FONT><BR>":
     "<FONT COLOR=\"#6285C6\" >来源：狩猎补给品商店。</FONT><BR><BR><FONT COLOR=\"#C6B262\">空无一物的小桶。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：狩猎补给品商店。</FONT><BR><BR><FONT COLOR=\"#C6B262\">空无一物的大桶。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：狩猎补给品商店。</FONT><BR><BR><FONT COLOR=\"#C6B262\">制作各类陷阱必不可少的工具。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园蜂房；狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">营养价值很高的蜂蜜。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：狩猎场</FONT><BR><BR><FONT COLOR=\"#C6B262\">怪物的粪便。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：珠宝调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">制作技能珠的必备素材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：千狩模式战利品</FONT><BR><BR><FONT COLOR=\"#C6B262\">白色宝石的碎粒，可以通过珠宝生产技能还原成白色宝石。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：千狩模式战利品</FONT><BR><BR><FONT COLOR=\"#C6B262\">绿色宝石的碎粒，可以通过珠宝生产技能还原成绿色宝石。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：千狩模式战利品</FONT><BR><BR><FONT COLOR=\"#C6B262\">粉色宝石的碎粒，可以通过珠宝生产技能还原成粉色宝石。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：千狩模式战利品</FONT><BR><BR><FONT COLOR=\"#C6B262\">蓝色宝石的碎粒，可以通过珠宝生产技能还原成蓝色宝石。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：5~20级狩猎场；狩猎补给品商店。</FONT><BR><BR><FONT COLOR=\"#C6B262\">小块的野兽之骨，能够用来制作一般的装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：20~40级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">中等大小的野兽之骨，能够用来制作优秀的装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：40级以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">大块的野兽之骨，能够用来制作高级别的装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：美食生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">从三个蓝蘑菇中精选而出，增强效果要比一般的蓝蘑菇强。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：美食生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">从十个蓝蘑菇中挑选而出，增强效果要更加强力。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：美食生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">从数量众多的蓝蘑菇中挑选而出，增强效果极佳的蓝蘑菇。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：美食生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">从不计其数的蓝蘑菇中挑选而出的极品蓝蘑菇，增强效果无比强大。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：美食生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">从一般的蜂蜜中挑选而出的优质蜂蜜，味道非常不错。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：美食生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">从精选蜂蜜中挑选而出的特选蜂蜜，仅仅只是闻到香味就已经欲罢不能了。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：美食生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">从特选蜂蜜中挑选而出的秘选蜂蜜，传说只有证明美食制作之魂的猎人才能品尝到。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：美食生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">从秘选蜂蜜中挑选而出的极选蜂蜜，美味程度无法用语言形容。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">用怪力之种研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">用耐力之种研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">用曼陀罗花研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">用落阳草研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">用不死虫研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">一种特殊的由于寒冷而形成的晶状结片。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">用火药草研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">用雷光虫研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">能将素材和药品的效果中量提升的药剂。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">能将素材和药品的效果大幅提升。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">能将素材和药品的效果提升至极致的药剂。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和。</FONT><BR><BR><FONT COLOR=\"#C6B262\">用紫参草研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和。</FONT><BR><BR><FONT COLOR=\"#C6B262\">用乌骨草研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和。</FONT><BR><BR><FONT COLOR=\"#C6B262\">用绿钟草研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">“差评！”</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明调和</FONT><BR><BR><FONT COLOR=\"#C6B262\">用秘制角笛研磨而成的粉末。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：【千狩试炼】</FONT><BR><BR><FONT COLOR=\"#C6B262\">集齐足够决心之证，可以在锻造处用于打造“特典公会装备”的部件</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：在线礼包、日程表奖励、活动礼包</FONT><BR><BR><FONT COLOR=\"#C6B262\">可以用于兑换各种稀有物品，是十分珍贵的货币。兑换地点：梅杰波尔坦</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~3级庄园矿场；狩猎场。</FONT><BR>":
     "<FONT COLOR=\"#6285C6\" >来源：在线礼包</FONT><BR><BR><FONT COLOR=\"#C6B262\">坚硬的爬虫甲壳，用于制造“特典甲虫装备”。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：在线礼包</FONT><BR><BR><FONT COLOR=\"#C6B262\">轻巧的爬虫羽翅，用于制造“特典甲虫装备”。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：【激运烤肉祭狩猎场】</FONT><BR><BR><FONT COLOR=\"#C6B262\">用于证明猎人曾经参加激运烤肉祭狩猎场的凭证。可通过此券于次日12:00~20:00前往官网活动页面进行烤肉小游戏，并通过积分兑换各类奖品。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：【激运烤肉祭狩猎场】</FONT><BR><BR><FONT COLOR=\"#C6B262\">激运烤肉祭狩猎场奖励的特殊货币，可以在锻造商人处以此兑换特典装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：喵喵异闻录</FONT><BR><BR><FONT COLOR=\"#C6B262\">最常见的端材，和其他材料的结合度非常高，是制造艾露装备的必备材料。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：二星以上喵喵异闻录</FONT><BR><BR><FONT COLOR=\"#C6B262\">较为常见的端材，质地较为坚硬，用作材料可以提升艾露装备的坚固程度。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：五星以上喵喵异闻录</FONT><BR><BR><FONT COLOR=\"#C6B262\">珍贵的端材，有较高的硬度并且表面富有光泽，适用于制作进阶艾露装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：六星以上喵喵异闻录</FONT><BR><BR><FONT COLOR=\"#C6B262\">几种稀有金属的混合端材，不仅坚固无比并且具有良好的延展性，是制作高级艾露装备的不二选择。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：猎人星级挑战卡片奖励</FONT><BR><BR><FONT COLOR=\"#C6B262\">表面散发着淡淡的光芒，可以完美和各种材料融合引发不可思议的效果，是制作高级艾露装备的不二选择。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：珠宝生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">制造高级装饰品的素材，非常稀少，传说还可以用来制造特有的胚珠。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：艾露猫日常任务、喵喵异闻录</FONT><BR><BR><FONT COLOR=\"#C6B262\">猫婆婆一直在收集的物品，可以用来兑换艾露猫的宝物袋。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：黍老伯兑换、六星喵喵异闻录白金评价</FONT><BR><BR><FONT COLOR=\"#C6B262\">猫婆婆一直在收集的物品，可以用来兑换艾露猫的秘籍袋。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：登录礼包【柒】</FONT><BR><BR><FONT COLOR=\"#C6B262\">可在艾露游乐团处兑换时装</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：任务奖励</FONT><BR><BR><FONT COLOR=\"#C6B262\">神秘武器的碎片，用于兑换神秘装备宝箱</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：活动期间登录礼包</FONT><BR><BR><FONT COLOR=\"#C6B262\">可在活动页面兑换专属特权</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1~6级庄园虫栖地；5~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">蜘蛛的巢穴，布满了带有韧性的蛛丝，能制作成工具使用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级种子概率产出；直接种植霜降草可产出；15~25级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">能吸附部分有害物质的植物，生长于路边，还带有一丝丝凉�。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2~3级庄园育菇木床；15~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">具有特殊功能的蘑菇，仅仅采集到就够让人兴奋的了。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：狩猎场；狩猎补给品商店。</FONT><BR><BR><FONT COLOR=\"#C6B262\">中空状的小骨头，可以用来制作瓶或者子弹。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级庄园鱼塘；20~39级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">在鱼塘中常见的鱼，可以用来制造子弹。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级庄园鱼塘；20~39级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">奇特的鱼类，体内似乎含有可以制造爆炸的物质。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级庄园鱼塘；40~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">体内的爆炸物质积累一定程度后，似乎能对别的物质起到反应的鱼类。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级庄园鱼塘；20~39级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">死亡后会飞溅在各处的鱼，会很难收拾。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级庄园鱼塘；40~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">肉质纤细以至于死亡后会分散成过多部分，作为子弹的素材很常用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级种子概率产出；直接种植贯通果可产出；5~15级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">硬度能贯穿骨肉，是植物中的特殊种类。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：2级庄园鱼塘；20~39级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">尖利的嘴部能穿透船板，在冲出水面时令人防不胜防。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：3级庄园鱼塘；40~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">有时似乎能直接冲破渔网，令渔民们相当头疼的鱼。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：1级庄园鱼塘；5~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">被认为是美味料理的素材，在鱼塘中能捕获到。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在矿石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在木材中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在晶石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在骨质中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在上晶石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在上骨质中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在坚晶石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在坚骨质中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在重晶石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在重骨质中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在秘石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在龙木中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在上秘石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在上龙木中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在坚秘石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在坚龙木中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在重秘石中混入怪物素材，用于制造艾露猫武器的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商店精算点兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">在重龙木中混入怪物素材，用于制造艾露猫防具的端材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：王立普通委托</FONT><BR><BR><FONT COLOR=\"#C6B262\">持有古文书才能接取王立精英委托进行狩猎</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：战队赛制活动</FONT><BR><BR><FONT COLOR=\"#C6B262\">可以用于兑换各种稀有物品</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：商团委托</FONT><BR><BR><FONT COLOR=\"#C6B262\">可以用于兑换怪物时装</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：4级庄园虫栖地；50级及以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">拥有美丽蓝色翅膀的蝴蝶。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：4级庄园虫栖地；50级及以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">眼睛巨大的蜻蜓，捕获后加工可以成为素材使用。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：4级庄园矿场；50级及以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">能够精炼出灵鹤钢材的金属矿石。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：4级庄园矿场；50级及以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">闪耀光芒的水晶，硬度较强，被猎人们收纳后用来制作装备。</FONT>":
     "<FONT COLOR=\"#6285C6\" >主要来源：王立委托。</FONT><BR><BR><FONT COLOR=\"#C6B262\">高级装备素材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：20级及以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">上等的龙之骨，入手相对困难，是武器和防具不可或缺的素材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：20级及以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">上等兽骨，骨质较一般的兽骨要好很多，制作装备必备的素材。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：喵喵币兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">高级装备镶嵌珠宝额外所需求的材料</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：喵喵币兑换</FONT><BR><BR><FONT COLOR=\"#C6B262\">激活技能组内技能的素材</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：4级种子概率产出；直接种植龟壳果可产出；50级及以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">长相好似乌龟壳的植物所产下的果实。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：4级种子概率产出；直接种植紫参草可产出；50级及以上狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">有延年益寿的功效！</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：5级庄园矿场；45~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">能够与各种金属产生共鸣的不可思议矿石。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：5级庄园矿场；45~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">黑暗中发出微小亮光的水晶，形成条件不为人知。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：5级庄园虫栖地；45~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">常年生活在红土泥地中的蚁类，虫身呈现淡绿色，很容易分辨出来。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：5级庄园虫栖地；45~55级狩猎场。</FONT><BR><BR><FONT COLOR=\"#C6B262\">栖覆在松叶当中的蚕蛹，还未成长为成虫。</FONT>":
     "<FONT COLOR=\"#68A16A\" >持有：可在铁匠处突破防具</FONT><BR><FONT COLOR=\"#6285C6\" >来源：猎人生活</FONT><BR><BR><FONT COLOR=\"#C6B262\">突破防具的关键素材，对热量会产生特别的反应，提炼后与防具融合能够增加防具的强度。</FONT>":
     "<BR><FONT COLOR=\"#C6B262\">呼叫艾露猫支援队，加快农场采集点的恢复速度</FONT>":
     "<BR><FONT COLOR=\"#C6B262\">凭此券可到《怪物猎人OL》官网相关活动页面获取价值120元的《侏罗纪世界》电影票。兑换时间6月11日——6月21日。</FONT>":
     "<BR><FONT COLOR=\"#C6B262\">猎人们通过使用“成长防具兑换券”，可在梅杰波尔坦和米拉德村的雷欧处自由兑换各种的专为猎人们精心打造的强力装备</FONT>":
     "<BR><FONT COLOR=\"#C6B262\">猎人们通过使用“成长武器兑换券”，可在梅杰波尔坦和米拉德村的雷欧处自由兑换各种的专为猎人们精心打造的强力武器</FONT>":
     "<BR><FONT COLOR=\"#C6B262\">莉薇丢失的货品，可以找莉薇兑换奖励</FONT>":
     "<BR><FONT COLOR=\"#C6B262\">上古武器的残片，可用于兑换武器或其他稀有道具。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：分解护石</FONT><BR><BR><FONT COLOR=\"#C6B262\">高纯度的结晶体，可以用于精铸护石。</FONT>":
     "<FONT COLOR=\"#68A16A\" >持有：可在铁匠处突破武器</FONT><BR><FONT COLOR=\"#6285C6\" >来源：猎人生活</FONT><BR><BR><FONT COLOR=\"#C6B262\">对热量会产生特别的反应，提炼后与武器融合能够增加武器的强度</FONT>":
     "<FONT COLOR=\"#68A16A\" >持有：可调和高级武器玉</FONT><BR><FONT COLOR=\"#6285C6\" >来源：王立委托以上狩猎场</FONT><BR><BR><FONT COLOR=\"#C6B262\">传说能够突破装备能力界限的玉。</FONT>":
     "<FONT COLOR=\"#6285C6\" >来源：发明生产</FONT><BR><BR><FONT COLOR=\"#C6B262\">能将素材和药品的效果提升至极致的药剂。</FONT>":
