var skillsArray = [
    {
      "data": [
        "Ambush",
        "伏击",
        "Assassin Tech +1",
        "刺杀术+1",
        "Assassin Tech +2",
        "刺杀术+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases damage to monsters not targeting you, but they will become more likely to target you."
      ]
    },
    {
      "data": [
        "Anti-bacterial",
        "抗菌",
        "Bacteria Cancel",
        "耐菌",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Attack",
        "攻击",
        "Attack Up (S)",
        "攻击力提升（小）",
        "Attack Up (M)",
        "攻击力提升（中）",
        "Attack Up (L)",
        "攻击力提升（大）",
        "Attack Up (XL)",
        "攻击力提升（超）",
        "Attack Up (XXL)",
        "攻击力提升（极）",
        "Attack Down (S)",
        "攻击力降低（小）",
        "Attack Down (M)",
        "攻击力降低（中）",
        "Attack Down (L)",
        "攻击力降低（大）",
        "Attack Down (XL)",
        "攻击力降低（超）",
        "Description"
      ]
    },
    {
      "data": [
        "Bleeding",
        "刺伤",
        "Negate Bleeding",
        "刺伤无效",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Butterfly Dance",
        "蝶舞",
        "Butterfly Form",
        "化蝶",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Cold Res",
        "耐寒",
        "Cold Cancel",
        "耐寒",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Constitution",
        "体术",
        "Constitution +1",
        "体术+1",
        "Constitution +2",
        "体术+2",
        "Constitution +3",
        "体术+3",
        "",
        "",
        "",
        "",
        "Constitution -1",
        "体术-1",
        "Constitution -2",
        "体术-2",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Handicraft",
        "匠",
        "Sharpness +1",
        "斩味等级+1",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Crit Draw",
        "拔刀会心",
        "Critical Draw",
        "拔刀术",
        "Critical Draw Max",
        "拔刀术极",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Defense",
        "防御",
        "Defense Up (S)",
        "防御力提升（小）",
        "Defense Up (M)",
        "防御力提升（中）",
        "Defense Up (L)",
        "防御力提升（大）",
        "Defense Up (XL)",
        "防御力提升（超）",
        "Defense Up (XXL)",
        "防御力提升（极）",
        "Defense Down (S)",
        "防御力降低（小）",
        "Defense Down (M)",
        "防御力降低（中）",
        "Defense Down (L)",
        "防御力降低（大）",
        "Defense Down (XL)",
        "防御力降低（超）",
        "Description"
      ]
    },
    {
      "data": [
        "Destroyer",
        "重击",
        "Partbreaker",
        "破坏王",
        "Destruction God",
        "破坏神",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Dragon Atk",
        "龙属性攻击",
        "Dragon Atk +1",
        "龙属性攻击强化+1",
        "Dragon Atk +2",
        "龙属性攻击强化+2",
        "Dragon Atk +3",
        "龙属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Dragon Atk Down",
        "龙属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Eating",
        "食事",
        "Speed Eating",
        "速食",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Slow Eater",
        "慢食",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Evade Dist",
        "回避距离",
        "Evade Dist +1",
        "回避距离+1",
        "Evade Dist +2",
        "回避距离+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Evasion",
        "回避性能",
        "Evasion +1",
        "回避性能+1",
        "Evasion +2",
        "回避性能+2",
        "Evasion +3",
        "回避性能+3",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Expert",
        "达人",
        "Critical Eye +1",
        "见切+1",
        "Critical Eye +2",
        "见切+2",
        "Critical Eye +3",
        "见切+3",
        "Critical Eye +4",
        "见切+4",
        "Critical Eye +5",
        "见切+5",
        "Critical Eye -1",
        "见切-1",
        "Critical Eye -2",
        "见切-2",
        "Critical Eye -3",
        "见切-3",
        "Critical Eye -4",
        "见切-4",
        "Description"
      ]
    },
    {
      "data": [
        "FastCharge",
        "集中",
        "Concentrate",
        "集中",
        "Focus",
        "专注",
        "Attentive",
        "凝神",
        "",
        "",
        "",
        "",
        "Distraction",
        "杂念",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Fencing",
        "剑术",
        "Mind's Eye",
        "心眼",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Fire Atk",
        "火属性攻击",
        "Fire Atk +1",
        "火属性攻击强化+1",
        "Fire Atk +2",
        "火属性攻击强化+2",
        "Fire Atk +3",
        "火属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Fire Atk Down",
        "火属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Fire Res",
        "火耐性",
        "Fire Res +1",
        "火属性耐性强化+1",
        "Fire Res +2",
        "火属性耐性强化+2",
        "Fire Res +3",
        "火属性耐性强化+3",
        "",
        "",
        "",
        "",
        "Fire Res Down",
        "火属性耐性弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Gluttony",
        "吃货",
        "Gourmand",
        "大胃王",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Guard",
        "防御性能",
        "Guard +1",
        "防御性能+1",
        "Guard +2",
        "防御性能+2",
        "Guard +3",
        "防御性能+3",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Guard Up",
        "防御强化",
        "Guard Boost",
        "防御强化",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Guts",
        "根性",
        "Guts",
        "根性",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Health",
        "体力",
        "Health +1",
        "体力强化+1",
        "Health +2",
        "体力强化+2",
        "Health +3",
        "体力强化+3",
        "Health +4",
        "体力强化+4",
        "Health +5",
        "体力强化+5",
        "Health -1",
        "体力弱化-1",
        "Health -2",
        "体力弱化-2",
        "Health -3",
        "体力弱化-3",
        "Health -4",
        "体力弱化-4",
        "Description"
      ]
    },
    {
      "data": [
        "Hearing",
        "听觉保护",
        "Earplugs",
        "耳栓",
        "HG Earplugs",
        "高级耳栓",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Heat Res",
        "耐暑",
        "Heat Cancel",
        "耐暑",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Herb King",
        "药王",
        "Herbal Daren",
        "草药达人",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Hormone",
        "荷尔蒙",
        "Attract",
        "吸引",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Hunger",
        "饥饿感",
        "Halve Hunger",
        "饥饿感减半",
        "Negate Hunger",
        "饱腹",
        "",
        "",
        "",
        "",
        "",
        "",
        "Raise Hunger",
        "饥饿感增加",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Ice Atk",
        "冰属性攻击",
        "Ice Itk +1",
        "冰属性攻击强化+1",
        "Ice Atk +2",
        "冰属性攻击强化+2",
        "Ice Atk +3",
        "冰属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Ice Atk Down",
        "冰属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Ice Res",
        "冰耐性",
        "Ice Res +1",
        "冰属性耐性强化+1",
        "Ice Res +2",
        "冰属性耐性强化+2",
        "Ice Res +3",
        "冰属性耐性强化+3",
        "",
        "",
        "",
        "",
        "Ice Res Down",
        "冰属性耐性弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Violent Strike",
        "会心术",
        "Violent Strike",
        "暴击",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "KO",
        "KO术",
        "Knockout King",
        "KO术",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Loading",
        "装填术",
        "Load Up",
        "装填术",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Mud/Snow",
        "耐泥雪",
        "Negate Mud/Snow",
        "耐泥雪",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Normal Up",
        "通常弹强化",
        "Normal/Rapid Up",
        "通常弹&连射矢强化",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Paralysis",
        "麻痹抵抗",
        "Negate Paralysis",
        "麻痹免疫",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Double Paralysis",
        "麻痹倍化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Pellet Up",
        "散弹强化",
        "Pellet/Spread Up",
        "散弹/矢强化",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Perception",
        "观察眼",
        "Capture Guru",
        "观察眼",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Pierce Up",
        "贯通弹强化",
        "Pierce/Pierce Up",
        "贯通弹/矢强化",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Poison",
        " 毒抵抗",
        "Halve Poison",
        "毒减半",
        "Negate Poison",
        "毒无效",
        "",
        "",
        "",
        "",
        "",
        "",
        "Double Poison",
        "毒倍化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Potential",
        "底力",
        "Adrenaline +1",
        "火事场力+1",
        "Adrenaline +2",
        "火事场力+2",
        "Adrenaline +3",
        "火事场力+3",
        "",
        "",
        "",
        "",
        "Worrywart",
        "不安",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Protection",
        "加护",
        "Holy Blessing",
        "精灵的守护",
        "Divine Blessing",
        "精灵王的加护",
        "",
        "",
        "",
        "",
        "",
        "",
        "Evil Blessing",
        "恶灵的加护",
        "Demonic Blessing",
        "恶灵王的加护",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Psychic",
        "千里眼",
        "Detect",
        "探知",
        "Autotracker",
        "自动标记",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Rec Speed",
        "回复速度",
        "Rec Speed +1",
        "回复速度+1",
        "Rec Speed +2",
        "回复速度+2",
        "Rec Speed +3",
        "回复速度+3",
        "",
        "",
        "",
        "",
        "Rec Speed -1",
        "   回复速度-1",
        "Rec Speed -2",
        "   回复速度-2",
        "Rec Speed -3",
        "   回复速度-3",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Recoil",
        "反动",
        "Recoil Down +1",
        "反动减轻+1",
        "Recoil Down +2",
        "反动减轻+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "Recoil Up",
        "反动增大",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Reload Spd",
        "快速装填",
        "Reload Spd +1",
        "上弹速度强化+1",
        "Reload Spd +2",
        "上弹速度强化+2",
        "Reload Spd +3",
        "上弹速度强化+3",
        "",
        "",
        "",
        "",
        "Reload Spd -1",
        "上弹速度强化-1",
        "Reload Spd -2",
        "上弹速度强化-2",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Resilience",
        "强韧",
        "See Through +1",
        "看破+1",
        "See Through +2",
        "看破+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Sense",
        "气息",
        "Sneak",
        "隐秘",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Taunt",
        "挑衅",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Sharpener",
        "研磨师",
        "Speed Sharpening",
        "砥石使用高速化",
        "High Speed Sharpening",
        "砥石使用极速化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Slow Sharpening",
        "砥石使用低速化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Sharpness",
        "锋利度",
        "Sharp",
        "业物",
        "Razor Sharp",
        "无锋",
        "",
        "",
        "",
        "",
        "",
        "",
        "Blunt Edge",
        "钝刀",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Sleep",
        "睡眠抵抗",
        "Negate Sleep",
        "睡眠免疫",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Double Sleep",
        "睡眠倍化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "SpeedSetup",
        "高速设置",
        "Trap Master",
        "陷阱师",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Spirit",
        "斗魂",
        "Challenger +1",
        "挑战者+1",
        "Challenger +2",
        "挑战者+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Stam Recov",
        "耐力回复",
        "Stam Recov +1",
        "耐力回复+1",
        "Stam Recov +2",
        "耐力回复+2",
        "Stam Recov +3",
        "耐力回复+3",
        "",
        "",
        "",
        "",
        "Stam Recov -1",
        "耐力回复-1",
        "Stam Recov -2",
        "耐力回复-2",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Status",
        "特殊攻击",
        "Status Atk +1",
        "状态异常攻击+1",
        "Status Atk +2",
        "状态异常攻击+2",
        "Status Atk +3",
        "状态异常攻击+3",
        "",
        "",
        "",
        "",
        "Status Atk Down",
        "状态异常攻击-1",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Stun",
        "气绝抵抗",
        "Halve Stun",
        "气绝减半",
        "Negate Stun",
        "气绝免疫",
        "",
        "",
        "",
        "",
        "",
        "",
        "Double Stun",
        "气绝倍化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Survivor",
        "逆境",
        "Fortify",
        "不屈",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Tenderizer",
        "痛击",
        "Weakness Exploit",
        "弱点特效",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Thunder Res",
        "雷耐性",
        "Thunder Res +1",
        "雷属性耐性强化+1",
        "Thunder Res +2",
        "雷属性耐性强化+2",
        "Thunder Res +3",
        "雷属性耐性强化+3",
        "",
        "",
        "",
        "",
        "Thunder Res Down",
        "雷属性耐性弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "ThunderAtk",
        "雷属性攻击",
        "Thunder Atk +1",
        "雷属性攻击强化+1",
        "Thunder Atk +2",
        "雷属性攻击强化+2",
        "Thunder Atk +3",
        "雷属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Thunder Atk Down",
        "雷属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Tremor Res",
        "耐震",
        "Tremor Res",
        "耐震",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Tripping Power",
        "倒地之力",
        "Tripping Power",
        "绊术",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Unscathed",
        "无伤",
        "Peak Performance",
        "无伤",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Water Atk",
        "水属性攻击",
        "Water Atk +1",
        "水属性攻击强化+1",
        "Water Atk +2",
        "水属性攻击强化+2",
        "Water Atk +3",
        "水属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Water Atk Down",
        "水属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Wide-Range",
        "广域化",
        "Wide-Range +1",
        "广域化+1",
        "Wide-Range +2",
        "广域化+2",
        "Wide-Range +3",
        "广域化+3",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Wind Res",
        "风压抵抗",
        "Windproof (Lo)",
        "风压（小）无效",
        "Windproof (Hi)",
        "风压（大）无效",
        "Dragon Windproof",
        "龙风压无效",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Sleep C+",
        "",
        "Use Sleep Coat",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Stamina",
        "",
        "Marathon Runner +1",
        "",
        "Marathon Runner +2",
        "",
        "Short Sprinter",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Hunter Life",
        "",
        "Wilderness Survival",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Water Res",
        "",
        "Water Res +1",
        "",
        "Water Res +2",
        "",
        "Water Res +3",
        "",
        "",
        "",
        "",
        "",
        "Water Res Down",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Dragon Res",
        "",
        "Dragon Res +1",
        "",
        "Dragon Res +2",
        "",
        "Dragon Res +3",
        "",
        "",
        "",
        "",
        "",
        "Dragon Res Down",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Rec Level",
        "",
        "Recovery Up",
        "",
        "Recovery Up Large",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Recovery Down",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "PowerEater",
        "",
        "Alloy Stomach",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "BBQ Expert",
        "",
        "BBQ Expert",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Rapid Fire",
        "",
        "Bonus Shot +1",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Maestro",
        "",
        "Horn Maestro",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Artillery",
        "",
        "Artillery Exptert",
        "",
        "Artillery God",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Crustacians Hunter",
        "",
        "Crustacians Killer",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Bird Dragons Hunter",
        "",
        "Bird Dragons Killer",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
    {
      "data": [
        "Dragons Hunter",
        "",
        "Dragons Killer",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Description"
      ]
    },
]