var skillsArray = [
    {
      "data": [
        "Ambush",
        "伏击",
        "Assassin Tech +1",
        "刺杀术+1",
        "Assassin Tech +2",
        "刺杀术+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases damage to monsters not targeting you, but they will become more likely to target you"
      ]
    },
    {
      "data": [
        "Anti-bacterial",
        "抗菌",
        "Bacteria Cancel",
        "耐菌",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Prevent stench"
      ]
    },
    {
      "data": [
        "Attack",
        "攻击",
        "Attack Up (S)",
        "攻击力提升（小）",
        "Attack Up (M)",
        "攻击力提升（中）",
        "Attack Up (L)",
        "攻击力提升（大）",
        "Attack Up (XL)",
        "攻击力提升（超）",
        "Attack Up (XXL)",
        "攻击力提升（极）",
        "Attack Down (S)",
        "攻击力降低（小）",
        "Attack Down (M)",
        "攻击力降低（中）",
        "Attack Down (L)",
        "攻击力降低（大）",
        "Attack Down (XL)",
        "攻击力降低（超）",
        "Increases/decreases Attack"
      ]
    },
    {
      "data": [
        "Bleeding",
        "刺伤",
        "Negate Bleeding",
        "刺伤无效",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Prevents Bleeding"
      ]
    },
    {
      "data": [
        "Butterfly Dance",
        "蝶舞",
        "Butterfly Form",
        "化蝶",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases Attack/Defense when Ultimate Guage is charged"
      ]
    },
    {
      "data": [
        "Cold Res",
        "耐寒",
        "Cold Cancel",
        "耐寒",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Negates All Cold"
      ]
    },
    {
      "data": [
        "Constitution",
        "体术",
        "Constitution +1",
        "体术+1",
        "Constitution +2",
        "体术+2",
        "Constitution +3",
        "体术+3",
        "",
        "",
        "",
        "",
        "Constitution -1",
        "体术-1",
        "Constitution -2",
        "体术-2",
        "",
        "",
        "",
        "",
        "Slows Stamina depletion when evading/blocking"
      ]
    },
    {
      "data": [
        "Handicraft",
        "匠",
        "Sharpness +1",
        "斩味等级+1",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases your weapon's Sharpness"
      ]
    },
    {
      "data": [
        "Crit Draw",
        "拔刀会心",
        "Critical Draw",
        "拔刀术",
        "Critical Draw Max",
        "拔刀术极",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases Affinity for all draw attacks"
      ]
    },
    {
      "data": [
        "Defense",
        "防御",
        "Defense Up (S)",
        "防御力提升（小）",
        "Defense Up (M)",
        "防御力提升（中）",
        "Defense Up (L)",
        "防御力提升（大）",
        "Defense Up (XL)",
        "防御力提升（超）",
        "Defense Up (XXL)",
        "防御力提升（极）",
        "Defense Down (S)",
        "防御力降低（小）",
        "Defense Down (M)",
        "防御力降低（中）",
        "Defense Down (L)",
        "防御力降低（大）",
        "Defense Down (XL)",
        "防御力降低（超）",
        "Increases/decreases Defense"
      ]
    },
    {
      "data": [
        "Destroyer",
        "重击",
        "Partbreaker",
        "破坏王",
        "Destruction God",
        "破坏神",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Makes it easier to break or sever parts of large monsters"
      ]
    },
    {
      "data": [
        "Dragon Atk",
        "龙属性攻击",
        "Dragon Atk +1",
        "龙属性攻击强化+1",
        "Dragon Atk +2",
        "龙属性攻击强化+2",
        "Dragon Atk +3",
        "龙属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Dragon Atk Down",
        "龙属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases the power of Dragon attacks and shots"
      ]
    },
    {
      "data": [
        "Eating",
        "食事",
        "Speed Eating",
        "速食",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Slow Eater",
        "慢食",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases meat-eating speed"
      ]
    },
    {
      "data": [
        "Evade Dist",
        "回避距离",
        "Evade Dist +1",
        "回避距离+1",
        "Evade Dist +2",
        "回避距离+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases evade distance"
      ]
    },
    {
      "data": [
        "Evasion",
        "回避性能",
        "Evasion +1",
        "回避性能+1",
        "Evasion +2",
        "回避性能+2",
        "Evasion +3",
        "回避性能+3",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Extends the invulnerability period when evading"
      ]
    },
    {
      "data": [
        "Expert",
        "达人",
        "Critical Eye +1",
        "见切+1",
        "Critical Eye +2",
        "见切+2",
        "Critical Eye +3",
        "见切+3",
        "Critical Eye +4",
        "见切+4",
        "Critical Eye +5",
        "见切+5",
        "Critical Eye -1",
        "见切-1",
        "Critical Eye -2",
        "见切-2",
        "Critical Eye -3",
        "见切-3",
        "Critical Eye -4",
        "见切-4",
        "Increases affinity"
      ]
    },
    {
      "data": [
        "FastCharge",
        "集中",
        "Concentrate",
        "集中",
        "Focus",
        "专注",
        "Attentive",
        "凝神",
        "",
        "",
        "",
        "",
        "Distraction",
        "杂念",
        "",
        "",
        "",
        "",
        "",
        "",
        "Speeds/slows charge of charge attacks"
      ]
    },
    {
      "data": [
        "Fencing",
        "剑术",
        "Mind's Eye",
        "心眼",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Prevents your attacks from being deflected"
      ]
    },
    {
      "data": [
        "Fire Atk",
        "火属性攻击",
        "Fire Atk +1",
        "火属性攻击强化+1",
        "Fire Atk +2",
        "火属性攻击强化+2",
        "Fire Atk +3",
        "火属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Fire Atk Down",
        "火属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases the power of Fire attacks and shots"
      ]
    },
    {
      "data": [
        "Fire Res",
        "火耐性",
        "Fire Res +1",
        "火属性耐性强化+1",
        "Fire Res +2",
        "火属性耐性强化+2",
        "Fire Res +3",
        "火属性耐性强化+3",
        "",
        "",
        "",
        "",
        "Fire Res Down",
        "火属性耐性弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases Fire resistance"
      ]
    },
    {
      "data": [
        "Gluttony",
        "吃货",
        "Gourmand",
        "大胃王",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases the effecacy of meat that raises max Stamina"
      ]
    },
    {
      "data": [
        "Guard",
        "防御性能",
        "Guard +1",
        "防御性能+1",
        "Guard +2",
        "防御性能+2",
        "Guard +3",
        "防御性能+3",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases the likelihood of standing your ground when blocking an attack"
      ]
    },
    {
      "data": [
        "Guard Up",
        "防御强化",
        "Guard Boost",
        "防御强化",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Causes previously unblockable attacks to become blockable"
      ]
    },
    {
      "data": [
        "Guts",
        "根性",
        "Guts",
        "根性",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Prevents fainting a single time if struck with a lethal blow"
      ]
    },
    {
      "data": [
        "Health",
        "体力",
        "Health +1",
        "体力强化+1",
        "Health +2",
        "体力强化+2",
        "Health +3",
        "体力强化+3",
        "Health +4",
        "体力强化+4",
        "Health +5",
        "体力强化+5",
        "Health -1",
        "体力弱化-1",
        "Health -2",
        "体力弱化-2",
        "Health -3",
        "体力弱化-3",
        "Health -4",
        "体力弱化-4",
        "Increases/decreases maximum Health"
      ]
    },
    {
      "data": [
        "Hearing",
        "听觉保护",
        "Earplugs",
        "耳栓",
        "HG Earplugs",
        "高级耳栓",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Negate the effects of large monster's roars"
      ]
    },
    {
      "data": [
        "Heat Res",
        "耐暑",
        "Heat Cancel",
        "耐暑",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Negates the damage incurred from heat and lava"
      ]
    },
    {
      "data": [
        "Herb King",
        "药王",
        "Herbal Daren",
        "草药达人",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Herbs can recover a large amount of health"
      ]
    },
    {
      "data": [
        "Hormone",
        "荷尔蒙",
        "Attract",
        "吸引",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases your attack when in party with opposite sex"
      ]
    },
    {
      "data": [
        "Hunger",
        "饥饿感",
        "Halve Hunger",
        "饥饿感减半",
        "Negate Hunger",
        "饱腹",
        "",
        "",
        "",
        "",
        "",
        "",
        "Raise Hunger",
        "饥饿感增加",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases maximum Stamina depletion speed"
      ]
    },
    {
      "data": [
        "Ice Atk",
        "冰属性攻击",
        "Ice Itk +1",
        "冰属性攻击强化+1",
        "Ice Atk +2",
        "冰属性攻击强化+2",
        "Ice Atk +3",
        "冰属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Ice Atk Down",
        "冰属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases the power of Ice attacks and shots"
      ]
    },
    {
      "data": [
        "Ice Res",
        "冰耐性",
        "Ice Res +1",
        "冰属性耐性强化+1",
        "Ice Res +2",
        "冰属性耐性强化+2",
        "Ice Res +3",
        "冰属性耐性强化+3",
        "",
        "",
        "",
        "",
        "Ice Res Down",
        "冰属性耐性弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases Ice resistance"
      ]
    },
    {
      "data": [
        "Violent Strike",
        "会心术",
        "Violent Strike",
        "暴击",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "After not dealing a critical strike for a while, your next attack will increase critical chance"
      ]
    },
    {
      "data": [
        "KO",
        "KO术",
        "Knockout King",
        "KO术",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Makes it easier to Stun monsters"
      ]
    },
    {
      "data": [
        "Loading",
        "装填术",
        "Load Up",
        "装填术",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases Bowguns and Gunlance ammo capacity and charge capacity of Bow"
      ]
    },
    {
      "data": [
        "Mud/Snow",
        "耐泥雪",
        "Negate Mud/Snow",
        "耐泥雪",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Negates being coated in snow or mud"
      ]
    },
    {
      "data": [
        "Normal Up",
        "通常弹强化",
        "Normal/Rapid Up",
        "通常弹&连射矢强化",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases the power of Normal S and Rapid-type arrows"
      ]
    },
    {
      "data": [
        "Paralysis",
        "麻痹抵抗",
        "Negate Paralysis",
        "麻痹免疫",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Double Paralysis",
        "麻痹倍化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Prevents/doubles Paralysis"
      ]
    },
    {
      "data": [
        "Pellet Up",
        "散弹强化",
        "Pellet/Spread Up",
        "散弹/矢强化",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases the power of Pellet S and Sread-type arrows"
      ]
    },
    {
      "data": [
        "Perception",
        "观察眼",
        "Capture Guru",
        "观察眼",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Grants knowledge of when a large marked monster can be captured"
      ]
    },
    {
      "data": [
        "Pierce Up",
        "贯通弹强化",
        "Pierce/Pierce Up",
        "贯通弹/矢强化",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases the power of Pierce S and Pierce-type arrows"
      ]
    },
    {
      "data": [
        "Poison",
        " 毒抵抗",
        "Halve Poison",
        "毒减半",
        "Negate Poison",
        "毒无效",
        "",
        "",
        "",
        "",
        "",
        "",
        "Double Poison",
        "毒倍化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Prevents/Doubles Poison"
      ]
    },
    {
      "data": [
        "Potential",
        "底力",
        "Adrenaline +1",
        "火事场力+1",
        "Adrenaline +2",
        "火事场力+2",
        "Adrenaline +3",
        "火事场力+3",
        "",
        "",
        "",
        "",
        "Worrywart",
        "不安",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases Defense boost and attack when Health is below 40% of max"
      ]
    },
    {
      "data": [
        "Protection",
        "加护",
        "Holy Blessing",
        "精灵的守护",
        "Divine Blessing",
        "精灵王的加护",
        "",
        "",
        "",
        "",
        "",
        "",
        "Evil Blessing",
        "恶灵的加护",
        "Demonic Blessing",
        "恶灵王的加护",
        "",
        "",
        "",
        "",
        "Sometimes decreases/increases damage taken"
      ]
    },
    {
      "data": [
        "Psychic",
        "千里眼",
        "Detect",
        "探知",
        "Autotracker",
        "自动标记",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Displays large monsters on the map as if they are marked"
      ]
    },
    {
      "data": [
        "Rec Speed",
        "回复速度",
        "Rec Speed +1",
        "回复速度+1",
        "Rec Speed +2",
        "回复速度+2",
        "Rec Speed +3",
        "回复速度+3",
        "",
        "",
        "",
        "",
        "Rec Speed -1",
        "   回复速度-1",
        "Rec Speed -2",
        "   回复速度-2",
        "Rec Speed -3",
        "   回复速度-3",
        "",
        "",
        "Speeds recovery from temporary damage (red portion of Health Guage)"
      ]
    },
    {
      "data": [
        "Recoil",
        "反动",
        "Recoil Down +1",
        "反动减轻+1",
        "Recoil Down +2",
        "反动减轻+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "Recoil Up",
        "反动增大",
        "",
        "",
        "",
        "",
        "",
        "",
        "Reduces/increases Bowgun recoil"
      ]
    },
    {
      "data": [
        "Reload Spd",
        "快速装填",
        "Reload Spd +1",
        "上弹速度强化+1",
        "Reload Spd +2",
        "上弹速度强化+2",
        "Reload Spd +3",
        "上弹速度强化+3",
        "",
        "",
        "",
        "",
        "Reload Spd -1",
        "上弹速度强化-1",
        "Reload Spd -2",
        "上弹速度强化-2",
        "",
        "",
        "",
        "",
        "Speeds up Bowgun Loading and Bow Coatings"
      ]
    },
    {
      "data": [
        "Resilience",
        "强韧",
        "See Through +1",
        "看破+1",
        "See Through +2",
        "看破+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Within 10 seconds of taking damage, the next attack will deal reduced damage"
      ]
    },
    {
      "data": [
        "Sense",
        "气息",
        "Sneak",
        "隐秘",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Taunt",
        "挑衅",
        "",
        "",
        "",
        "",
        "",
        "",
        "Decreases/increases the likelihood of being targeted by monsters"
      ]
    },
    {
      "data": [
        "Sharpener",
        "研磨师",
        "Speed Sharpening",
        "砥石使用高速化",
        "High Speed Sharpening",
        "砥石使用极速化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Slow Sharpening",
        "砥石使用低速化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Speeds up/slows down weapon sharpening"
      ]
    },
    {
      "data": [
        "Sharpness",
        "锋利度",
        "Sharp",
        "业物",
        "Razor Sharp",
        "无锋",
        "",
        "",
        "",
        "",
        "",
        "",
        "Blunt Edge",
        "钝刀",
        "",
        "",
        "",
        "",
        "",
        "",
        "Halves/doubles the rate at which your weapon loses Sharpness"
      ]
    },
    {
      "data": [
        "Sleep",
        "睡眠抵抗",
        "Negate Sleep",
        "睡眠免疫",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Double Sleep",
        "睡眠倍化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Prevents/doubles sleep"
      ]
    },
    {
      "data": [
        "SpeedSetup",
        "高速设置",
        "Trap Master",
        "陷阱师",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Speeds up trap-setting and bomb-setting time"
      ]
    },
    {
      "data": [
        "Spirit",
        "斗魂",
        "Challenger +1",
        "挑战者+1",
        "Challenger +2",
        "挑战者+2",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases Attack and Affinity when a large monster in the area becomes angry"
      ]
    },
    {
      "data": [
        "Stam Recov",
        "耐力回复",
        "Stam Recov +1",
        "耐力回复+1",
        "Stam Recov +2",
        "耐力回复+2",
        "Stam Recov +3",
        "耐力回复+3",
        "",
        "",
        "",
        "",
        "Stam Recov -1",
        "耐力回复-1",
        "Stam Recov -2",
        "耐力回复-2",
        "",
        "",
        "",
        "",
        "Increases/decreases Stamina recovery speed"
      ]
    },
    {
      "data": [
        "Status",
        "特殊攻击",
        "Status Atk +1",
        "状态异常攻击+1",
        "Status Atk +2",
        "状态异常攻击+2",
        "Status Atk +3",
        "状态异常攻击+3",
        "",
        "",
        "",
        "",
        "Status Atk Down",
        "状态异常攻击-1",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases the potency of abnormal status attacks"
      ]
    },
    {
      "data": [
        "Stun",
        "气绝抵抗",
        "Halve Stun",
        "气绝减半",
        "Negate Stun",
        "气绝免疫",
        "",
        "",
        "",
        "",
        "",
        "",
        "Double Stun",
        "气绝倍化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Reduces/doubles stun power"
      ]
    },
    {
      "data": [
        "Survivor",
        "逆境",
        "Fortify",
        "不屈",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases Attack and Defense every time you fall in battle"
      ]
    },
    {
      "data": [
        "Tenderizer",
        "痛击",
        "Weakness Exploit",
        "弱点特效",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases damage when striking body parts that your attacks are highly effective"
      ]
    },
    {
      "data": [
        "Thunder Res",
        "雷耐性",
        "Thunder Res +1",
        "雷属性耐性强化+1",
        "Thunder Res +2",
        "雷属性耐性强化+2",
        "Thunder Res +3",
        "雷属性耐性强化+3",
        "",
        "",
        "",
        "",
        "Thunder Res Down",
        "雷属性耐性弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases Thunder resistance"
      ]
    },
    {
      "data": [
        "ThunderAtk",
        "雷属性攻击",
        "Thunder Atk +1",
        "雷属性攻击强化+1",
        "Thunder Atk +2",
        "雷属性攻击强化+2",
        "Thunder Atk +3",
        "雷属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Thunder Atk Down",
        "雷属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases the power of Thunder attacks and shots"
      ]
    },
    {
      "data": [
        "Tremor Res",
        "耐震",
        "Tremor Res",
        "耐震",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Prevents staggering from tremors created by large monsters"
      ]
    },
    {
      "data": [
        "Tripping Power",
        "倒地之力",
        "Tripping Power",
        "绊术",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Make it easier to knock down monsters"
      ]
    },
    {
      "data": [
        "Unscathed",
        "无伤",
        "Peak Performance",
        "无伤",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases Attack when your Health Guage is full"
      ]
    },
    {
      "data": [
        "Water Atk",
        "水属性攻击",
        "Water Atk +1",
        "水属性攻击强化+1",
        "Water Atk +2",
        "水属性攻击强化+2",
        "Water Atk +3",
        "水属性攻击强化+3",
        "",
        "",
        "",
        "",
        "Water Atk Down",
        "水属性攻击弱化",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases the power of Water attacks and shots"
      ]
    },
    {
      "data": [
        "Wide-Range",
        "广域化",
        "Wide-Range +1",
        "广域化+1",
        "Wide-Range +2",
        "广域化+2",
        "Wide-Range +3",
        "广域化+3",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Transfers a portion of the effects of certain items to companions in the same area"
      ]
    },
    {
      "data": [
        "Wind Res",
        "风压抵抗",
        "Windproof (Lo)",
        "风压（小）无效",
        "Windproof (Hi)",
        "风压（大）无效",
        "Dragon Windproof",
        "龙风压无效",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Lessens/Negates Wind Pressure from monsters"
      ]
    },
    {
      "data": [
        "Sleep C+",
        "",
        "Use Sleep Coat",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Allows Sleep coatings to be set when equipped with a Bow"
      ]
    },
    {
      "data": [
        "Stamina",
        "",
        "Marathon Runner +1",
        "",
        "Marathon Runner +2",
        "",
        "Short Sprinter",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Slows down Stamina depletion for actions which continuously drain Stamina (such as dashing)"
      ]
    },
    {
      "data": [
        "Hunter Life",
        "",
        "Wilderness Survival",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increase movement speed when carrying eggs, and theft immunity"
      ]
    },
    {
      "data": [
        "Water Res",
        "",
        "Water Res +1",
        "",
        "Water Res +2",
        "",
        "Water Res +3",
        "",
        "",
        "",
        "",
        "",
        "Water Res Down",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases Water resistance"
      ]
    },
    {
      "data": [
        "Dragon Res",
        "",
        "Dragon Res +1",
        "",
        "Dragon Res +2",
        "",
        "Dragon Res +3",
        "",
        "",
        "",
        "",
        "",
        "Dragon Res Down",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases/decreases Dragon resistance"
      ]
    },
    {
      "data": [
        "Rec Level",
        "",
        "Recovery Up",
        "",
        "Recovery Up Large",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Recovery Down",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases the efficacy of Health recovery items"
      ]
    },
    {
      "data": [
        "PowerEater",
        "",
        "Alloy Stomach",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Eating mushrooms will result in different effects"
      ]
    },
    {
      "data": [
        "BBQ Expert",
        "",
        "BBQ Expert",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Auto-cook meat"
      ]
    },
    {
      "data": [
        "Rapid Fire",
        "",
        "Bonus Shot +1",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Allows one extra shot to be fired while Rapid Firing"
      ]
    },
    {
      "data": [
        "Maestro",
        "",
        "Horn Maestro",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases the effect time of Hunting Horn melodies"
      ]
    },
    {
      "data": [
        "Artillery",
        "",
        "Artillery Exptert",
        "",
        "Artillery God",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases power of Bowgun, Gunlance, Wyvern's Fire & Crag shots"
      ]
    },
    {
      "data": [
        "Crustacians Hunter",
        "",
        "Crustacians Killer",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases attacks against Crustacian Monsters"
      ]
    },
    {
      "data": [
        "Bird Dragons Hunter",
        "",
        "Bird Dragons Killer",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases attacks against Bird Dragon Monsters"
      ]
    },
    {
      "data": [
        "Dragons Hunter",
        "",
        "Dragons Killer",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Increases attacks against Dragon Monsters"
      ]
    },
]