var translations = {
    "双刀":"Dual Blades",
    "大剑":"Greatsword",
    "大锤":"Hammer",
    "太刀":"Longsword",
    "弓":"Bow",
    "弩炮":"Bowgun",
    "片手剑":"Sword and Shield",
    "狩猎笛":"Hunting Horn",
    "铳枪":"Gunlance",
    "长枪":"Lance",

    "E键":"E",
    "人物前方向所对应的方向键":"LMB while pressing the direction of your characters front",
    "人物后方向所对应的方向键":"LMB while pressing the direction of your characters back",
    "人物左手方向所对应的方向键":"RMB while pressing the direction of your characters left",
    "右键":"RMB",
    "左键":"LMB",
    "左键+右键":"LMB + RMB",
    "按住<右键>后松开":"Press and hold RMB after release",
    "按住<左键>后松开":"Press and hold LMB after release of LMB",
    "方向键":"Release RMB while pressing a direction",
    "松开<右键>":"Release RMB",
    "空格键":"Space Bar",

    "强击瓶":"Power Coating",
    "接击瓶":"C.Range Coating",
    "毒瓶":"Poison Coating",
    "眠瓶":"Sleep Coating",
    "麻瓶":"Para Coating",

    "地型1级":"Arrow Bomb Lv1",
    "地型2级":"Arrow Bomb Lv2",
    "地型3级":"Arrow Bomb Lv3",
    "天型1级":"Arrow Rain Lv1",
    "天型2级":"Arrow Rain Lv2",
    "天型3级":"Arrow Rain Lv3",

    "中":"Med",
    "大":"Large",
    "小":"Small",
    "快":"Fast",
    "慢":"Slow",

    "冰结弹":"Freeze S",
    "彻甲榴弹1级":"Crag S Lv1",
    "彻甲榴弹2级":"Crag S Lv2",
    "彻甲榴弹3级":"Crag S Lv3",
    "散弹1级":"Pellet S Lv1",
    "散弹2级":"Pellet S Lv2",
    "散弹3级":"Pellet S Lv3",
    "水冷弹":"Water S",
    "火焰弹":"Flaming S",
    "猛毒弹":"Poison S",
    "电击弹":"Thunder S",
    "致眠弹":"Sleep S",
    "贯通弹1级":"Pierce S Lv1",
    "贯通弹2级":"Pierce S Lv2",
    "贯通弹3级":"Pierce S Lv3",
    "通常弹1级":"Normal S Lv1",
    "通常弹2级":"Normal S Lv2",
    "通常弹3级":"Normal S Lv3",
    "通常弹Lv3":"Normal S Lv3",
    "麻痹弹":"Para S",

    "蓄力":"Charge ",
    "速射2发":"Rapid ",
    "速射3发":"Rapid ",

    "KO术":"KO",
    "伏击":"Ambush",
    "会心术":"Knowing Technique",
    "体力":"Health",
    "体术":"Constitution",
    "倒地之力":"Tripping Power",
    "冰属性攻击":"Ice Atk",
    "冰耐性":"Ice Res",
    "刺伤":"Bleeding",
    "剑术":"Fencing",
    "加护":"Protection",
    "匠":"Handicraft",
    "千里眼":"Psychic",
    "反动":"Recoil",
    "古龙猎人":"Elder Dragon Hunter",
    "吃货":"Gluttony",
    "听觉保护":"Hearing",
    "回复速度":"Rec Speed",
    "回避性能":"Evasion",
    "回避距离":"Evade Dist",
    "孤注一掷":"Desperation",
    "广域化":"Wide-Range",
    "底力":"Potential",
    "强韧":"Resilience",
    "快速装填":"Reload Spd",
    "快速防御":"Auto-Guard",
    "恢复量":"Recovery Amount",
    "抗菌":"Anti-bacterial",
    "拔刀会心":"Crit Draw",
    "攻击":"Attack",
    "散弹增加":"Pellet S Carry",
    "散弹强化":"Pellet Up",
    "斗魂":"Spirit",
    "无伤":"Unscathed",
    "根性":"Guts",
    "榴弹增加":"Crag S Carry",
    "毒弹增加":"Poison C+",
    "毒抵抗":"Poison",
    "气息":"Sense",
    "气绝抵抗":"Stun",
    "水属性攻击":"Water Atk",
    "水耐性":"Water Res",
    "火属性攻击":"Fire Atk",
    "火耐性":"Fire Res",
    "炮术":"Artillery",
    "烤肉达人":"Barbecue Daren",
    "牙兽猎人":"Fanged Beast Hunter",
    "特殊攻击":"Status",
    "猎人生活":"Hunter Life",
    "甲壳猎人":"Carapacean Hunter",
    "痛击":"Tenderizer",
    "眠弹增加":"Sleep C+",
    "睡眠抵抗":"Sleep",
    "研磨师":"Sharpener",
    "笛":"Flute",
    "耐力回复":"Stam Recov",
    "耐力消耗下降":"Endurance Consumption Down",
    "耐寒":"Cold Res",
    "耐暑":"Heat Res",
    "耐泥雪":"Mud/Snow",
    "耐震":"Tremor Res",
    "药王":"Herb King",
    "荷尔蒙":"Hormone",
    "蝶舞":"Butterfly Dance",
    "装填术":"Loading",
    "观察眼":"Perception",
    "贯通弹增加":"Pierce S Carry",
    "贯通弹强化":"Pierce Up",
    "达人":"Expert",
    "逆境":"Survivor",
    "通常弹增加":"Normal S Carry",
    "通常弹强化":"Normal Up",
    "速射":"Rapid Fire",
    "采集":"Collection",
    "重击":"Destroyer",
    "锁气绝":"Stun Lock",
    "锋利度":"Sharpness",
    "防御":"Defense",
    "防御强化":"Guard Up",
    "防御性能":"Guard",
    "集中":"FastCharge",
    "雷属性攻击":"ThunderAtk",
    "雷耐性":"Thunder Res",
    "风压抵抗":"Wind Res",
    "飞龙猎人":"Flying Wyvern Hunter",
    "食事":"Eating",
    "饥饿感":"Hunger",
    "高速设置":"SpeedSetup",
    "鱼龙猎人":"Piscine Wyvern Hunter",
    "鸟龙猎人":"Bird Wyvern Hunter",
    "麻痹弹增加":"Para C+",
    "麻痹抵抗":"Paralysis",
    "龙属性攻击":"Dragon Atk",
    "龙耐性":"Dragon Res",

    "上弹速度强化+1":"Reload Spd +1",
    "上弹速度强化+2":"Reload Spd +2",
    "上弹速度强化+3":"Reload Spd +3",
    "上弹速度强化-1":"Reload Spd -1",
    "上弹速度强化-2":"Reload Spd -2",
    "不安":"Worrywart",
    "不屈":"Fortify",
    "专注":"Focus",
    "业物":"Sharp",
    "体力弱化-1":"Health -1",
    "体力弱化-2":"Health -2",
    "体力弱化-3":"Health -3",
    "体力弱化-4":"Health -4",
    "体力强化+1":"Health +1",
    "体力强化+2":"Health +2",
    "体力强化+3":"Health +3",
    "体力强化+4":"Health +4",
    "体力强化+5":"Health +5",
    "体术+1":"Constitution +1",
    "体术+2":"Constitution +2",
    "体术+3":"Constitution +3",
    "体术-1":"Constitution -1",
    "体术-2":"Constitution -2",
    "冰属性攻击弱化":"Ice Atk Down",
    "冰属性攻击强化+1":"Ice Atk +1",
    "冰属性攻击强化+2":"Ice Atk +2",
    "冰属性攻击强化+3":"Ice Atk +3",
    "冰属性耐性弱化":"Ice Res Down",
    "冰属性耐性强化+1":"Ice Res +1",
    "冰属性耐性强化+2":"Ice Res +2",
    "冰属性耐性强化+3":"Ice Res +3",
    "凝神":"Attentive",
    "刺伤无效":"Negate Bleeding",
    "刺杀术+1":"Assassin Tech +1",
    "刺杀术+2":"Assassin Tech +2",
    "化蝶":"Butterfly Form",
    "卸甲":"Unload Armor",
    "反动减轻+1":"Recoil Down +1",
    "反动减轻+2":"Recoil Down +2",
    "反动增大":"Recoil Up",
    "古龙杀手":"Elder Dragon Killer",
    "吃血量减少":"Recovery Down",
    "吃血量增加":"Recovery Up",
    "吃血量大幅增加":"Recovery Up Large",
    "吸引":"Attract",
    "吹笛名人":"Horn Maestro",
    "回复速度+1":"Rec Speed +1",
    "回复速度+2":"Rec Speed +2",
    "回复速度+3":"Rec Speed +3",
    "回复速度-1":"Rec Speed -1",
    "回复速度-2":"Rec Speed -2",
    "回复速度-3":"Rec Speed -3",
    "回避性能+1":"Evasion +1",
    "回避性能+2":"Evasion +2",
    "回避性能+3":"Evasion +3",
    "回避距离+1":"Evade Dist +1",
    "回避距离+2":"Evade Dist +2",
    "大胃王":"Gourmand",
    "广域化+1":"Wide-Range +1",
    "广域化+2":"Wide-Range +2",
    "广域化+3":"Wide-Range +3",
    "弱点特效":"Weakness Exploit",
    "心眼":"Mind's Eye",
    "恶灵王的加护":"Demonic Blessing",
    "恶灵的加护":"Evil Blessing",
    "慢食":"Slow Eater",
    "拔刀术":"Critical Draw",
    "拔刀术极":"Critical Draw Max",
    "挑战者+1":"Challenger +1",
    "挑战者+2":"Challenger +2",
    "挑衅":"Taunt",
    "探知":"Detect",
    "攻击力提升（中）":"Attack Up (M)",
    "攻击力提升（大）":"Attack Up (L)",
    "攻击力提升（小）":"Attack Up (S)",
    "攻击力提升（极）":"Attack Up (XXL)",
    "攻击力提升（超）":"Attack Up (XL)",
    "攻击力降低（中）":"Attack Down (M)",
    "攻击力降低（大）":"Attack Down (L)",
    "攻击力降低（小）":"Attack Down (S)",
    "攻击力降低（超）":"Attack Down (XL)",
    "散弹/矢强化":"Pellet/Spread Up",
    "散弹LV1+2":"Pellet S Lv1 +2",
    "散弹LV1/2/3装填数+2":"Pellet S Lv1/2/3 +2",
    "散弹LV1/2装填数+2":"Pellet S Lv1/2 +2",
    "斩味等级+1":"Sharpness +1",
    "无锋":"Razor Sharp",
    "暴击":"Violent Strike",
    "杂念":"Distraction",
    "榴弹LV1+2":"Crag S Lv1 +2",
    "榴弹LV1/2/3装填数+2":"Crag S Lv1/2/3 +2",
    "榴弹LV1/2装填数+2":"Crag S Lv1/2 +2",
    "毒倍化":"Double Poison",
    "毒减半":"Halve Poison",
    "毒无效":"Negate Poison",
    "毒瓶/毒弹追加":"Use Poison Coat",
    "气绝倍化":"Double Stun",
    "气绝免疫":"Negate Stun",
    "气绝减半":"Halve Stun",
    "水属性攻击弱化":"Water Atk Down",
    "水属性攻击强化+1":"Water Atk +1",
    "水属性攻击强化+2":"Water Atk +2",
    "水属性攻击强化+3":"Water Atk +3",
    "水属性耐性弱化":"Water Res Down",
    "水属性耐性强化+1":"Water Res +1",
    "水属性耐性强化+2":"Water Res +2",
    "水属性耐性强化+3":"Water Res +3",
    "火事场力+1":"Adrenaline +1",
    "火事场力+2":"Adrenaline +2",
    "火事场力+3":"Adrenaline +3",
    "火属性攻击弱化":"Fire Atk Down",
    "火属性攻击强化+1":"Fire Atk +1",
    "火属性攻击强化+2":"Fire Atk +2",
    "火属性攻击强化+3":"Fire Atk +3",
    "火属性耐性弱化":"Fire Res Down",
    "火属性耐性强化+1":"Fire Res +1",
    "火属性耐性强化+2":"Fire Res +2",
    "火属性耐性强化+3":"Fire Res +3",
    "炮术师":"Artillery Exptert",
    "炮术王":"Artillery God",
    "牙兽杀手":"Fanged Beast Killer",
    "状态异常攻击+1":"Status Atk +1",
    "状态异常攻击+2":"Status Atk +2",
    "状态异常攻击+3":"Status Atk +3",
    "状态异常攻击-1":"Status Atk Down",
    "甲壳杀手":"Carapacean Killer",
    "看破+1":"See Through +1",
    "看破+2":"See Through +2",
    "眠瓶/弹追加":"Use Sleep Coat",
    "睡眠倍化":"Double Sleep",
    "睡眠免疫":"Negate Sleep",
    "砥石使用低速化":"Slow Sharpening",
    "砥石使用极速化":"High Speed Sharpening",
    "砥石使用高速化":"Speed Sharpening",
    "破坏王":"Partbreaker",
    "破坏神":"Destruction God",
    "精灵王的加护":"Divine Blessing",
    "精灵的守护":"Holy Blessing",
    "绊术":"Tripping Power",
    "耐力回复+1":"Stam Recov +1",
    "耐力回复+2":"Stam Recov +2",
    "耐力回复+3":"Stam Recov +3",
    "耐力回复-1":"Stam Recov -1",
    "耐力回复-2":"Stam Recov -2",
    "耐暑":"Heat Cancel",
    "耐泥雪":"Negate Mud/Snow",
    "耐菌":"Bacteria Cancel",
    "耳栓":"Earplugs",
    "自动标记":"Autotracker",
    "茸食":"Alloy Stomach",
    "草药达人":"Herbal Daren",
    "装填术":"Load Up",
    "见切+1":"Critical Eye +1",
    "见切+2":"Critical Eye +2",
    "见切+3":"Critical Eye +3",
    "见切+4":"Critical Eye +4",
    "见切+5":"Critical Eye +5",
    "见切-1":"Critical Eye -1",
    "见切-2":"Critical Eye -2",
    "见切-3":"Critical Eye -3",
    "见切-4":"Critical Eye -4",
    "贯通弹/矢强化":"Pierce/Pierce Up",
    "贯通弹LV1/2/3装填数+3":"Pierce S Lv1/2/3 +3",
    "贯通弹LV1/2装填数+3":"Pierce S Lv1/2 +3",
    "贯通弹LV1装填数+3":"Pierce S Lv1 +3",
    "通常弹&连射矢强化":"Normal/Rapid Up",
    "通常弹LV1/2/3装填数+3":"Normal S Lv1/2/3 +3",
    "通常弹LV1/2装填数+3":"Normal S Lv1/2 +3",
    "通常弹LV1装填数+3":"Normal S Lv1 +3",
    "速射子弹+1":"Bonus Shot +1",
    "速食":"Speed Eating",
    "采取+1":"Take +1",
    "采取+2":"Take +2",
    "野外生存":"Wilderness Survival",
    "钝刀":"Blunt Edge",
    "防御力提升（中）":"Defense Up (M)",
    "防御力提升（大）":"Defense Up (L)",
    "防御力提升（小）":"Defense Up (S)",
    "防御力提升（极）":"Defense Up (XXL)",
    "防御力提升（超）":"Defense Up (XL)",
    "防御力降低（中）":"Defense Down (M)",
    "防御力降低（大）":"Defense Down (L)",
    "防御力降低（小）":"Defense Down (S)",
    "防御力降低（超）":"Defense Down (XL)",
    "防御强化":"Guard Boost",
    "防御性能+1":"Guard +1",
    "防御性能+2":"Guard +2",
    "防御性能+3":"Guard +3",
    "陷阱师":"Trap Master",
    "隐秘":"Sneak",
    "集中":"Concentrate",
    "雷属性攻击弱化":"Thunder Atk Down",
    "雷属性攻击强化+1":"Thunder Atk +1",
    "雷属性攻击强化+2":"Thunder Atk +2",
    "雷属性攻击强化+3":"Thunder Atk +3",
    "雷属性耐性弱化":"Thunder Res Down",
    "雷属性耐性强化+1":"Thunder Res +1",
    "雷属性耐性强化+2":"Thunder Res +2",
    "雷属性耐性强化+3":"Thunder Res +3",
    "顿足":"Slow Sprinter",
    "风压（大）无效":"Windproof (Hi)",
    "风压（小）无效":"Windproof (Lo)",
    "飞人+1":"Marathon Runner +1",
    "飞人+2":"Marathon Runner +2",
    "飞龙杀手":"Flying Wyvern Killer",
    "饥饿感减半":"Halve Hunger",
    "饥饿感增加":"Raise Hunger",
    "饱腹":"Negate Hunger",
    "高级耳栓":"HG Earplugs",
    "鱼龙杀手":"Piscine Wyvern Killer",
    "鸟龙杀手":"Bird Wyvern Killer",
    "麻瓶/弹追加":"Use Para Coat",
    "麻痹倍化":"Double Paralysis",
    "麻痹免疫":"Negate Paralysis",
    "龙属性攻击弱化":"Dragon Atk Down",
    "龙属性攻击强化+1":"Dragon Atk +1",
    "龙属性攻击强化+2":"Dragon Atk +2",
    "龙属性攻击强化+3":"Dragon Atk +3",
    "龙属性耐性弱化":"Dragon Res Down",
    "龙属性耐性强化+1":"Dragon Res +1",
    "龙属性耐性强化+2":"Dragon Res +2",
    "龙属性耐性强化+3":"Dragon Res +3",
    "龙风压无效":"Dragon Windproof",

    "一定概率受到的伤害值增加":"Chance that when recieving damage it gets increased",
    "一定概率受到的伤害值降低":"Chance that when recieving damage it gets reduced",
    "不会进入中毒状态":"Cannot be Poisoned",
    "不会进入刺伤状态":"Negates Bleeding condition",
    "不会进入气绝状态":"Cannot be Stunned",
    "不会进入泥人或雪人状态":"Prevents being coated in snow or mud",
    "不会进入睡眠状态":"Cannot be put to Sleep",
    "不会进入臭气状态":"Prevent stench",
    "不会进入麻痹状态":"Cannot be Paralysed",
    "不受到震地效果的影响":"Prevents staggering from tremors created by large monsters",
    "不容易成为怪物的目标":"Reduce chance of being targeted by monster",
    "中毒状态的时间减半":"Poison time halved",
    "中量增加会心几率":"Increase Critical Chance",
    "中量提升体力上限":"Increase amount of Health",
    "中量提升攻击力":"Increase Attack",
    "中量提升防御力":"Increase Defense",
    "中量降低会心几率":"Reduce Critical Chance",
    "中量降低体力上限":"Reduce amount of Health",
    "中量降低攻击力":"Reduce Attack",
    "中量降低防御力":"Reduce Defense",
    "体力满时攻击力增加":"Increases Attack at full health",
    "体力较低时，防御力和攻击力得到大幅提升":"Dramatically increase Defense and Attack when at low health",
    "体力较低时，防御力和攻击力得到提升":"Increase Defense and Attack when at low health",
    "体力较低时，防御力提升":"Increase Defense and Attack when at low health",
    "体力降低时，防御力和攻击力减少":"Decrease Defense and Attack when at low health",
    "使得弩可以使用LV1/LV2/LV3散弹，如果已有该子弹，则弹夹变长":"You can use Pellet S Lvl1/2/3; if you already have these your clip size is extended",
    "使得弩可以使用LV1/LV2/LV3榴弹，如果已有该子弹，则弹夹变长":"You can use Crag S Lvl1/2/3; if you already have these your clip size is extended",
    "使得弩可以使用LV1/LV2/LV3贯通弹，如果已有该子弹，则弹夹变长":"You can use Pierce S Lvl1/2/3; if you already have these your clip size is extended",
    "使得弩可以使用LV1/LV2/LV3通常弹，如果已有该子弹，则弹夹变长":"You can use Normal S Lvl1/2/3; if you already have these your clip size is extended",
    "使得弩可以使用LV1/LV2散弹，如果已有该子弹，则弹夹变长":"You can use Pellet S Lvl1/2; if you already have these your clip size is extended",
    "使得弩可以使用LV1/LV2榴弹，如果已有该子弹，则弹夹变长":"You can use Crag S Lvl1/2; if you already have these your clip size is extended",
    "使得弩可以使用LV1/LV2贯通弹，如果已有该子弹，则弹夹变长":"You can use Pierce S Lvl1/2; if you already have these your clip size is extended",
    "使得弩可以使用LV1/LV2通常弹，如果已有该子弹，则弹夹变长":"You can use Normal S Lvl1/2; if you already have these your clip size is extended",
    "使得弩可以使用LV1散弹，如果已有该子弹，则弹夹变长":"You can use Pellet S Lvl1; if you already have these your clip size is extended",
    "使得弩可以使用LV1榴弹，如果已有该子弹，则弹夹变长":"You can use Crag S Lvl1; if you already have these your clip size is extended",
    "使得弩可以使用LV1贯通弹，如果已有该子弹，则弹夹变长":"You can use Pierce S Lvl1; if you already have these your clip size is extended",
    "使得弩可以使用LV1通常弹，如果已有该子弹，则弹夹变长":"You can use Normal S Lvl1; if you already have these your clip size is extended",
    "使用回复药等道具时，恢复量增加":"When using health recovery items gain increased Recovery",
    "使用回复药等道具时，恢复量大幅增加":"When using health recovery items gain a substantial amount of Recovery",
    "使用回复药等道具时，恢复量较少":"When using health recovery items the amount recovered is lessened",
    "使用对应类型的远程武器时，可以使用毒瓶或毒弹":"Can use Poison C (Bow) or Poison S (Bowgun)",
    "使用对应类型的远程武器时，可以使用眠瓶或眠弹":"Can use Sleep C (Bow) or Sleep S (Bowgun)",
    "使用对应类型的远程武器时，可以使用麻瓶或麻弹":"Can use Para C (Bow) or Para S (Bowgun)",
    "使用放置类道具时速度显著加快":"Speeds up trap-setting and bomb-setting time",
    "免疫怪物造成的小型和大型风压":"Immune to small and large wind pressure",
    "免疫怪物造成的小型和大型风压以及古龙造成的龙风压":"Immune to small and large wind pressure (including elder dragons)",
    "免疫怪物造成的小型风压":"Immune to small wind pressure",
    "冰属性攻击伤害大幅提升":"Dramatically increase Ice Attack",
    "冰属性攻击伤害显著提升":"Significantly increase Ice Attack",
    "冰属性攻击伤害略微提升":"Slightly increase Ice Attack",
    "冰属性耐性大幅提升":"Dramatically increase Ice Res",
    "冰属性耐性显著提升":"Significantly increase Ice Res",
    "冰属性耐性略微提升":"Slightly increase Ice Res",
    "冰属性耐性衰减":"Reduce Ice Res",
    "击中怪物弱点部位时，有额外伤害加成":"Increases damage when striking body parts that your attacks are highly effective",
    "受到攻击后10秒内再次受到的首次攻击伤害降低,一段时间内仅触发一次":"Reduce damage after being attacked again within 10 seconds of the first attack; Has a cooldown",
    "受到攻击后15秒内再次受到的首次攻击伤害显著降低，一段时间内仅触发一次":"Significantly reduce damage after being attacked again within 15 seconds of the first attack; Has a cooldown",
    "可以抵御大多数大型怪物的咆哮":"Can withstand most large monster roars",
    "可以抵御部分大型怪物的咆哮":"Can withstand some large monster roars",
    "可以知道地图中大型怪物的位置":"Shows location of large monsers",
    "可以知道地图中大型怪物的濒死状态便于捕获":"Shows when monster is dying to help with monster capture",
    "吃药品时候有一定几率恢复耐力":"Increases the effecacy of meat that raises max Stamina",
    "吃蘑菇有不同效果":"Eating mushrooms have different effects",
    "回复能力大幅增强":"Greatly increase Rec Speed",
    "回复能力显著增强":"Significantly increase Rec Speed",
    "回复能力略微增强":"Slightly increase Rec Speed",
    "回复能力降低":"Reduce Rec Speed",
    "在剩余一定体力的情况下，不会被一击必杀":"Prevents fainting a single time if struck with a lethal blow; except one hit kills",
    "在怪物身上存在染色效果时，可以知道大型怪物什么时候能被捕捉":"Shows when monster is dying (when marked with paintball) to help with monster capture",
    "增加攻击的倒地效果":"Makes it easier to Trip monsters",
    "增加攻击的气绝效果":"Makes it easier to Stun monsters",
    "增加散弹和散射矢的伤害":"Increases the power of Pellet S and Sread-type arrows",
    "增加翻滚的无敌时间":"Increase dodge invincible time",
    "增加翻滚的移动距离":"Increase dodge roll distance",
    "增加耐力回复速度":"Increase Stamina recovery speed",
    "增加贯通矢和贯通弹的伤害":"Increases the power of Pierce S and Pierce-type arrows",
    "增加连射矢和通常弹的伤害":"Increases the power of Normal S and Rapid-type arrows",
    "增强防御时可抵御的攻击强度":"Increase amount of attack you can guard against",
    "大剑、锤、弓蓄力时间缩短10%；双刀鬼人槽积攒效率+30%；太刀练气槽积攒效率+10%":"Sword, hammer, and bow charge time reduced by 10%; Dual blades Demon gauge accumulation efficiency +30%; Longsword Spirit guage accumulation efficiency +10%",
    "大剑、锤、弓蓄力时间缩短20%；双刀鬼人槽积攒效率+50%；太刀练气槽积攒效率+20%":"Sword, hammer, and bow charge time reduced by 20%; Dual blades Demon gauge accumulation efficiency +50%; Longsword Spirit guage accumulation efficiency +20%",
    "大剑、锤、弓蓄力时间缩短5%；双刀鬼人槽积攒效率+15%；太刀练气槽积攒效率+5%":"Sword, hammer, and bow charge time reduced by 5%; Dual blades Demon gauge accumulation efficiency +15%; Longsword Spirit guage accumulation efficiency +5%",
    "大剑和锤蓄力所需时间延长":"Requirements extended",
    "大剑或片手剑可以在招式的间隙转入防御状态":"When equiped with a Greatsword or Sword and Shield, you will automatically guard frontal attacks when not attacking ",
    "大幅减少翻滚及受身的耐力消耗":"Significantly reduce the stamina cost of dodging",
    "大幅增加会心几率":"Dramatically increase Critical Chance",
    "大幅增加翻滚的无敌时间":"Greatly increase dodge invincible time",
    "大幅增加翻滚的移动距离":"Significantly increase dodge roll distance",
    "大幅增强防御时可抵御的攻击强度":"Greatly increase amount of attack you can guard against",
    "大幅提升体力上限":"Dramatically increase amount of Health",
    "大幅提升攻击力":"Dramatically increase Attack",
    "大幅提升防御力":"Dramatically increase Defense",
    "大幅降低体力上限":"Dramatically reduce amount of Health",
    "大幅降低攻击力":"Dramatically reduce Attack",
    "大幅降低耐力回复速度":"Significantly reduce Stamina recovery speed",
    "大幅降低防御力":"Dramatically reduce Defense",
    "奥义槽全满是增加攻击力和防御力":"Increases Attack and Defense when Ultimate Guage is charged",
    "容易对怪物造成部位破坏":"Likely to damage breakable parts of a monster",
    "寒冷效果无效":"Negates Cold effects",
    "对古龙种造成的伤害增加":"Increase the damage done to certain monster species",
    "对牙兽种造成的伤害增加":"Increase the damage done to certain monster species",
    "对甲壳种造成的伤害增加":"Increase the damage done to certain monster species",
    "对飞龙种造成的伤害增加":"Increase the damage done to certain monster species",
    "对鱼龙种造成的伤害增加":"Increase the damage done to certain monster species",
    "对鸟龙种造成的伤害增加":"Increase the damage done to certain monster species",
    "异常状态攻击的蓄积值减少":"Reduce Status Attack",
    "异常状态攻击的蓄积值大幅增加":"Dramatically increase Status Attack",
    "异常状态攻击的蓄积值少量增加":"Slightly increase Status Attack",
    "异常状态攻击的蓄积值显著增加":"Significantly increase Status Attack",
    "弩子弹装填的速度中等下降":"Decrease speed of Bowgun bullet loading and Bow coat applying",
    "弩子弹装填的速度中等提升":"Improve speed of Bowgun bullet loading and Bow coat applying",
    "弩子弹装填的速度显著提升":"Significantly improve speed of Bowgun bullet loading and Bow coat applying",
    "弩子弹装填的速度略微下降":"slightly decrease speed of Bowgun bullet loading and Bow coat applying",
    "弩子弹装填的速度略微提升":"Slightly improve speed of Bowgun bullet loading and Bow coat applying",
    "弩炮射击时，后坐力减少":"Reduce Bowgun recoil",
    "弩炮射击时，后坐力变大":"Increase Bowgun recoil",
    "弩炮射击时，后坐力大幅减少":"Significantly reduce Bowgun recoil",
    "弩炮速射时增加一发子弹":"Increase Rapid-Fire bullet count by one",
    "弩装填数+1，可以使用弓箭4级蓄力":"Gives +1 shot to bowgun; Unlocks Bow Lvl4 charge",
    "当怪物愤怒时，攻击力小幅提升":"Slightly increase your Attack when monster is angry",
    "当怪物愤怒时，攻击力提升":"Increase your Attack when monster is angry",
    "当持续一定时间没有触发会心时，下一次攻击增加会心机率":"After not dealing a critical strike for a while, your next attack will increase critical chance",
    "当自己使用恢复类及肉类时，对同区域内的队员都提供较大比例的效果":"Transfers a large portion of the effects of certain items to companions in the same area",
    "当自己使用恢复类道具时，对一定范围内的队员提供一定比例的效果":"Transfers a portion of the effects of certain items to companions in the same area",
    "当自己使用恢复类道具时，对同区域内的队员提供较大比例的效果":"Transfers a greater portion of the effects of certain items to companions in the same area",
    "当血量值较高时，通过降低防御力增加伤害":"When health is high, increase your Attack by reducing your Defense",
    "当队伍中存在异性的情况下，攻击力得到一定提升":"Increases your attack when in party with opposite sex",
    "拔刀攻击时，会心率增加":"When attacking out of sheathe critical rate is increased",
    "拔刀攻击时，会心率大幅增加":"When attacking out of sheathe critical rate is increased substantially",
    "搬蛋时移动速度增加，并且偷盗免疫":"Increases movement speed when moving eggs; theft immunity",
    "攻击时不会弹刀":"Prevents your attacks from being deflected",
    "攻击时增加斩味消耗":"Increase Sharpness consumption",
    "攻击时大幅降低斩味消耗":"Greatly reduce Sharpness consumption",
    "攻击时降低斩味消耗":"Reduce Sharpness consumption",
    "斩味增加一档":"Adds more sharpness to weapon",
    "显著减少翻滚及受身的耐力消耗":"Reduce the stamina cost of dodging",
    "显著增加会心几率":"Significantly increase Critical Chance",
    "显著增加翻滚及受身的耐力消耗":"Significantly increase the stamina cost of dodging",
    "显著增加翻滚的无敌时间":"Significantly increase dodge invincible time",
    "显著增强防御时可抵御的攻击强度":"Significantly increase amount of attack you can guard against",
    "显著提升体力上限":"Significantly increase amount of Health",
    "显著提升攻击力":"Significantly increase Attack",
    "显著提升防御力":"Significantly increase Defense",
    "显著降低会心几率":"Significantly reduce Critical Chance",
    "显著降低体力上限":"Significantly reduce amount of Health",
    "显著降低攻击力":"Significantly reduce Attack",
    "显著降低防御力":"Significantly reduce Defense",
    "暑热效果无效":"Negates Heat effects",
    "更容易对怪物造成部位破坏":"More likely to damage breakable parts of a monster",
    "更容易成为怪物的目标":"Increase chance of being targeted by monster",
    "极大增加会心几率":"Greatly increase Critical Chance",
    "极大提升体力上限":"Greatly increase amount of Health",
    "极大提升攻击力":"Greatly increase Attack",
    "极大提升防御力":"Greatly increase Defense",
    "每次死亡后攻击力和防御力都得到一定的提升（最多提升2次）":"After each death, attack and defense improved slightly (Stacks twice)",
    "气绝状态的时间减半":"Stun time halved",
    "气绝状态的时间延长":"Stun time extended",
    "水属性攻击伤害大幅提升":"Dramatically increase Water Attack",
    "水属性攻击伤害显著提升":"Significantly increase Water Attack",
    "水属性攻击伤害略微提升":"Slightly increase Water Attack",
    "水属性攻击的伤害衰减":"Reduce Ice Attack",
    "水属性攻击的伤害衰减":"Reduce Water Attack",
    "水属性耐性大幅提升":"Dramatically increase Water Res",
    "水属性耐性显著提升":"Significantly increase Water Res",
    "水属性耐性略微提升":"Slightly increase Water Res",
    "水属性耐性衰减":"Reduce Water Res",
    "火属性攻击伤害大幅提升":"Dramatically increase Fire Attack",
    "火属性攻击伤害显著提升":"Significantly increase Fire Attack",
    "火属性攻击伤害略微提升":"Slightly increase Fire Attack",
    "火属性攻击的伤害衰减":"Reduce Fire Attack",
    "火属性耐性大幅提升":"Dramatically increase Fire Res",
    "火属性耐性显著提升":"Significantly increase Fire Res",
    "火属性耐性略微提升":"Slightly increase Fire Res",
    "火属性耐性衰减":"Reduce Fire Res",
    "炮击伤害小幅增加，龙击炮CD时间小幅缩减":"Shelling damage increased slightly, Wyvern Fire Cooldown reduced",
    "炮击伤害略微增加，龙击炮CD时间略微缩减":"Shelling damage increased slightly, Wyvern Fire Cooldown slightly reduced",
    "狩猎笛旋律效果持续时间变长":"Hunting Horn Melody effects last for a longer time",
    "略微减少翻滚及受身的耐力消耗":"Slightly reduce the stamina cost of dodging",
    "略微增加会心几率":"Slightly increase Critical Chance",
    "略微增加翻滚及受身的耐力消耗":"Slightly increase the stamina cost of dodging",
    "略微提升体力上限":"Slightly increase amount of Health",
    "略微提升攻击力":"Slightly increase Attack",
    "略微提升防御力":"Slightly increase Defense",
    "略微降低会心几率":"Slightly reduce Critical Chance",
    "略微降低体力上限":"Slightly reduce amount of Health",
    "略微降低攻击力":"Slightly reduce Attack",
    "略微降低防御力":"Slightly reduce Defense",
    "耐力上限值不会减少":"Stamina bar will not decrease",
    "耐力上限的自然下降速度变快":"Stamina bar decreases faster",
    "耐力上限的自然下降速度变慢":"Stamina bar will decrease slower",
    "耐力消耗增加":"Increase consumption cost of Stamina",
    "耐力消耗显著降低":"Significantly reduce consumption cost of Stamina",
    "耐力消耗降低":"Reduce consumption cost of Stamina",
    "能够使砥石进行磨刀的速度达到极速":"Greatly increases speed of whetstone sharpening",
    "能够大幅加快使用砥石进行磨刀的速度":"Significantly increases speed of whetstone sharpening",
    "能够抵抗不可防御招式":"Causes previously unblockable attacks to become blockable",
    "自动烤肉":"Auto Barbecue",
    "较大概率受到的伤害值明显增加":"Greater chance that when recieving damage it gets significantly increased",
    "较大概率受到的伤害值明显降低":"Greater chance that when recieving damage it gets significantly reduced",
    "进入毒状态的时间延长":"Poison time extended",
    "进入睡眠状态的时间延长":"Sleep time extended",
    "采集时50%几率多采一次":"When collecting there is an 50% chance of recieving more items",
    "采集时80%几率多采一次":"When collecting there is an 80% chance of recieving more items",
    "锤横扫重击、片手剑盾二连击、大剑拍击和防御拍击、弩炮近身攻击命中怪物头部将产生\n锁气绝效果，短时内让怪物气绝值停止恢复。":"Hammer blow, Sword and Shield Bash, Greatsword Slap, and Ranged head hits will lock up the monster. The monster will recover in a short amount of time",
    "降低使用砥石进行磨刀的速度":"Reduces the speed of whetstone sharpening",
    "降低耐力回复速度":"Reduce Stamina recovery speed",
    "雷属性攻击伤害大幅提升":"Dramatically increase Thunder Attack",
    "雷属性攻击伤害显著提升":"Significantly increase Thunder Attack",
    "雷属性攻击伤害略微提升":"Slightly increase Thunder Attack",
    "雷属性攻击的伤害衰减":"Reduce Thunder Attack",
    "雷属性耐性大幅提升":"Dramatically increase Thunder Res",
    "雷属性耐性显著提升":"Significantly increase Thunder Res",
    "雷属性耐性略微提升":"Slightly increase Thunder Res",
    "雷属性耐性衰减":"Reduce Thunder Res",
    "非怪物仇恨目标时额外增加伤害，但对怪物的仇恨变高":"Increases damage to monsters not targeting you, but they will become more likely to target you",
    "食用草药就可以恢复大量体力":"Edible herbs can recover a large amount of health",
    "食用速度减慢":"Slow down the speed of eating",
    "食用速度加快":"Eating sped up",
    "麻痹状态的时间增长":"Paralysis time extended",
    "龙属性攻击伤害大幅提升":"Dramatically increase Dragon Attack",
    "龙属性攻击伤害显著提升":"Significantly increase Dragon Attack",
    "龙属性攻击伤害略微提升":"Slightly increase Dragon Attack",
    "龙属性攻击的伤害衰减":"Reduce Dragon Attack",
    "龙属性耐性大幅提升":"Dramatically increase Dragon Res",
    "龙属性耐性显著提升":"Significantly increase Dragon Res",
    "龙属性耐性略微提升":"Slightly increase Dragon Res",
    "龙属性耐性衰减":"Reduce Dragon Res",

    "真晓风":"True Dawnwind",

    "NB5":"<a href='/monsters/merphistophelin/' target='_blank'>Merphistophelin</a>",
    "NBX":"<a href='/monsters/slicemargl/' target='_blank'>Slicemargl</a>",
    "NBY":"<a href='/monsters/lightenna/' target='_blank'>Lightenna</a>",
    "PVP2":"<a href='/monsters/merphistophelin/' target='_blank'>Merphistophelin</a>",
    "一角龙":"<a href='/monsters/monoblos/' target='_blank'>Monoblos</a>",
    "冰雷鸟":"<a href='/monsters/ice-chramine/' target='_blank'>Ice Chramine</a>",
    "初阶吞渊龙":"<a href='/monsters/tartaronis/' target='_blank'>Tartaronis</a>",
    "剑刹狼":"<a href='/monsters/purple-slicemargl/' target='_blank'>Purple Slicemargl</a>",
    "剑极狼":"<a href='/monsters/slicemargl/' target='_blank'>Slicemargl</a>",
    "剑极狼亚种":"<a href='/monsters/purple-slicemargl/' target='_blank'>Purple Slicemargl</a>",
    "剑豪镰蟹":"<a href='/monsters/swordmaster-shogun-ceanataur/' target='_blank'>Swordmaster Shogun Ceanataur</a>",
    "吞渊龙":"<a href='/monsters/tartaronis/' target='_blank'>Tartaronis</a>",
    "大名盾蟹":"<a href='/monsters/daimyo-hermitaur/' target='_blank'>Daimyo Hermitaur</a>",
    "大怪鸟":"<a href='/monsters/yian-kut-ku/' target='_blank'>Yian Kut-Ku</a>",
    "大野猪王":"<a href='/monsters/bulldrome/' target='_blank'>Bulldrome</a>",
    "将军镰蟹":"<a href='/monsters/shogun-ceanataur/' target='_blank'>Shogun Ceanataur</a>",
    "尾晶蝎":"<a href='/monsters/akura-vashimu/' target='_blank'>Akura Vashimu</a>",
    "岩龙":"<a href='/monsters/basarios/' target='_blank'>Basarios</a>",
    "战鬼河狸兽":"<a href='/monsters/ghost-caeserber/' target='_blank'>Ghost Caeserber</a>",
    "断刃一角龙":"<a href='/monsters/shattered-monoblos/' target='_blank'>Shattered Monoblos</a>",
    "断角一角龙":"<a href='/monsters/shattered-monoblos/' target='_blank'>Shattered Monoblos</a>",
    "星龙":"<a href='/monsters/estrellian/' target='_blank'>Estrellian</a>",
    "晶岩龙":"<a href='/monsters/crystal-basarios/' target='_blank'>Crystal Basarios</a>",
    "桃毛兽王":"<a href='/monsters/congalala/' target='_blank'>Congalala</a>",
    "樱火龙":"<a href='/monsters/pink-rathian/' target='_blank'>Pink Rathian</a>",
    "毒怪鸟":"<a href='/monsters/gypceros/' target='_blank'>Gypceros</a>",
    "水龙":"<a href='/monsters/plesioth/' target='_blank'>Plesioth</a>",
    "沙狸兽":"<a href='/monsters/yellow-caeserber/' target='_blank'>Yellow Caeserber</a>",
    "沙雷鸟":"<a href='/monsters/chramine/' target='_blank'>Chramine</a>",
    "沙龙王":"<a href='/monsters/cephadrome/' target='_blank'>Cephadrome</a>",
    "河狸兽":"<a href='/monsters/caeserber/' target='_blank'>Caeserber</a>",
    "灰晶蝎":"<a href='/monsters/akura-jebia/' target='_blank'>Akura Jebia</a>",
    "炎狮子":"<a href='/monsters/flame-blangonga/' target='_blank'>Flame Blangonga</a>",
    "烈焰女王":"<a href='/monsters/conflagration-rathian/' target='_blank'>Conflagration Rathian</a>",
    "烈焰雌火龙":"<a href='/monsters/conflagration-rathian/' target='_blank'>Conflagration Rathian</a>",
    "熔岩龙":"<a href='/monsters/lavasioth/' target='_blank'>Lavasioth</a>",
    "片耳黑狼鸟":"<a href='/monsters/one-eared-yian-garuga/' target='_blank'>One-Eared Yian Garuga</a>",
    "独耳黑狼鸟":"<a href='/monsters/one-eared-yian-garuga/' target='_blank'>One-Eared Yian Garuga</a>",
    "电甲虫":"<a href='/monsters/lightenna/' target='_blank'>Lightenna</a>",
    "电龙":"<a href='/monsters/khezu/' target='_blank'>Khezu</a>",
    "白一角龙":"<a href='/monsters/white-monoblos/' target='_blank'>White Monoblos</a>",
    "白速龙王":"<a href='/monsters/giadrome/' target='_blank'>Giadrome</a>",
    "盾蟹":"<a href='/monsters/daimyo-hermitaur/' target='_blank'>Hermitaur</a>",
    "眠鸟":"<a href='/monsters/hypnocatrice/' target='_blank'>Hypnocatrice</a>",
    "砂岩龙":"<a href='/monsters/sandstone-basarios/' target='_blank'>Sandstone Basarios</a>",
    "砦蟹":"<a href='/monsters/shen-gaoren/' target='_blank'>Shen Gaoren</a>",
    "祸星龙":"<a href='/monsters/doom-estrellian/' target='_blank'>Doom Estrellian</a>",
    "紫毒鸟":"<a href='/monsters/purple-gypceros/' target='_blank'>Purple Gypceros</a>",
    "红电龙":"<a href='/monsters/red-khezu/' target='_blank'>Red Khezu</a>",
    "红莲砦蟹":"<a href='/monsters/guren-shen-gaoren/' target='_blank'>Guren Shen Gaoren</a>",
    "红莲砦蟹,铠岩砦蟹":"<a href='/monsters/guren-shen-gaoren/' target='_blank'>Guren Shen Gaoren</a>, <a href='/monsters/tepekki-shen-gaoren/' target='_blank'>Tepekki Shen Gaoren</a>",
    "红莲砦蟹，铠岩砦蟹":"<a href='/monsters/guren-shen-gaoren/' target='_blank'>Guren Shen Gaoren</a>, <a href='/monsters/tepekki-shen-gaoren/' target='_blank'>Tepekki Shen Gaoren</a>",
    "红速龙王":"<a href='/monsters/iodrome/' target='_blank'>Iodrome</a>",
    "老山蟹":"<a href='/monsters/shen-gaoren/' target='_blank'>Shen Gaoren</a>",
    "老山蟹B":"<a href='/monsters/guren-shen-gaoren/' target='_blank'>Guren Shen Gaoren</a>",
    "苍火龙":"<a href='/monsters/azure-rathalos/' target='_blank'>Azure Rathalos</a>",
    "荒厄龙":"<a href='/monsters/merphistophelin/' target='_blank'>Merphistophelin</a>",
    "蓝速龙王":"<a href='/monsters/velocidrome/' target='_blank'>Velocidrome</a>",
    "角龙":"<a href='/monsters/diablos/' target='_blank'>Diablos</a>",
    "轰龙":"<a href='/monsters/tigrex/' target='_blank'>Tigrex</a>",
    "金毛兽王":"<a href='/monsters/gold-congalala/' target='_blank'>Gold Congalala</a>",
    "金狮子":"<a href='/monsters/rajang/' target='_blank'>Rajang</a>",
    "金眠鸟":"<a href='/monsters/gold-hypnocatrice/' target='_blank'>Gold Hypnocatrice</a>",
    "钢龙":"<a href='/monsters/kushala-daora/' target='_blank'>Kushala Daora</a>",
    "铠岩砦蟹":"<a href='/monsters/tepekki-shen-gaoren/' target='_blank'>Tepekki Shen Gaoren</a>",
    "铠龙":"<a href='/monsters/gravios/' target='_blank'>Gravios</a>",
    "银眠鸟":"<a href='/monsters/silver-hypnocatrice/' target='_blank'>Silver Hypnocatrice</a>",
    "镰蟹":"<a href='/monsters/shogun-ceanataur/' target='_blank'>Ceanataur</a>",
    "雄火龙":"<a href='/monsters/rathalos/' target='_blank'>Rathalos</a>",
    "雄火龙，苍火龙":"<a href='/monsters/rathalos/' target='_blank'>Rathalos</a>, <a href='/monsters/azure-rathalos/' target='_blank'>Azure Rathalos</a>",
    "雌火龙":"<a href='/monsters/rathian/' target='_blank'>Rathian</a>",
    "雪狮子王":"<a href='/monsters/blangonga/' target='_blank'>Blangonga</a>",
    "霞龙":"<a href='/monsters/chameleos/' target='_blank'>Chameleos</a>",
    "青怪鸟":"<a href='/monsters/blue-yian-kut-ku/' target='_blank'>Blue Yian Kut-Ku</a>",
    "骇狩蛛":"<a href='/monsters/dread-baelidae/' target='_blank'>Dread Baelidae</a>",
    "鬼狩蛛":"<a href='/monsters/baelidae/' target='_blank'>Baelidae</a>",
    "黄速龙王":"<a href='/monsters/gendrome/' target='_blank'>Gendrome</a>",
    "黑狼鸟":"<a href='/monsters/yian-garuga/' target='_blank'>Yian Garuga</a>",

    "hali":"Congalala",
    "kurimu":"Gendrome",
    "subaku":"Bulldrome + Congalala",
    "sunaku":"Congalala + Velocidrome",
    "十字枪":"Rocks",
    "新手":"Velociprey",
    "爬虫":"Bones",
    "特殊枪":"Gendrome + Bulldrome",
    "特殊笛":"Baelidae + Yian Kut-Ku",
    "特殊铳枪":"Yian Kut-Ku + Bulldrome",
    "鄂":"Congalala + Gendrome",
    "野性":"Congalala",
    "铁":"Rocks",
    "骨":"Bones",

    "nl一角龙":"Monoblos",
    "nl冰雷鸟":"Ice Chramine",
    "nl剑刹狼":"Purple Slicemargl",
    "nl剑极狼":"Slicemargl",
    "nl剑极狼亚种":"Purple Slicemargl",
    "nl剑豪镰蟹":"Swordmaster Shogun Ceanataur",
    "nl吞渊龙":"Tartaronis",
    "nl大名盾蟹":"Daimyo Hermitaur",
    "nl大怪鸟":"Yian Kut-Ku",
    "nl大野猪王":"Bulldrome",
    "nl将军镰蟹":"Shogun Ceanataur",
    "nl尾晶蝎":"Akura Vashimu",
    "nl岩龙":"Basarios",
    "nl战鬼河狸兽":"Ghost Caeserber",
    "nl断刃一角龙":"Shattered Monoblos",
    "nl星龙":"Estrellian",
    "nl晶岩龙":"Crystal Basarios",
    "nl桃毛兽王":"Congalala",
    "nl樱火龙":"Pink Rathian",
    "nl毒怪鸟":"Gypceros",
    "nl水龙":"Plesioth",
    "nl沙狸兽":"Yellow Caeserber",
    "nl沙雷鸟":"Chramine",
    "nl沙龙王":"Cephadrome",
    "nl河狸兽":"Caeserber",
    "nl灰晶蝎":"Akura Jebia",
    "nl炎狮子":"Flame Blangonga",
    "nl烈焰女王":"Conflagration Rathian",
    "nl熔岩龙":"Lavasioth",
    "nl独耳黑狼鸟":"One-Eared Yian Garuga",
    "nl电甲虫":"Lightenna",
    "nl电龙":"Khezu",
    "nl白一角龙":"White Monoblos",
    "nl白速龙王":"Giadrome",
    "nl盾蟹":"Hermitaur",
    "nl眠鸟":"Hypnocatrice",
    "nl砂岩龙":"Sandstone Basarios",
    "nl砦蟹":"Shen Gaoren",
    "nl祸星龙":"Doom Estrellian",
    "nl紫毒鸟":"Purple Gypceros",
    "nl红电龙":"Red Khezu",
    "nl红莲砦蟹":"Guren Shen Gaoren",
    "nl红莲砦蟹，铠岩砦蟹":"Tepekki Shen Gaoren",
    "nl红速龙王":"Iodrome",
    "nl苍火龙":"Azure Rathalos",
    "nl荒厄龙":"Merphistophelin",
    "nl蓝速龙王":"Velocidrome",
    "nl角龙":"Diablos",
    "nl轰龙":"Tigrex",
    "nl金毛兽王":"Gold Congalala",
    "nl金狮子":"Rajang",
    "nl金眠鸟":"Gold Hypnocatrice",
    "nl钢龙":"Kushala Daora",
    "nl铠岩砦蟹":"Tepekki Shen Gaoren",
    "nl铠龙":"Gravios",
    "nl银眠鸟":"Silver Hypnocatrice",
    "nl镰蟹":"Ceanataur",
    "nl雄火龙":"Rathalos",
    "nl雄火龙，苍火龙":"Azure Rathalos",
    "nl雌火龙":"Rathian",
    "nl雪狮子王":"Blangonga",
    "nl霞龙":"Chameleos",
    "nl青怪鸟":"Blue Yian Kut-Ku",
    "nl骇狩蛛":"Dread Baelidae",
    "nl鬼狩蛛":"Baelidae",
    "nl黄速龙王":"Gendrome",
    "nl黑狼鸟":"Yian Garuga",

    "右手":"Right Hand",
    "右手（钳）":"Right Hand (Pincer)",
    "右翼":"Right Wing",
    "右脚":"Right Foot",
    "右腿":"Right Leg",
    "壳":"Shell",
    "头部":"Head",
    "尾巴":"Tail",
    "尾部":"Tail",
    "尾部（尻尾）":"Tail (Rump)",
    "左,右手（钳）":"Left and Right Hand (Pincers)",
    "左,右翼":"Wings",
    "左/右翼":"Wings",
    "左/右臂":"Arms",
    "左右手（钳）":"Left and Right Hands (Pincers)",
    "左右翼":"Wings",
    "左手":"Left Hand",
    "左翼":"Left Wing",
    "左脚":"Left Foot",
    "左腿":"Left Leg",
    "翼膜":"Wing Membrane",
    "背部":"Back",
    "腹部":"Abdomen",
    "角":"Horn",
    "躯干":"Torso",
    "躯干（本体/胴体）":"Torso (Body/Carcass)",
    "面部":"Face",
    "颈部":"Neck",

    "50级以上古龙征伐":"Lvl 50 Large Monster Conquests",
    "50级以上王立委托、王立精英委托":"Lvl 50 Large Monster Conquests, HR Elite Hunting",
    "大型怪物狩猎":"Large Monster Hunting",
    "大型怪物狩猎、50级以上王立委托、王立精英委托":"Large Monster Hunting, Lvl 50 Large Monster Conquests, HR Elite Hunting",
    "大型怪物狩猎挑战难度、王立委托、王立精英委托":"Large Monster Hunting Difficult Challenge, HR Hunting, HR Elite Hunting",
    "大型怪物狩猎挑战难度，王立委托，王立精英委托":"Large Monster Hunting Difficult Challenge, HR Hunting, HR Elite Hunting",
    "大湖围猎祭":"Great Lakes Hunting Festival",
    "活动":"Raid",
    "王立委托":"HR Hunting",
    "王立委托、王立精英、极限":"HR Hunting, HR Elite, Limit Mode",
    "王立委托、王立精英委托":"HR Hunting, HR Elite Hunting",
    "王立委托，王立精英委托":"HR Hunting, HR Elite Hunting",
    "王立委托，王立精英，极限":"HR Hunting, HR Elite, Limit Mode",
    "王立精英委托":"HR Elite Hunting",

    "KO术、上弹速度强化+1、挑衅":"KO King，Reload Spd +1，Taunt",
    "KO术、散弹/矢强化、挑衅":"KO King，Pellet/Spread Up，Taunt",
    "KO术、砥石使用高速化、挑衅":"KO King，Speed Sharpening，Taunt",
    "KO术，集中，看破+1，耐力回复-1":"Knockout King，Concentrate，See Through +1，Stam Recov -1",
    "上弹速度强化+1、攻击力提升（小）、状态异常攻击-1":"Reload Spd +1，Attack Up (S)，Status Atk Down",
    "上弹速度强化+1，气绝减半，回避性能+1，耐暑":"Reload Spd +1，Halve Stun，Evasion +1，Heat Cancel",
    "上弹速度强化+1，贯通弹/矢强化，耐力回复+1，状态异常攻击-1":"Reload Spd +1，Pierce/Pierce Up，Stam Recov +1，Status Atk Down",
    "不屈、根性、回复速度+1、耐力回复迟缓-1":"Fortify，Guts，Rec Speed +1，Stam Recov -1",
    "不屈，特殊攻击+2，广域化+1":"Fortify，Status Atk +2，Wide-Range +1",
    "业物、砥石使用高速化、体力弱化-2":"Sharp，Speed Sharpening，Health -2",
    "业物、见切+1、防御力降低（小）":"Sharp，Critical Eye +1，Defense Down (S)",
    "业物，气绝减半，回避性能+1，耐暑":"Sharp，Halve Stun，Evasion +1，Heat Cancel",
    "体力强化+1、攻击力提升（小）":"Health +1，Attack Up (S)",
    "体术+1、冰属性攻击强化+2、刺杀术+1、毒倍化":"Constitution +1，Ice Itk +2，Assassin Tech +1，Double Poison",
    "体术+1、弱点特效、挑衅":"Constitution +1，Weakness Exploit，Taunt",
    "体术+2，睡眠免疫，鸟龙杀手，防御力降低（小）":"Constitution +2，Negate Sleep，Bird Dragons Killer，Defense Down (S)",
    "冰属性攻击强化+1、耐寒、耐震、气绝倍化":"Ice Itk +1，Cold Res，Tremor Res，Double Stun",
    "刺杀术+1、火属性攻击强化+2、防御力降低（小）":"Assassin Tech +1，Fire Atk +2，Defense Down (S)",
    "化蝶、隐秘、见切-1":"Butterfly Form，Sneak，Critical Eye -1",
    "回复速度+1、观察眼、大胃王":"Rec Speed +1，Capture Guru，Gourmand",
    "回复速度+2、业物、挑战者+2、刺伤无效、降低耐力回复速度-1":"Rec Speed +2，Sharp，Challenger+2，Negate Thorns，Stam Recov -1",
    "回复速度+2、业物、挑战者+2、刺伤无效、降低耐力回复速度-6":"Rec Speed +2，Sharp，Challenger+2，Negate Thorns，Stam Recov -1",
    "回复速度+3、气绝倍化":"Rec Speed +3，Double Stun",
    "回复速度+3、雷属性攻击强化+1、气绝倍化":"Rec Speed +3，Thunder Atk +1，Double Stun",
    "回避性能+2，集中，毒倍化":"Evasion +2，Concentrate，Double Poison",
    "广域化+1、耐力急速回复+1、回复速度-1":"Wide-Range +1，Stam Recov +1，Rec Speed -1",
    "弱点特效、回复速度+1、火属性攻击强化+1、上弹速度强化-1":"Weakness Exploit，Rec Speed +1，Fire Atk +1，Reload Spd -1",
    "心眼、回复速度+1、火属性攻击强化+1、钝刀":"Mind's Eye，Rec Speed +1，Fire Atk +1，Blunt Edge",
    "心眼、火属性攻击强化+2、防御力降低（小）":"Mind's Eye，Fire Atk +2，Defense Down (S)",
    "快速装填+2，散弹/矢强化，体力强化+3，体术-1":"Reload Spd +2，Pellet/Spread Up，Health +3，Constitution -1",
    "抗菌、速食、看破+1、饥饿感增加":"Anti-bacterial，Speed Eating，See Through +1，Raise Hunger",
    "抗菌、速食、饥饿感增加":"Anti-bacterial，Speed Eating，Raise Hunger",
    "拔刀术，耐震，耐力回复+1，砥石使用低速化":"Critical Draw，Tremor Res，Stam Recov +1，Slow Sharpening",
    "挑战者、火事场力+1、恶灵加持":"Challenger，Adrenaline +1，Evil Blessing",
    "探知、速食":"Detect，Speed Eating",
    "攻击力提升（大）、火属性攻击强化+1、体力弱化-1":"Attack Up (L)，Fire Atk +1，Health -1",
    "攻击力提升（小）、火属性耐性强化+1":"Attack Up (S)，Fire Res +1",
    "散弹/矢强化、速食、耐泥雪、攻击力降低（小）":"Pellet/Spread Up，Speed Eating，Mud/Snow，Attack Down (S)",
    "毒减半、体力强化+2、探知":"Halve Poison，Health +2，Detect",
    "毒减半、体力强化+2、气绝倍化":"Halve Poison，Health +2，Double Stun",
    "毒减半、雷属性耐性强化+1":"Halve Poison，Thunder Atk +1",
    "毒减半、麻痹免疫、睡眠倍化":"Halve Poison，Negate Paralysis，Double Sleep",
    "毒无效、雷属性耐性强化+1、饥饿感增加":"Negate Poison，Thunder Atk +1，Raise Hunger",
    "毒无效、麻痹免疫、状态异常攻击+1、睡眠倍化":"Negate Poison，Negate Paralysis，Status Atk +1，Double Sleep",
    "气绝免疫、风压（小）无效、恶灵加持":"Negate Stun，Windproof (Lo)，Evil Blessing",
    "气绝免疫、风压（小）无效、耐力急速回复+1、恶灵加持":"Negate Stun，Windproof (Lo)，Stam Recov +1，Evil Blessing",
    "气绝减半、草药达人":"Halve Stun，Herbal Daren",
    "火事场力+1、破坏王、抗菌、防御力降低（小）":"Adrenaline +1，Partbreaker，Anti-bacterial，Defense Down (S)",
    "火事场力+1、破坏王、防御力降低（小）":"Adrenaline +1，Partbreaker，Defense Down (S)",
    "火事场力+1、绊术、速食、回复速度-1":"Adrenaline +1，Tripping Power，Speed Eating，Rec Speed -1",
    "火事场力+2，见切+1，恶灵的加护":"Adrenaline +2，Critical Eye +1，Evil Blessing",
    "火事场力+2，风压（大）无效，火属性攻击强化+1":"Adrenaline +2，Windproof (Hi)，Fire Atk +1",
    "特殊攻击+2，麻痹免疫，反动减轻+1，上弹速度强化-1":"Status Atk +2，Negate Paralysis，Recoil Down +1，Reload Spd -1",
    "特殊攻击+2，麻痹免疫，心眼，钝刀":"Status Atk +2，Negate Paralysis，Mind's Eye，Blunt Edge",
    "睡眠免疫、上弹速度强化+1、麻痹倍化":"Negate Sleep，Reload Spd +1，Double Paralysis",
    "睡眠免疫、体术+1、吸引、耐力回复迟缓-1":"Negate Sleep，Constitution +1，Attract，Stam Recov -1",
    "睡眠免疫、吸引、状态异常攻击+1、火属性耐性弱化":"Negate Sleep，Attract，Status Atk +1，Fire Res Down",
    "睡眠免疫、吸引、耐力回复迟缓-1":"Negate Sleep，Attract，Stam Recov -1",
    "睡眠免疫、防御等级+1、麻痹倍化":"Negate Sleep，Guard +1，Double Paralysis",
    "砥石使用高速化、冰属性攻击强化+1、心眼、毒倍化":"Speed Sharpening，Ice Itk +1，Mind's Eye，Double Poison",
    "砥石使用高速化、防御力提升（小）":"Speed Sharpening，Defense Up (S)",
    "破坏王，耐震，弱点特效，耐力回复-1":"Partbreaker，Tremor Res，Weakness Exploit，Stam Recov -1",
    "耐暑、暴击":"Heat Cancel，Violent Strike",
    "耐泥雪、探知、冰属性耐性强化+1、火属性耐性弱化":"Mud/Snow，Detect，Ice Res +1，Fire Res Down",
    "耐泥雪、耐寒、冰属性攻击强化+1、气绝倍化":"Mud/Snow，Cold Res，Ice Itk +1，Double Stun",
    "耐泥雪、陷阱师":"Mud/Snow，Trap Master",
    "耐泥雪、陷阱师、回复速度+1":"Mud/Snow，Trap Master，Rec Speed +1",
    "耐震、根性、水属性攻击强化+1、慢食":"Tremor Res，Guts，Water Atk +1，Slow Eater",
    "耳栓、状态异常攻击+1、反动减轻+1、回复速度-1":"Earplugs，Status Atk +1，Recoil Down +1，Rec Speed -1",
    "耳栓、状态异常攻击+1、砥石使用高速化、回复速度-1":"Earplugs，Status Atk +1，Speed Sharpening，Rec Speed -1",
    "耳栓、速食、防御力提升（小）、反动增大":"Earplugs，Speed Eating，Defense Up (S)，Recoil Up",
    "耳栓、速食、防御力提升（小）、砥石使用低速化":"Earplugs，Speed Eating，Defense Up (S)，Slow Sharpening",
    "耳栓，甲壳杀手，回复速度+1，体力弱化-1":"Earplugs，Crustaceans Killer，Rec Speed +1，Health -1",
    "耳栓，隐秘，风压（大）无效，耐力回复-1":"Earplugs，Sneak，Windproof (Hi)，Stam Recov -1",
    "见切+1、火属性攻击强化+1、体力弱化-1":"Critical Eye +1，Fire Atk +1，Health -1",
    "见切+1、状态异常攻击+1、火属性攻击强化+1、体力弱化-1":"Critical Eye +1，Status Atk +1，Fire Atk +1，Health -1",
    "见切+2、暴击、气绝倍化":"Critical Eye +2，Violent Strike，Double Stun",
    "见切+2，耳栓，业物，体力弱化-1":"Critical Eye +2，Earplugs，Sharp，Health -1",
    "见切+2，耳栓，通常弹&连射矢强化，体力弱化-1":"Critical Eye +2，Earplugs，Normal/Rapid Up，Health -1",
    "贯通弹/矢强化、上弹速度强化+1、体力弱化-2":"Pierce/Pierce Up，Reload Spd +1，Health -2",
    "贯通弹/矢强化、见切+1、防御力降低（小）":"Pierce/Pierce Up，Critical Eye +1，Defense Down (S)",
    "通常弹&连射矢强化 、防御力提升（小）":"Normal/Rapid Up ，Defense Up (S)",
    "通常弹&连射矢强化、防御力提升（小）":"Normal/Rapid Up，Defense Up (S)",
    "防御力提升（小）、风压（小）无效、雷属性攻击弱化":"Defense Up (S)，Windproof (Lo)，Thunder Atk Down",
    "防御强化、速食、耐泥雪、攻击力降低（小）":"Guard Boost，Speed Eating，Mud/Snow，Attack Down (S)",
    "防御性能+2，防御强化，体力强化+3，体术-1":"Guard +2，Guard Boost，Health +3，Constitution -1",
    "防御等级+1、攻击力提升（小）、状态异常攻击-1":"Guard +1，Attack Up (S)，Status Atk Down",
    "集中、破坏王、体力弱化-2":"Concentrate，Partbreaker，Health -2",
    "集中，根性，火属性攻击强化+1，水属性耐性弱化，":"Concentrate，Guts，Fire Atk +1，Water Res Down",
    "雷属性攻击强化+1，回避性能，精灵的守护，上弹速度强化-1":"Thunder Atk +1，Evasion，Holy Blessing，Reload Spd -1",
    "雷属性攻击强化+1，回避性能，精灵的守护，砥石使用低速化":"Thunder Atk +1，Evasion，Holy Blessing，Slow Sharpening",
    "风压（大）无效、无伤、耐力回复迟缓-1":"Windproof (Hi)，Peak Performance，Stam Recov -1",
    "风压（小）无效、无伤":"Windproof (Lo)，Peak Performance",
    "麻痹免疫、状态异常攻击+1":"Negate Paralysis，Status Atk +1",

    "一角龙的刚翼":"Monoblos Firm Wing+",
    "一角龙的坚壳":"Monoblos Hard Shell+",
    "一角龙的坚甲":"Monoblos Frim Armor+",
    "一角龙的尾巴":"Monoblos Tail",
    "一角龙的延髓":"Monoblos Medulla Oblongata+",
    "一角龙的心脏":"Monoblos Heart",
    "一角龙的甲壳":"Monoblos Hard Shell",
    "一角龙的翼":"Monoblos Wing",
    "一角龙的背甲":"Monoblos Carapace",
    "一角龙的血液":"Monoblos Blood",
    "一角龙的靭尾":"Monoblos Tough Tail+",
    "一角龙的骨髓":"Monoblos Marrow",
    "七色的尾羽":"Rainbow Feather",
    "不新鲜的蘑菇":"Stale Mushroom",
    "不明的体液":"Bright Fluid",
    "不死虫":"Dead Bugs",
    "丑陋的臼齿":"Ugly Molars",
    "业炎的秘宝":"Flaming Jewel",
    "亮绿色的粘液":"Bright Green Mucus+",
    "亮蓝色的粘液":"Bright Blue Mucus",
    "亮黄的毛":"Bright Yellow Hair",
    "仙人掌花":"Cactus Flower",
    "优质的毛皮":"Warm Pelt+",
    "低压的电气袋":"Electro Sac",
    "修罗原珠":"Repair Gem",
    "储沙囊":"Sand Bag",
    "光水晶":"Lightcrystal",
    "光虫":"Light Bug",
    "兽骨【中】":"Brute Bone M",
    "兽骨【大】":"Brute Bone L",
    "兽骨【小】":"Brute Bone S",
    "冰冷的头骨":"Ice Cold Skull",
    "冰冷的爪子":"Ice Cold Paw",
    "冰结晶":"Ice Crystal",
    "冰雪覆盖的厚毛皮":"Snow Covered Thick Pelt",
    "冰雪覆盖的毛皮":"Snow Covered Pelt",
    "冰雷爆裂袋":"Ice-Ray Burst Bag",
    "冰雷鸟的优质皮":"I.Chramine Hide+",
    "冰雷鸟的冻翼":"I.Chramine Frozen Wing+",
    "冰雷鸟的刚翼":"I.Chramine Wing+",
    "冰雷鸟的厚实嗉囊":"I.Chramine Crop+",
    "冰雷鸟的嗦囊":"I.Chramine Wind Bag",
    "冰雷鸟的惨白鼻":"I.Chramine Pale Nose+",
    "冰雷鸟的极寒嗉囊":"I.Chramine Arctic Crop+",
    "冰雷鸟的特上皮":"I.Chramine Special Epithelial+",
    "冰雷鸟的白鼻":"I.Chramine White Nose",
    "冰雷鸟的皮":"I.Chramine Skin",
    "冰雷鸟的翼":"I.Chramine Wings",
    "冰雷鸟的臼齿":"I.Chramine Molars",
    "冰雷鸟的苍白鼻":"I.Chramine Pale Beak",
    "剑刹狼的修罗眼":"P.Slicemargl Eye",
    "剑刹狼的刚爪":"P.Slicemargl Steel Claw",
    "剑刹狼的剑棘":"P.Slicemargl Sword Spine",
    "剑刹狼的豪刚毛":"P.Slicemargl Bristle",
    "剑刹狼的重牙":"P.Slicemargl Heavy Fang",
    "剑刹狼的重腕甲":"P.Slicemargl Heavy Wristguards",
    "剑刹狼的重骨刃":"P.Slicemargl Heavy Blade Bone",
    "剑刹狼的长獠齿":"P.Slicemargl Hunting Fang",
    "剑刹狼的靭尾鬃":"P.Slicemargl Tough Tail Bristle",
    "剑极狼的上背棘":"Slicemargl Dorsal Spine",
    "剑极狼的上腕甲":"Slicemargl Wristguard",
    "剑极狼的凶戾眼":"Slicemargl Brutal Eye",
    "剑极狼的刚毛":"Slicemargl Bristle",
    "剑极狼的刚爪":"Slicemargl Sharp Claw+",
    "剑极狼的剑棘":"Slicemargl Dorsal Spine+",
    "剑极狼的劲尾鬃":"Slicemargl Tail Bristle",
    "剑极狼的尖爪":"Slicemargl Sharp Claw",
    "剑极狼的残暴眼":"Slicemargl Brutal Eye+",
    "剑极狼的獠齿":"Slicemargl Hunting Fang",
    "剑极狼的硬骨刃":"Slicemargl Hard Blade Bone",
    "剑极狼的豪刚毛":"Slicemargl Black Hair+",
    "剑极狼的重牙":"Slicemargl Sharp Fang+",
    "剑极狼的重腕甲":"Slicemargl Wristguard+",
    "剑极狼的重骨刃":"Slicemargl Hard Blade Bone+",
    "剑极狼的锐牙":"Slicemargl Sharp Fang",
    "剑极狼的长獠齿":"Slicemargl Hunting Fang+",
    "剑极狼的靭尾鬃":"Slicemargl Tail Bristle+",
    "剑极狼的黑毛":"Slicemargl Black Hair",
    "剑豪之刃镰":"Swordmaster Sickle Blade",
    "剑豪之将军角":"Swordmaster General Horn",
    "剑豪之锋镰":"S.Shogun Ceanataur Sickle",
    "剑豪的坚龙头壳":"Swordmaster Wyvern Skull",
    "剑豪的重龙头壳":"Swordmaster Wyvern Skull",
    "剑豪镰蟹的储水袋":"S.Shogun Ceanataur Water Bag",
    "剑豪镰蟹的刚爪":"S.Shogun Ceanataur Sharp Claw+",
    "剑豪镰蟹的刚钳":"S.Shogun Ceanataur Clamp+",
    "剑豪镰蟹的坚壳":"S.Shogun Ceanataur Shell",
    "剑豪镰蟹的坚脚":"S.Shogun Ceanataur Leg",
    "剑豪镰蟹的坚钳":"S.Shogun Ceanataur Clamp",
    "剑豪镰蟹的尖爪":"S.Shogun Ceanataur Sharp Claw",
    "剑豪镰蟹的重壳":"S.Shogun Ceanataur Shell+",
    "剑豪镰蟹的重脚":"S.Shogun Ceanataur Leg+",
    "剑豪镰蟹的金色大真珠":"S.Shogun Ceanataur Large Gold Pearl",
    "华丽的青鸟喙":"Blue Kut-Ku Beak+",
    "历战的门牙":"Worn Incisor+",
    "厚实的储沙囊":"Thick Sand Bag",
    "厚实的毒舌":"Thick Tongue",
    "厚实的紫毒舌":"Thick Purple Tongue",
    "厚重的晶石壳":"Heavy Spar Shell",
    "厚重的石壳":"Heavy Stone Shell",
    "原盘石":"Disk Stone",
    "发黄的臭牙":"Smelly Yellow Teeth",
    "变异的光水晶":"Weird Lightcrystal",
    "变异的新星水晶":"Weird Novacrystal+",
    "变质的体液":"Metamorphism Fluid",
    "古龙之燃血":"Dragon Elder Blood",
    "古龙之血":"Ancient Blood",
    "吞渊龙的优质背鳍":"Tartaronis Fin+",
    "吞渊龙的坚尾甲":"Tartaronis Tail+",    
    "吞渊龙的坚岩壳":"Tartaronis Rock Shell+",
    "吞渊龙的坚腕甲":"Tartaronis Wristguards+",
    "吞渊龙的坚骨甲":"Tartaronis Bone Plate+",
    "吞渊龙的大颚":"Tartaronis Jaw+",
    "吞渊龙的尾甲":"Tartaronis Tail",
    "吞渊龙的岩壳":"Tartaronis Rock Shell",
    "吞渊龙的背鳍":"Tartaronis Fin",
    "吞渊龙的腕甲":"Tartaronis Wristguards",
    "吞渊龙的颚":"Tartaronis Jaw",
    "吞渊龙的骨板甲":"Tartaronis Bone Plate",
    "圆盘石":"Disk Stone",
    "圆蚂蚱":"Round Grasshopper",
    "圆鼓鼓的眠袋":"Bulging Sleep Sac",
    "土蜂幼虫":"Earth Bee Larvae",
    "坚固的紫头壳":"Complete Purple Head+",
    "坚硬的沙鳞":"Hard Sand Scale",
    "坚龙头壳":"Wyvern Skull+",
    "多彩的尾羽":"Colorful Feather+",
    "多彩色之毛":"Colourful Hair",
    "大地结晶":"Earth Crystal",
    "大桶":"Vat",
    "大野猪王尖獠牙":"Bulldrome Pointed Fangs",
    "大野猪王的卷曲牙":"Bulldrome Curved Fang",
    "大野猪王的尖牙":"Bulldrome Tusk+",
    "大野猪王的曲刚牙":"Bulldrome Curved Fang+",
    "大野猪王的牙":"Bulldrome Tusk",
    "大野猪王的硬蹄":"Bulldrome Hoof+",
    "大野猪王的硬鬃":"Bulldrome Bristle+",
    "大野猪王的蹄":"Bulldrome Hoof",
    "大野猪王的鬃":"Bulldrome Bristle",
    "大野猪的皮":"Bullfango Hide",
    "大野猪的硬皮":"Bullfango Hide+",
    "妖光的体液":"Cold Light Fluid+",
    "妖光的浓液":"Devil Fluid",
    "妖艳的星光":"Glamorous Starlight",
    "完好的骨甲":"Intact Bone",
    "完整的大块紫胶皮":"Complete Purple Rubber Chunk",
    "完整的大块胶皮":"Rubber Chunks",
    "完整的眠袋":"Sleep Sac+",
    "完整的紫头壳":"Complete Purple Head",
    "完整的鸣袋":"Intact Sound Bag",
    "寒光的体液":"Cold Light Fluid",
    "将军之角":"General Horn",
    "小桶":"Keg",
    "小石子":"Stone",
    "尾晶蝎的刚毛":"A.Vashimu Hair+",
    "尾晶蝎的刚爪":"A.Vashimu Steel Claw",
    "尾晶蝎的刚钳":"A.Vashimu Steel Clamp",
    "尾晶蝎的坚壳":"A.Vashimu Shell+",
    "尾晶蝎的大颚":"A.Vashimu Jaw+",
    "尾晶蝎的尖爪":"A.Vashimu Claw+",
    "尾晶蝎的尾巴":"A.Vashimu Tail",
    "尾晶蝎的巨钳":"A.Vashimu Clamp+",
    "尾晶蝎的晶石":"A.Vashimu Amethyst",
    "尾晶蝎的毒刚毛":"A.Vashimu Poison Hair+",
    "尾晶蝎的毒毛":"A.Vashimu Poisen Hair",
    "尾晶蝎的毒豪毛":"A.Vashimu Grand Poisen Hair",
    "尾晶蝎的毛":"A.Vashimu Hair",
    "尾晶蝎的爪":"A.Vashimu Claw",
    "尾晶蝎的甲壳":"A.Vashimu Shell",
    "尾晶蝎的紫晶":"A.Vashimu Amethyst+",
    "尾晶蝎的纯紫晶":"A.Vashimu Pure Amethyst",
    "尾晶蝎的绝尾":"A.Vashimu Absolute Tail",
    "尾晶蝎的豪毛":"A.Vashimu Grand Hair",
    "尾晶蝎的重壳":"A.Vashimu Heavy Shell",
    "尾晶蝎的重颚":"A.Vashimu Heavy Jaw",
    "尾晶蝎的钳":"A.Vashimu Clamp",
    "尾晶蝎的靭尾":"A.Vashimu Tail+",
    "尾晶蝎的颚":"A.Vashimu Jaw",
    "山青虫":"Mountain Budworm",
    "岩龙的优质翼":"Basarios Wing+",
    "岩龙的坚壳":"Basarios Armor+",
    "岩龙的坚头壳":"Basarios Skull+",
    "岩龙的坚背壳":"Basarios Shell+",
    "岩龙的坚腹甲":"Basarios Breastplate+",
    "岩龙的头壳":"Basarios Skull",
    "岩龙的尾巴":"Basarios Tail",
    "岩龙的晶泪":"Basarios Tear+",
    "岩龙的泪":"Basarios Tear",
    "岩龙的甲壳":"Basarios Shell",
    "岩龙的翼":"Basarios Wing",
    "岩龙的背壳":"Basarios Carapace",
    "岩龙的腹甲":"Basarios Breastplate",
    "岩龙的苔背甲":"Basarios Carapace",
    "岩龙的靭尾":"Basarios Tough Tail+",
    "巨大冰雷鸟嘴":"I.Chramine Huge Mouth",
    "巨大的喙":"Huge Beak+",
    "巨大的青鸟喙":"Blue Kut-Ku Beak",
    "常春藤叶":"Ivy Leaves",
    "异味的腺体":"Peculiar Smell Gland",
    "弯月之头冠":"Cephadrome Head",
    "强光的电气袋":"Thunder Sac+",
    "强走精华":"Sprinter Essence",
    "强韧的脚蹼":"Tough Webbed Feet",
    "微光的体液":"Shimmering Body Fluid",
    "微光的电气袋":"Shimmering Electric Bag",
    "忍耐果实":"Bear Fruit",
    "怪力果实":"Power Fruit",
    "怪物粪便":"Dung",
    "怪鸟的优质鳞":"Kut-Ku Scale+",
    "怪鸟的刚爪":"Kut-Ku Steel Talons+",
    "怪鸟的刚翼":"Kut-Ku Wing+",
    "怪鸟的地狱耳":"Kut-Ku Ear+",
    "怪鸟的坚背甲":"Kut-Ku Carapace+",
    "怪鸟的尖爪":"Kut-Ku Claw+",
    "怪鸟的尾巴":"Yian Kut-Ku Tail",
    "怪鸟的爪":"Kut-Ku Claw",
    "怪鸟的福耳":"Blessed Kut-Ku Ear+",
    "怪鸟的翼":"Kut-Ku Wing",
    "怪鸟的翼爪":"Yian Kut-Ku Wing Claw",
    "怪鸟的耳":"Kut-Ku Ear",
    "怪鸟的背甲":"Kut-Ku Shell",
    "怪鸟的重背甲":"Kut-Ku Heavy Carapace+",
    "怪鸟的重鳞":"Kut-Ku Heavy Scales+",
    "怪鸟的靭翼":"Kut-Ku Tough Wing+",
    "怪鸟的鳞":"Kut-Ku Scale",
    "恶臭的粪便":"Smelly Feces",
    "恶臭的腺体":"Stench Gland",
    "战鬼之眼":"G.Caeserber Eye",
    "战鬼之血":"Ghost Blood",
    "战鬼凶眼":"Evil Ghost Eye",
    "战鬼河狸兽坚硬皮":"G.Caeserber Hard Hide",
    "战鬼河狸兽尖爪":"G.Caeserber Sharp Claws",
    "战鬼河狸兽的优质皮":"G.Caeserber Hide+",
    "战鬼河狸兽的刚爪":"G.Caeserber Steel Claw",
    "战鬼河狸兽的利爪":"G.Caeserber Claw+",
    "战鬼河狸兽的厚毛":"G.Caeserber Thick Hair",
    "战鬼河狸兽的坚尾甲":"G.Caeserber Tail+",
    "战鬼河狸兽的坚牙":"G.Caeserber Fang+",
    "战鬼河狸兽的尾甲":"G.Caeserber Tail Armor",
    "战鬼河狸兽的爪":"G.Caeserber Claws",
    "战鬼河狸兽的牙":"G.Caeserber Teeth",
    "战鬼河狸兽的皮":"G.Caeserber Skin",
    "战鬼河狸兽的重尾甲":"G.Caeserber Heavy Tail",
    "战鬼河狸兽的重牙":"G.Caeserber Heavy Fang",
    "折断的巨角":"Giant Fracture Horn",
    "摇曳的星光":"Flickering Starlight",
    "断刃一角龙的刚翼":"S.Monoblos Wing+",
    "断刃一角龙的坚壳":"S.Monoblos Hard Shell+",
    "断刃一角龙的坚甲":"S.Monoblos Carapace+",
    "断刃一角龙的延髓":"S.Monoblos Medulla",
    "断刃一角龙的脉动心脏":"S.Monoblos Pulsating Heart",
    "断刃一角龙的血液":"S.Monoblos Horn Blood",
    "断刃一角龙的靭尾":"S.Monoblos Tough Tail+",
    "断流之爪":"Dried Claw",
    "断流利爪":"Dried Claw+",
    "断流绝爪":"Absolute Dried Claw",
    "新月之头冠":"Cephadrome Head+",
    "新鲜的体液":"Fresh Fluid",
    "星之龙鳞":"Star Scale",
    "星光的体液":"Starlight Fluid",
    "星羽蝶的体液":"Feathered Butterfly Fluid",
    "星羽蝶的妖羽":"Demon Butterfly Wing",
    "星羽蝶的妖角":"Demon Butterfly Horn",
    "星羽蝶的斩妖羽":"Demon Butterfly Cut Wing",
    "星羽蝶的甲壳":"Feathered Butterfly Shell",
    "星羽蝶的羽翅":"Feathered Butterfly Wing",
    "星羽蝶的薄妖羽":"Demon Butterfly Wing+",
    "星羽蝶的薄羽翅":"Feathered Butterfly Wing+",
    "星羽蝶的虫腹":"Feathered Butterfly Abdomen",
    "星羽蝶的角":"Feathered Butterfly Horn",
    "星龙的坚壳":"Estrellian Shell+",
    "星龙的坚腹甲":"Estrellian Breastplate+",
    "星龙的尖爪":"Estrellian Claw+",
    "星龙的尖角":"Estrellian Horn+",
    "星龙的尾巴":"Estrellian Tail",
    "星龙的爪":"Estrellian Claw",
    "星龙的甲壳":"Estrellian Shell",
    "星龙的腹甲":"Estrellian Breastplate",
    "星龙的角":"Estrellian Horn",
    "星龙的韧尾":"Estrellian Tail+",
    "晶岩之泪":"C.Basarios Tears",
    "晶岩龙的刚翼":"C.Basarios Firm Wing+",
    "晶岩龙的坚头壳":"C.Basarios Firm Skull+",
    "晶岩龙的坚甲":"C.Basarios Firm Armor+",
    "晶岩龙的坚背壳":"C.Basarios Hard Back Shell+",
    "晶岩龙的坚腹甲":"C.Basarios Firm Breastplate+",
    "晶岩龙的头壳":"C.Basarios Skull",
    "晶岩龙的尾巴":"C.Basarios Tail",
    "晶岩龙的甲壳":"C.Basarios Hard Shell",
    "晶岩龙的翼":"C.Basarios Wing",
    "晶岩龙的背壳":"C.Basarios Carapace",
    "晶岩龙的腹甲":"C.Basarios Breastplate",
    "晶岩龙的苔背甲":"C.Basarios Rear Armor",
    "晶岩龙的靭尾":"C.Basarios Tough Tail+",
    "晶莹的眠液":"Crystal Clear Sleep Solution",
    "曼陀罗花":"Datura Flower",
    "杀人蜂幼虫":"Snakebee Larvae",
    "松动的矿石":"Loose Ore",
    "极上金真珠":"Polished Gold Pearl",
    "极品金色大真珠":"High Quality Large Gold Pearl",
    "极彩色的毛":"Extreme Colored Hair",
    "极炼蟹糕":"Refined Crab Cream",
    "极电浓汁":"Electric Gravy",
    "极电精华":"Electric Essence",
    "染色果":"Staining Fruit",
    "柔软的皮":"Pearly Hide",
    "桃毛兽王优质头冠":"Congalala Crown+",
    "桃毛兽王的优质皮":"Congalala Hide+",
    "桃毛兽王的坚骨":"Congalala Strong Bone",
    "桃毛兽王的大骨":"Congalala Large Bone",
    "桃毛兽王的头冠":"Congalala Crown",
    "桃毛兽王的尖爪":"Congalala Claw+",
    "桃毛兽王的尖牙":"Congalala Fang+",
    "桃毛兽王的爪":"Congalala Claw",
    "桃毛兽王的牙":"Congalala Fang",
    "桃毛兽王的皮":"Congalala Hide",
    "桃毛兽的刚毛":"Conga Hair+",
    "桃毛兽的毛":"Conga Hair",
    "桃色的优质鳞":"Pink Quality Scale",
    "桃色的鳞":"Pink Scale",
    "梅杰波尔坦黄玉":"Mezeporta Topaz",
    "棒状之骨":"Bone",
    "樱火龙的上棘":"P.Rathian Webbing+",
    "樱火龙的上鳞":"P.Rathian Scale+",
    "樱火龙的坚壳":"P.Rathian Shell+",
    "樱火龙的延髓":"P.Rathian Marrow+",
    "樱火龙的逆鳞":"P.Rathian Spike+",
    "樱红的爆炎袋":"P.Rathian Inferno Sac",
    "橙色的绒毛":"Orange Hair",
    "橡胶质的尾巴":"Gypceros Tail",
    "橡胶质的紫柔皮":"P.Rubbery Hide+",
    "橡胶质的紫皮":"P.Rubbery Hide",
    "橡胶质的绿尾":"P.Gypceros Tail",
    "橡胶质的绿韧尾":"P.Gypceros Tail+",
    "橡胶质的韧尾":"Gypceros Tail+",
    "毒怪鸟的优质皮":"Gypceros Hide+",
    "毒怪鸟的刚翼":"Gypceros Wing+",
    "毒怪鸟的嘴":"Gypceros Beak",
    "毒怪鸟的坚硬嘴":"Gypceros Beak+",
    "毒怪鸟的坚硬头":"Gypceros Head+",
    "毒怪鸟的头":"Gypceros Head",
    "毒怪鸟的皮":"Gypceros Hide",
    "毒怪鸟的翼":"Gypceros Wing",
    "毒蘑菇":"Poisonous Mushroom",
    "毒鸟的紫刚翼":"P.Gypceros Wing+",
    "毒鸟的紫坚硬头":"P.Gypceros Head+",
    "毒鸟的紫头":"P.Gypceros Head",
    "毒鸟的紫翼":"P.Gypceros Wing",
    "水光原珠":"Water Gem",
    "水龙的上鳍":"Plesioth Fin",
    "水龙的上鳞":"Plesioth Scale",
    "水龙的坚头壳":"Plesioth Head",
    "水龙的翼膜":"Plesioth Membrane",
    "水龙的锐牙":"Plesioth Sharp Fang",
    "沙化的骨甲":"Sandy Bone",
    "沙渊的龙玉":"Jade Sandstone",
    "沙渊的龙神玉":"Deep Jade Sandstone",
    "沙狸兽之皮":"Y.Caeserber Hide",
    "沙狸兽的刚腕":"Y.Caeserber Iron Wrist+",
    "沙狸兽的坚尾甲":"Y.Caeserber Tail+",
    "沙狸兽的坚爪":"Y.Caeserber Claw+",
    "沙狸兽的尖牙":"Y.Caeserber Fang+",
    "沙狸兽的尖门牙":"Y.Caeserber Incisor+",
    "沙狸兽的尾甲":"Y.Caeserber Tail",
    "沙狸兽的爪":"Y.Caeserber Claw",
    "沙狸兽的牙":"Y.Caeserber Fang",
    "沙狸兽的铁腕":"Y.Caeserber Iron Wrist",
    "沙狸兽的门牙":"Y.Caeserber Incisor",
    "沙狸兽重皮":"Y.Caeserber Hide+",
    "沙雷鸟的优质皮":"Chramine Hide+",
    "沙雷鸟的刚翼":"Chramine Wing+",
    "沙雷鸟的厚实嗉囊":"Chramine Crop+",
    "沙雷鸟的嗉囊":"Chramine Crop",
    "沙雷鸟的皮":"Chramine Hide",
    "沙雷鸟的红鼻":"Chramine Red Beak",
    "沙雷鸟的翼":"Chramine Wing",
    "沙雷鸟的臼齿":"Chramine Molars",
    "沙雷鸟的赤红鼻":"Chramine Crimson Beak+",
    "沙龙王琼脂":"Cephadrome Fat",
    "沙龙王的优质皮":"Cephadrome Hide+",
    "沙龙王的优质背鳍":"Cephadrome Quality Dorsal Fin",
    "沙龙王的储砂袋":"Cephadrome Sand Sac",
    "沙龙王的大储砂袋":"Cephadrome Sand Sac+",
    "沙龙王的尖牙":"Cephadrome Fang+",
    "沙龙王的牙":"Cephadrome Fang",
    "沙龙王的皮":"Cephadrome Hide",
    "沙龙王的背鳍":"Cephadrome Dorsal Fin",
    "沙龙王的鱼尾":"Cephadrome Tail",
    "沙龙王硬背鳍":"Cephadrome Hard Dorsal Fin",
    "沙龙的优质鳞":"Cephalos Scale+",
    "沙龙的鳞":"Cephalos Scale",
    "河狸兽的优质皮":"Caeserber Hide+",
    "河狸兽的尖爪":"Caeserber Claw+",
    "河狸兽的尖牙":"Caeserber Fang+",
    "河狸兽的尾甲":"Caeserber Tail",
    "河狸兽的爪":"Caeserber Claw",
    "河狸兽的牙":"Caeserber Fang",
    "河狸兽的皮":"Caeserber Hide",
    "沸腾的龙血":"Boiling Dragon Blood",
    "泌酸腺":"Acid Gland",
    "浑浊的眠液":"Turbid Sleep Solution",
    "浑浊的龙血":"Muddy Dragon Blood",
    "浓缩的眠液":"Concentrated Sleep Solution+",
    "淡彩色的毛":"Bright Hair",
    "淡金色的毛":"Pale Gold Hair",
    "深紫头壳":"Deep Purple Head",
    "深紫色的毒液":"Purple Venom",
    "深蓝的刚鬃":"Firm Blue Bristles+",
    "混沌核心":"Chaos Heart",
    "混沌的龙血":"Chaos Dragon Blood",
    "温暖的毛皮":"Warm Pelt",
    "湛蓝的刚鬃":"Blue Mane+",
    "漂亮的喙":"Beautiful Beak+",
    "漆黑大珍珠":"Black Pearl+",
    "漆黑的趾甲":"Dark Nails",
    "潮湿的毛皮":"Wet Fur",
    "火红的鬃毛":"Red Mane",
    "火药草":"Gunpowder Grass",
    "火龙体液":"Rathalos Body Fluid",
    "火龙坚壳":"Rathalos Hard Shell",
    "火龙的上鳞":"Rathalos Scales",
    "火龙的优质鳞":"Rathalos Quality Scales+",
    "火龙的刚翼":"Rathalos Firm Wing+",
    "火龙的坚壳":"Rathalos Hard Shell+",
    "火龙的延髓":"Rathalos Medulla Oblongata+",
    "火龙的红玉":"Rathalos Ruby+",
    "火龙的逆鳞":"Rathalos Inverse Scale+",
    "火龙的锐翼爪":"Rathalos Sharp Wing Claw",
    "火龙的韧尾":"Rathalos Tough Tail+",
    "火龙的韧翼膜":"Rathalos Blade Patagium+",
    "火龙翼膜":"Rathalos Patagium",
    "灰晶蝎的刚毛":"A.Jebia Bristle",
    "灰晶蝎的刚爪":"A.Jebia Sharp Claw+",
    "灰晶蝎的刚钳":"A.Jebia Giant Clamp+",
    "灰晶蝎的坚壳":"A.Jebia Shell",
    "灰晶蝎的大颚":"A.Jebia Giant Jaw",
    "灰晶蝎的尖爪":"A.Jebia Sharp Claw",
    "灰晶蝎的巨钳":"A.Jebia Giant Clamp",
    "灰晶蝎的星辉石":"A.Jebia Bright Star Stone",
    "灰晶蝎的毒刚毛":"A.Jebia Poisen Bristle",
    "灰晶蝎的毒豪毛":"A.Jebia Poisen Bristle+",
    "灰晶蝎的绝尾":"A.Jebia Tough Tail+",
    "灰晶蝎的豪毛":"A.Jebia Bristle+",
    "灰晶蝎的辉晶石":"A.Jebia Bright Crystal Stone",
    "灰晶蝎的重壳":"A.Jebia Shell+",
    "灰晶蝎的重颚":"A.Jebia Giant Jaw+",
    "灰晶蝎的靭尾":"A.Jebia Tough Tail",
    "灾厄的宝珠":"Disaster Orb",
    "灾星的厚龙鳞":"Thick Bane Scale",
    "灾星龙鳞":"Bane Scale",
    "灾祸的龙血":"Evil Dragon Blood",
    "炎狮子的上头冠":"F.Blangonga Crown",
    "炎狮子的刚毛":"F.Blangonga Bristle",
    "炎狮子的刚爪":"F.Blangonga Sharp Claw+",
    "炎狮子的刚髭":"F.Blangonga Mustache",
    "炎狮子的坚长骨":"F.Blangonga Long Bone",
    "炎狮子的尖爪":"F.Blangonga Sharp Claw",
    "炎狮子的尖牙":"F.Blangonga Sharp Fang",
    "炎狮子的强韧髭":"F.Blangonga Mustache+",
    "炎狮子的豪刚毛":"F.Blangonga Bristle+",
    "炎狮子的豪头冠":"F.Blangonga Crown+",
    "炎狮子的豪尾":"F.Blangonga Tough Tail+",
    "炎狮子的重牙":"F.Blangonga Heavy Fang+",
    "炎狮子的重骨":"F.Blangonga Heavy Bone",
    "炎狮子的靭尾":"F.Blangonga Tough Tail",
    "炮钢砂":"Steel Grit",
    "炮铁砂":"Sand Ore",
    "炸药":"Dynamite",
    "炽热的折断真红之角":"Really Red Broken Horn",
    "炽热的火焰袋":"Hot Flame Bag+",
    "炽热的真红之角":"Firm Red Hot Horn",
    "烈焰的优质棘":"C.Rathian Quality Spine+",
    "烈焰的优质龙鳞":"C.Rathian Quality Scale+",
    "烈焰的刚翼":"C.Rathian Firm Wings+",
    "烈焰的刚龙爪":"C.Rathian Firm Claw+",
    "烈焰的坚壳":"C.Rathian Firm Hard Armor Shell+",
    "烈焰的延髓":"C.Rathian Medulla Oblongata+",
    "烈焰的毒液":"C.Rathian Venom",
    "烈焰的甲壳":"C.Rathian Armor Shell",
    "烈焰的秘棘":"C.Rathian Secret Spine+",
    "烈焰的翼膜":"C.Rathian Patagium",
    "烈焰的靭尾":"C.Rathian Tough Tail+",
    "烈焰的骨髓":"C.Rathian Marrow",
    "烈焰的龙尾":"C.Rathian Tail",
    "烈焰的龙棘":"C.Rathian Spine",
    "烈焰的龙爪":"C.Rathian Claw",
    "烈焰的龙翼":"C.Rathian Wings",
    "烈焰的龙鳞":"C.Rathian Scale",
    "烈焰红玉":"C.Rathian Ruby",
    "烈焰红玉":"C.Rathian Ruby+",
    "熔岩块":"Lava Rock",
    "熔岩龙的上鳍":"Lavasioth Fin",
    "熔岩龙的上鳞":"Lavasioth Scale",
    "熔岩龙的厚鳞":"Lavasioth Thick Scale",
    "熔岩龙的坚壳":"Lavasioth Hard Shell",
    "熔岩龙的坚头壳":"Lavasioth Head",
    "熔岩龙的尾鳍":"Lavasioth Dorsal Fin",
    "熔岩龙的特上鳍":"Lavasioth Special Fin",
    "熔岩龙的重壳":"Lavasioth Heavy Shell",
    "熔岩龙的重头壳":"Lavasioth Heavy Head",
    "熔岩龙的重尾鳍":"Lavasioth Heavy Tail Fin",
    "熔岩龙的重牙":"Lavasioth Heavy Fang",
    "熔岩龙的锐牙":"Lavasioth Sharp Fang",
    "燕雀石":"Machalite Ore",
    "爆炎袋":"Fire Bomb Bag",
    "爆裂核桃":"Burst Walnut",
    "独耳黑狼鸟的优质鳞":"One-Eared Garuga Scale+",
    "独耳黑狼鸟的刚翼":"One-Eared Garuga Wing+",
    "独耳黑狼鸟的刚翼爪":"One-Eared Garuga Claw+",
    "独耳黑狼鸟的刚髭":"One-Eared Garuga Mustache+",
    "独耳黑狼鸟的喙":"One-Eared Garuga Beak+",
    "独耳黑狼鸟的地狱耳":"One-Eared Garuga Hell Ear+",
    "独耳黑狼鸟的坚壳":"One-Eared Garuga Shell+",
    "独耳黑狼鸟的坚背甲":"One-Eared Garuga Firm Tail Armor+",
    "独耳黑狼鸟的尖喙":"One-Eared Garuga Sharp Beak+",
    "独耳黑狼鸟的尾":"One-Eared Garuga Tail",
    "独耳黑狼鸟的甲壳":"One-Eared Garuga Shell",
    "独耳黑狼鸟的翼":"One-Eared Garuga Wing+",
    "独耳黑狼鸟的翼爪":"One-Eared Garuga Claw",
    "独耳黑狼鸟的翼膜":"One-Eared Garuga Wing Membrane+",
    "独耳黑狼鸟的耳":"One-Eared Garuga Ear",
    "独耳黑狼鸟的背甲":"One-Eared Garuga Tail Armor+",
    "独耳黑狼鸟的靭尾":"One-Eared Garuga Tough Tail+",
    "独耳黑狼鸟的韧翼膜":"One-Eared Garuga Edge Webbing",
    "独耳黑狼鸟的髭":"One-Eared Garuga Mustache",
    "独耳黑狼鸟的鳞":"One-Eared Garuga Scale",
    "独耳黒狼鸟的毒棘":"One-Eared Garuga Poisonous Spines",
    "独耳黒紫色的小鳞":"One-Eared Garuga Small Scale",
    "狱岩块":"Lava Block",
    "猩红之眼":"Scarlet Eye",
    "猩红的臭牙":"Smelly Scarlet Teeth",
    "珍珠色的柔皮":"Pearly Hide+",
    "珍珠色的环状嘴":"Pearl Mouth",
    "珍珠色的翼膜":"Pearly Patagium",
    "珍珠色的脚趾":"Pearl-colored Toes",
    "琉璃原珠":"Glass Gem",
    "生命之粉":"Life Powder",
    "电甲虫的刚尾须":"Lightenna Cercus+",
    "电甲虫的刚角":"Lightenna Cusp+",
    "电甲虫的坚壳":"Lightenna Shell",
    "电甲虫的坚尾须":"Lightenna Cercus",
    "电甲虫的大颚":"Lightenna Jaw",
    "电甲虫的尖角":"Lightenna Cusp",
    "电甲虫的斩羽":"Lightenna Feather+",
    "电甲虫的极电角":"Lightenna Horn",
    "电甲虫的薄羽":"Lightenna Feather",
    "电甲虫的超极电角":"Lightenna Horn+",
    "电甲虫的重壳":"Lightenna Shell+",
    "电甲虫的重颚":"Lightenna Jaw+",
    "电龙的优质翼":"Khezu Patagium+",
    "电龙的吸盘":"Khezu Sucker",
    "电龙的尖牙":"Khezu Fang+",
    "电龙的强力吸盘":"Khezu Sucker+",
    "电龙的牙":"Khezu Fang",
    "电龙的翼":"Khezu Wing",
    "白一角龙的心脏":"White Monoblos Heart+",
    "白一角龙的绝尾":"White Monoblos Tail+",
    "白化精华":"Albino Essence",
    "白化里脊肉":"Pale Steak",
    "白化霜降肉":"Pearly Frosted Meat+",
    "白色宝石颗粒":"White Gem Pieces",
    "白色的鸟龙皮":"White Bird Wyvern Skin",
    "白速龙王的优质皮":"Giadrome Hide+",
    "白速龙王的冰结腺":"Giadrome Venom",
    "白速龙王的冻结腺":"Giadrome Frozen Gland",
    "白速龙王的大头冠":"Giadrome Large Crown+",
    "白速龙王的头冠":"Giadrome Crown",
    "白速龙王的尖爪":"Giadrome Claw+",
    "白速龙王的尖牙":"Giadrome Fang+",
    "白速龙王的尾巴":"Giadrome Tail",
    "白速龙王的爪":"Giadrome Claws",
    "白速龙王的牙":"Giadrome Teeth",
    "白速龙王的皮":"Giadrome Hide",
    "白速龙的优质鳞":"Giaprey Scale+",
    "白速龙的鳞":"Giadrome Scales",
    "白银尾羽":"Silver Tail",
    "盾蟹断脚":"Daimyo Hermitaur Broken Legs",
    "盾蟹的储水袋":"Hermitaur Water Bag",
    "盾蟹的坚壳":"Daimyo Hermitaur Shell+",
    "盾蟹的小坚壳":"Small Hermitaur Shell+",
    "盾蟹的小壳":"Small Hermitaur Shell",
    "盾蟹的尖爪":"Daimyo Hermitaur Claw+",
    "盾蟹的巨钳":"Daimyo Hermitaur Clamp+",
    "盾蟹的爪":"Daimyo Hermitaur Claw",
    "盾蟹的甲壳":"Daimyo Hermitaur Shell",
    "盾蟹的脚":"Daimyo Hermitaur Leg",
    "盾蟹的钳":"Daimyo Hermitaur Clamp",
    "盾蟹的长脚":"Daimyo Hermitaur Leg+",
    "盾蟹的鳃":"Hermitaur Gills",
    "真红之角":"True Red Horn",
    "真红刚角":"True Red Horn+",
    "眠鸟的喙":"Hypnocatrice Beak",
    "眠鸟的尖爪":"Hypnocatrice Sharp Claw+",
    "眠鸟的尾巴":"Hypnocatrice Tail",
    "眠鸟的橙羽毛":"Hypnocatrice Orange Feather+",
    "眠鸟的爪":"Hypnocatrice Claw",
    "眠鸟的牙喙":"Hypnocatrice Beak+",
    "眠鸟的稀胃石":"Rare Bezoar",
    "眠鸟的羽毛":"Hypnocatrice Feather",
    "眠鸟的翼羽":"Hypnocatrice Feathers",
    "眠鸟的胃石":"Hypnocatrice Gastrolith",
    "眠鸟重喙":"Hypnocatrice Long Beak",
    "睡眠草":"Sleep Grass",
    "短小的喙":"Short Beak",
    "石质的脚趾":"Stone Toes",
    "砂岩龙的优质翼":"S.Basarios Wing+",
    "砂岩龙的坚壳":"S.Basarios Shell+",
    "砂岩龙的坚头壳":"S.Basarios Skull+",
    "砂岩龙的坚背壳":"S.Basarios Armor+",
    "砂岩龙的坚腹甲":"S.Basarios Breastplate+",
    "砂岩龙的沙泪":"S.Basarios Tear+",
    "砦蟹之刚赤螯":"Shen Gaoren Red Pincers",
    "砦蟹之天壳":"Shen Gaoren Shell",
    "砦蟹之崩山铗":"Shen Gaoren Landslide Sword",
    "砦蟹之极上甲":"Shen Gaoren Polished Armor",
    "砦蟹之烈刃爪":"Shen Gaoren Strong Blade Claw",
    "砦蟹之裂岳爪":"Shen Gaoren Cracked Claw",
    "砦蟹之重甲":"Shen Gaoren Heavy Armor",
    "破损的喙":"Broken Beak",
    "破损的毒腺":"Damaged Venom",
    "破损的电气袋":"Damaged Electro Sac",
    "破损的眠袋":"Broken Sleep Sac",
    "破损的腺体":"Damaged Glands",
    "硝化蘑菇":"Nitro Mushroom",
    "硬化的脚蹼":"Hardened Webbed Feet",
    "磨损的门牙":"Worn Incisor",
    "神秘粉末":"Mysterious Powder",
    "祸之龙鳞":"Doom Scale",
    "祸星龙的刚翼":"D.Estrellian Breastplate+",
    "祸星龙的刚角":"D.Estrellian Evil Horn",
    "祸星龙的坚壳":"D.Estrellian Shell+",
    "祸星龙的尖爪":"D.Estrellian Claws+",
    "祸星龙的尖角":"D.Estrellian Horn+",
    "祸星龙的尾巴":"D.Estrellian Tail",
    "祸星龙的爪":"D.Estrellian Claw",
    "祸星龙的甲壳":"D.Estrellian Shell",
    "祸星龙的绝尾":"D.Estrellian Absolute Tail",
    "祸星龙的腹甲":"D.Estrellian Breastplate",
    "祸星龙的角":"D.Estrellian Horn",
    "祸星龙的重壳":"D.Estrellian Heavy Shell",
    "祸星龙的重爪":"D.Estrellian Heavy Claw",
    "祸星龙的靭尾":"D.Estrellian Tail+",
    "祸星龙的韧翼":"D.Estrellian Hard Breastplate",
    "秘银尾羽":"Silver Tail+",
    "稀释的眠液":"Diluted Sleep Solution",
    "空喵玉":"Purple Meow Jade",
    "空心果":"Hollow Fruit",
    "粉色宝石颗粒":"Pink Gem Pieces",
    "粗壮的大猪骨":"Sturdy Bulldrome Bone",
    "粗壮的鸟腿骨":"Stout Bird Leg",
    "粗糙的毛皮":"Rough Fur",
    "粗糙的翼膜":"Rough Patagium",
    "粗糙的胶皮":"Rough Rubber",
    "粘稠的毒液":"Viscous Venom",
    "素材玉":"Creation Sphere",
    "紫毒鸟的嘴":"P.Gypceros Beak",
    "紫毒鸟的坚硬嘴":"P.Gypceros Beak+",
    "红电击袋":"Red Shock Bag",
    "红电龙坚牙":"R.Khezu Firm Electric Tooth",
    "红电龙的刚翼":"R.Khezu Wing+",
    "红电龙的吸盘":"R.Khezu Electric Chuck",
    "红电龙的尖牙":"R.Khezu Fang+",
    "红电龙的强力吸盘":"R.Khezu Sucker+",
    "红电龙的牙":"R.Khezu Electric Tooth",
    "红电龙的翼":"R.Khezu Elecric Wing",
    "红色的体液":"Red Fluid",
    "红色的鸟龙皮":"Red Bird Wyvern Skin",
    "红色里脊肉":"Red Tenderloin",
    "红色霜降肉":"Red Frosted Meat",
    "红角蝶":"Red-Horned Butterfly",
    "红速龙王头冠":"Iodrome Crown",
    "红速龙王的优质皮":"Iodrome Hide+",
    "红速龙王的大头冠":"Iodrome Crown+",
    "红速龙王的尖爪":"Iodrome Claw+",
    "红速龙王的尖牙":"Iodrome Fang+",
    "红速龙王的尾巴":"Iodrome Tail",
    "红速龙王的毒腺":"Iodrome Venom",
    "红速龙王的牙":"Iodrome Teeth",
    "红速龙王的猛毒腺":"Iodrome Fierce Venom",
    "红速龙王的皮":"Iodrome Hide",
    "红速龙的优质鳞":"Iodrome Scale+",
    "红速龙的鳞":"Iodrome Scales",
    "纯晶之泪":"Pure Crystal Tears+",
    "纯蓝的粘液":"Chunlan Mucus+",
    "绿色宝石颗粒":"Green Gem Pieces",
    "绿色的粘液":"Green Mucus",
    "网":"Net",
    "翠绿之眼":"Green Eye",
    "翠绿色的胶皮":"Emerald Green Rubber",
    "肥沃的泥巴":"Fertile Mud",
    "肥美的猪肉":"Plump Pork",
    "肥美的蟹膏":"Crab Cream",
    "肥美的蟹黄":"Plump Crab",
    "脉动的心脏":"Pulsating Heart+",
    "腐朽的厚龙鳞":"Decay Scale+",
    "腐朽的龙鳞":"Decay Scale",
    "腐烂的蘑菇":"Rotten Mushroom",
    "艾露秘藏":"Allure Hoards",
    "苍火龙的上鳞":"A.Rathalos Scale+",
    "苍火龙的刚翼":"A.Rathalos Wing+",
    "苍火龙的坚壳":"A.Rathalos Shell+",
    "苍火龙的延髓":"A.Rathalos Medulla",
    "苍火龙的逆鳞":"A.Rathalos Plate+",
    "苍蓝的爆炎袋":"Pale Azure Flame Sac+",
    "苦虫":"Bitter Worms",
    "荒厄龙的凶眼":"Merphistrophelin Evil Eye",
    "荒厄龙的刀剑鳞":"Merphistrophelin Sword Claw",
    "荒厄龙的刚翼":"Merphistrophelin Bone Wing+",
    "荒厄龙的刚蛮爪":"Merphistrophelin Claw+",
    "荒厄龙的刚角":"Merphistrophelin Horn+",
    "荒厄龙的剑尾":"Merphistrophelin Tail",
    "荒厄龙的剑鳞":"Merphistrophelin Sword Scale",
    "荒厄龙的厚鳞":"Merphistrophelin Scale+",
    "荒厄龙的甲壳":"Merphistrophelin Carapace",
    "荒厄龙的眼":"Merphistrophelin Eye",
    "荒厄龙的绝剑尾":"Merphistrophelin Tail+",
    "荒厄龙的胸壳":"Merphistrophelin Thorax",
    "荒厄龙的蛮爪":"Merphistrophelin Claw",
    "荒厄龙的角":"Merphistrophelin Horn",
    "荒厄龙的重壳":"Merphistrophelin Shell+",
    "荒厄龙的重胸壳":"Merphistrophelin Thorax+",
    "荒厄龙的骨翼":"Merphistrophelin Bone Wing",
    "荒厄龙的鳞":"Merphistrophelin Scale",
    "萎缩的眠袋":"Atrophy Sleep Bag",
    "落阳草":"Sun Grass",
    "蓝湖石":"Blue Lake Stone",
    "蓝色宝石颗粒":"Blue Gem Pieces",
    "蓝色的粘液":"Blue Mucus",
    "蓝色的鬃毛":"Blue Mane",
    "蓝色的鸟龙皮":"Blue Bird Wyvern Skin",
    "蓝蘑菇":"Blue Mushroom",
    "蓝速龙之鳞":"Kut-Ku Blue Scales",
    "蓝速龙王的优质皮":"Velocidrome Hide+",
    "蓝速龙王的大头冠":"Velocidrome Head+",
    "蓝速龙王的头冠":"Velocidrome Head",
    "蓝速龙王的尖爪":"Velocidrome Claw+",
    "蓝速龙王的尖牙":"Velocidrome Fang+",
    "蓝速龙王的尾巴":"Velocidrome Tail",
    "蓝速龙王的爪":"Velocidrome Claw",
    "蓝速龙王的牙":"Velocidrome Fang",
    "蓝速龙王的皮":"Velocidrome Hide",
    "蓝速龙王的锐爪":"Velocidrome Sharp Claws",
    "蓝速龙的优质鳞":"Velociprey Scale+",
    "蓝速龙的鳞":"Velociprey Scale",
    "虾的大壳":"Large Shrimp Shell",
    "蜂蜜":"Honey",
    "蟹之壳":"Crab",
    "被消化的铁砂":"Digested Iron Ore",
    "解毒草":"Detox Grass",
    "诡异的光水晶":"Strange Lightcrystal",
    "诡异的新星水晶":"Strange Novacrystal+",
    "赤红的刚鬃":"Red Mane+",
    "赤红的小鳞":"Small Crimson Scale",
    "辉水晶":"Bright Crystal",
    "辉龙石":"Dragonite Ore",
    "迷之骨":"Mystery Bone",
    "野生辣椒":"Wild Pepper",
    "金喵玉":"Golden Meow Sphere",
    "金毛兽王优质头皮":"G.Congalala Quality Scalp",
    "金毛兽王的优质皮":"G.Congalala Hide+",
    "金毛兽王的刚毛":"G.Congalala Hair+",
    "金毛兽王的坚骨":"G.Congalala Strong Bone",
    "金毛兽王的大骨":"G.Congalala Large Bone",
    "金毛兽王的头冠":"G.Congalala Crown",
    "金毛兽王的尖爪":"G.Congalala Claw+",
    "金毛兽王的尖牙":"G.Congalala Fang+",
    "金毛兽王的毛":"G.Congalala Hair",
    "金毛兽王的爪":"G.Congalala Claw",
    "金毛兽王的牙":"G.Congalala Fang",
    "金毛兽王的皮":"G.Congalala Hide",
    "金真珠":"Gold Pearl",
    "金色的毛":"Golden Hair",
    "针果":"Needle Fruit",
    "钢之上龙鳞":"Steel Scale",
    "钢之厚龙鳞":"Steel Scale+",
    "钢龙的刚爪":"Daora Sharp Claw+",
    "钢龙的刚翼":"Daora Wing+",
    "钢龙的刚角":"Daora Horn+",
    "钢龙的坚壳":"Daora Shell",
    "钢龙的宝玉":"Daora Gem",
    "钢龙的尖爪":"Daora Sharp Claw",
    "钢龙的尖角":"Daora Horn",
    "钢龙的绝尾":"Daora Tail+",
    "钢龙的翼膜":"Daora Wing",
    "钢龙的逆厚鳞":"Daora Scale+",
    "钢龙的逆鳞":"Daora Scale",
    "钢龙的重壳":"Daora Shell+",
    "钢龙的靭尾":"Daora Tail",
    "铁矿石":"Iron Ore",
    "铃芽草":"Bell Wheatgrass",
    "铠玉":"Armor Sphere",
    "银喵玉":"Silver Meow Sphere",
    "银眠鸟的喙":"S.Hypnocatrice Beak",
    "银眠鸟的尖爪":"S.Hypnocatrice Claw+",
    "银眠鸟的尾巴":"S.Hypnocatrice Tail",
    "银眠鸟的爪":"S.Hypnocatrice Claws",
    "银眠鸟的牙喙":"S.Hypnocatrice Beak+",
    "银眠鸟的稀胃石":"Rare Silver Bezoar+",
    "银眠鸟的羽毛":"S.Hypnocatrice Feathers",
    "银眠鸟的胃石":"S.Hypnocatrice Gastrolith",
    "银眠鸟的银羽毛":"S.Hypnocatrice Feather+",
    "银色的绒毛":"Silver Hair",
    "锋利的镰":"Sharp Sickle",
    "锋利的长趾甲":"Sharp Long Fingernails",
    "镰蟹的储水袋":"Shogun Ceanataur Water Bag",
    "镰蟹的坚壳":"Ceanataur Shell+",
    "镰蟹的小坚壳":"Shogun Ceanataur Small Shell+",
    "镰蟹的小壳":"Shogun Ceanataur Small Shell",
    "镰蟹的尖爪":"Shogun Ceanataur Claw+",
    "镰蟹的巨钳":"Shogun Ceanataur Clamp+",
    "镰蟹的爪":"Shogun Ceanataur Claw",
    "镰蟹的甲壳":"Shogun Ceanataur Shell",
    "镰蟹的脚":"Shogun Ceanataur Leg",
    "镰蟹的钳":"Shogun Ceanataur Clamp",
    "镰蟹的长脚":"Shogun Ceanataur Leg+",
    "长满霉斑的骨头":"Mildew Covered Bones",
    "阳翔原珠":"Sun Gem",
    "降星之龙鳞":"Fallen Star Scale",
    "陷阱机关":"Trap Parts",
    "隐藏的宝藏":"Hidden Treasure",
    "雌火龙的刚翼":"Rathian Firm Wing+",
    "雌火龙的尾巴":"Rathian Tail",
    "雌火龙的翼":"Rathian Wing",
    "雌火龙的靭尾":"Rathian Tough Tail+",
    "雪狮子的优质皮":"Blangonga Hide+",
    "雪狮子的刚毛":"Blangonga Hair+",
    "雪狮子的刚髭":"Blangonga Mustache+",
    "雪狮子的坚骨":"Blangonga Strong Bone",
    "雪狮子的大骨":"Blangonga Large Bone",
    "雪狮子的尖爪":"Blangonga Claw+",
    "雪狮子的尖牙":"Blangonga Fang+",
    "雪狮子的尾巴":"Blangonga Tail",
    "雪狮子的毛":"Blangonga Hair",
    "雪狮子的爪":"Blangonga Claw",
    "雪狮子的牙":"Blangonga Fang",
    "雪狮子的白毛":"Blangonga White Hair",
    "雪狮子的皮":"Blangonga Hide",
    "雪狮子的靭尾":"Blangonga Tail+",
    "雪狮子的髭":"Blangonga Mustache",
    "雷光虫":"Thunder Bug",
    "霞龙的上皮":"Chameleos Hide",
    "霞龙的刚爪":"Chameleos Sharp Claw+",
    "霞龙的刚翼":"Chameleos Wing+",
    "霞龙的刚角":"Chameleos Horn+",
    "霞龙的宝玉":"Chameleos Gem",
    "霞龙的尖爪":"Chameleos Sharp Claw",
    "霞龙的尖角":"Chameleos Horn",
    "霞龙的极长舌":"Chameleos Tongue+",
    "霞龙的特上皮":"Chameleos Hide+",
    "霞龙的绝尾":"Chameleos Tail+",
    "霞龙的翼膜":"Chameleos Wing",
    "霞龙的重牙":"Chameleos Sharp Fang+",
    "霞龙的锐牙":"Chameleos Sharp Fang",
    "霞龙的长舌":"Chameleos Tongue",
    "霞龙的靭尾":"Chameleos Tail",
    "霸之苍曜角":"Tyrant Horn",
    "青怪鸟的优质翼":"Blue Kut-Ku Wing+",
    "青怪鸟的优质鳞":"Blue Kut-Ku Scale+",
    "青怪鸟的地狱耳":"Blue Kut-Ku Ear+",
    "青怪鸟的坚背甲":"Blue Kut-Ku Shell+",
    "青怪鸟的尖爪":"Blue Kut-Ku Claw+",
    "青怪鸟的尾巴":"Blue Kut-Ku Tail",
    "青怪鸟的爪":"Blue Kut-Ku Claw",
    "青怪鸟的翼":"Blue Kut-Ku Wing",
    "青怪鸟的翼爪":"Blue Kut-Ku Claw Wing",
    "青怪鸟的耳":"Blue Kut-Ku Ear",
    "青怪鸟的背甲":"Blue Kut-Ku Shell",
    "青怪鸟的鳞":"Blue Kut-Ku Scale",
    "青绿色的韧皮":"Green Tough Skin",
    "青色的翼膜":"Blue Patagium",
    "飞虫之羽":"Vespoid Wing",
    "骇人的毒臼齿":"Terrible Poison Molars",
    "骇狩蛛的体液":"D.Baelidae Fluid",
    "骇狩蛛的刚毛":"D.Baelidae Hair+",
    "骇狩蛛的坚壳":"D.Baelidae Shell+",
    "骇狩蛛的复眼":"D.Baelidae Eye+",
    "骇狩蛛的妖面壳":"D.Baelidae Demon Face Shell",
    "骇狩蛛的尖爪":"D.Baelidae Claw+",
    "骇狩蛛的毒液":"D.Baelidae Poisen Fluid",
    "骇狩蛛的毛":"D.Baelidae Hair",
    "骇狩蛛的浓液":"D.Baelidae Broth",
    "骇狩蛛的爪":"D.Baelidae Claw",
    "骇狩蛛的甲壳":"D.Baelidae Shell",
    "骇狩蛛的盾爪坚壳":"D.Baelidae Shield Claw+",
    "骇狩蛛的盾爪壳":"D.Baelidae Shield Claw",
    "骇狩蛛的眼":"D.Baelidae Eye",
    "骇狩蛛的蛛丝":"D.Baelidae Silk",
    "骇狩蛛的韧蛛丝":"D.Baelidae Silk+",
    "骇狩蛛的麻痹液":"D.Baelidae Palsy Fluid",
    "高压的电气袋":"High-voltage Electro Sac+",
    "高级技能珠素材券":"Advanced Skill Coupon",
    "高级珍珠色的翼膜":"Pearly Patagium",
    "鬼狩蛛的体液":"Baelidae Fluid",
    "鬼狩蛛的刚毛":"Baelidae Hair+",
    "鬼狩蛛的坚壳":"Baelidae Shell+",
    "鬼狩蛛的复眼":"Baelidae Complex Eye",
    "鬼狩蛛的尖爪":"Baelidae Claw+",
    "鬼狩蛛的毛":"Baelidae Hair",
    "鬼狩蛛的浓液":"Baelidae Broth",
    "鬼狩蛛的爪":"Baelidae Claw",
    "鬼狩蛛的甲壳":"Baelidae Shell",
    "鬼狩蛛的盾爪坚壳":"Baelidae Shield Claw+",
    "鬼狩蛛的盾爪壳":"Baelidae Shield Claw",
    "鬼狩蛛的蛛丝":"Baelidae Silk",
    "鬼狩蛛的韧蛛丝":"Baelidae Silk+",
    "鬼狩蛛的鬼眼":"Baelidae Ghost Eye",
    "鬼狩蛛的鬼面壳":"Baelidae Ghost Face Shell",
    "鬼王之紫角":"Ghost King Purple Horn",
    "鬼王之角":"Ghost King Horn",
    "魅惑色的柔皮":"Alluring Hide+",
    "魅惑色的环状嘴":"Alluring Ring Mouth",
    "魅惑色的皮":"Alluring Skin",
    "魅惑色的翼膜":"Alluring Patagium",
    "鱼龙之牙":"Piscine Wyvern Teeth",
    "鲜红的龙血":"Red Dragon Blood",
    "鹿角":"Antlers",
    "麻痹腺体":"Paralysis Glands",
    "麻痹蘑菇":"Paralysis Mushroom",
    "黄绿色的鸟龙皮":"Yellow Bird Wyvern Skin",
    "黄色的唾液":"Yellow Saliva",
    "黄速龙王的优质皮":"Gendrome Hide+",
    "黄速龙王的大头冠":"Gendrome Head+",
    "黄速龙王的头冠":"Gendrome Head",
    "黄速龙王的尖爪":"Gendrome Claw+",
    "黄速龙王的尾巴":"Gendrome Tail",
    "黄速龙王的爪":"Gendrome Claw",
    "黄速龙王的皮":"Gendrome Hide",
    "黄速龙王的韧尾":"Gendrome Tail+",
    "黄速龙王的麻痹尖牙":"Gendrome Fang+",
    "黄速龙王的麻痹牙":"Gendrome Fang",
    "黄速龙的优质鳞":"Genprey Scale+",
    "黄速龙的鳞":"Genprey Scale",
    "黄速龙麻痹牙":"Gendrome Yellow Paralysis Teeth",
    "黏着白蚁":"Glueglopper",
    "黏着草":"Adhesion Grass",
    "黑狼鸟的优质鳞":"Garuga Scale+",
    "黑狼鸟的刚翼":"Yian Garuga Wing+",
    "黑狼鸟的刚翼爪":"Garuga Claw+",
    "黑狼鸟的刚髭":"Garuga Mustache+",
    "黑狼鸟的喙":"Yian Garuga Beak",
    "黑狼鸟的地狱耳":"Garuga Hell Ear+",
    "黑狼鸟的坚壳":"Garuga Shell+",
    "黑狼鸟的坚背甲":"Yian Garuga Firm Carapace+",
    "黑狼鸟的尖喙":"Yian Garuga Beak+",
    "黑狼鸟的翼":"Yian Garuga Wing",
    "黑狼鸟的翼膜":"Yian Garuga Wing Membrane",
    "黑狼鸟的背甲":"Yian Garuga Carapace",
    "黑狼鸟的韧翼膜":"Garuga Webbing+",
    "黑珍珠":"Black Pearl",
    "黯淡的粘液":"Dark Mucus",
    "龙头壳":"Wyvern Skull",
    "龙牙":"Wyvern Tooth",
    "龙骨【中】":"Monster Bone M",
    "龙骨【大】":"Monster Bone L",
    "龙骨【小】":"Monster Bone S",
    "�黄的毛":"Yellow Hair",

    "KO珠【1】":"KO Jewel 1",
    "KO珠【3】":"KO Jewel 3",
    "体力珠【1】":"Vitality Jewel 1",
    "体术珠【1】":"Physique Jewel 1",
    "体术珠【2】":"Physique Jewel 2",
    "倒地珠【1】":"Trip Jewel 1",
    "冰结珠【1】":"Frost Jewel 1",
    "冰结珠【2】":"Frost Jewel 2",
    "制冰珠【1】":"Nul-Ice Jewel 1",
    "制水珠【1】":"Nul-Water Jewel 1",
    "制火珠【1】":"Nul-Fire Jewel 1",
    "制雷珠【1】":"Nul-Thunder Jewel 1",
    "刺杀珠【1】":"Ambush Jewel 1",
    "刺杀珠【3】":"Ambush Jewel 3",
    "剑术珠【1】":"Fencer Jewel 1",
    "剑术珠【3】":"Fencer Jewel 3",
    "加弹珠【1】":"ShotPlus Jewel 1",
    "加护珠【1】":"Nul-Dragon Jewel 1",
    "加散珠【1】":"PelletPlus Jewel 1",
    "加榴珠【1】":"ClustPlus Jewel 1",
    "加贯珠【1】":"PiercePlus Jewel 1",
    "匠珠【2】":"Handicraft Jewel 2",
    "千里珠【1】":"Psychic Jewel 1",
    "反动珠【1】":"Absorber Jewel 1",
    "古龙珠【1】":"Elder Dragon Jewel 1",
    "名药珠【1】":"Herbalism Jewel 1",
    "吸引珠【1】":"Attraction Jewel 1",
    "吸引珠【2】":"Attraction Jewel 2",
    "回避珠【1】":"Evasion Jewel 1",
    "回避珠【2】":"Evasion Jewel 2",
    "广域珠【1】":"Friendship Jewel 1",
    "广域珠【2】":"Friendship Jewel 2",
    "底力珠【1】":"Potential Jewel 1",
    "底力珠【2】":"Potential Jewel 2",
    "强壁珠【1】":"Shield Jewel 1",
    "强壁珠【2】":"Shield Jewel 2",
    "强弹珠【1】":"Forceshot Jewel 1",
    "忍脚珠【1】":"Ninja Jewel 1",
    "抗棘珠【1】":"Staunch Jewel 1",
    "抗震珠【1】":"Quake Jewel 1",
    "拔刀珠【1】":"Draw Jewel 1",
    "拔刀珠【2】":"Draw Jewel 2",
    "攻击珠【1】":"Attack Jewel 1",
    "攻击珠【2】":"Attack Jewel 2",
    "攻击珠【3】":"Attack Jewel 3",
    "散弹珠【1】":"Pellet Jewel 1",
    "斗魂珠【1】":"Spirit Jewel 1",
    "斗魂珠【2】":"Spirit Jewel 2",
    "斩铁珠【1】":"Razor Jewel 1",
    "斩铁珠【3】":"Razor Jewel 3",
    "无伤珠【1】":"Flawless Jewel 1",
    "无伤珠【2】":"Flawless Jewel 2",
    "无食珠【1】":"Hungerless Jewel 1",
    "无食珠【2】":"Hungerless Jewel 2",
    "早填珠【1】":"Quickload Jewel 1",
    "早复珠【1】":"Recovery Jewel 1",
    "早复珠【2】":"Recovery Jewel 2",
    "早气珠【1】":"Refresh Jewel 1",
    "早气珠【2】":"Refresh Jewel 2",
    "早食珠【1】":"Gobbler Jewel 1",
    "根性珠【1】":"Guts Jewel 1",
    "根性珠【2】":"Guts Jewel 2",
    "毒瓶珠【1】":"PoisonPlus Jewel 1",
    "治愈珠【1】":"Medicine Jewel 1",
    "治愈珠【2】":"Medicine Jewel 2",
    "流水珠【1】":"Stream Jewel 1",
    "流水珠【2】":"Stream Jewel 2",
    "火炎珠【1】":"Blaze Jewel 1",
    "火炎珠【2】":"Blaze Jewel 2",
    "炮术珠【1】":"Artillery Jewel 1",
    "牙兽珠【1】":"Fanged Beast Jewel 1",
    "牙兽珠【2】":"Fanged Beast Jewel 2",
    "特攻珠【1】":"Disabler Jewel 1",
    "特攻珠【2】":"Disabler Jewel 2",
    "生存珠【1】":"Ranger Jewel 1",
    "甲壳珠【1】":"Carapacean Jewel 1",
    "甲壳珠【2】":"Carapacean Jewel 2",
    "痛击珠【1】":"Tenderizer Jewel 1",
    "痛击珠【3】":"Tenderizer Jewel 3",
    "看破珠【1】":"Hardy Jewel 1",
    "看破珠【2】":"Hardy Jewel 2",
    "眠瓶珠【1】":"SleepPlus Jewel 1",
    "短缩珠【1】":"Charger Jewel 1",
    "短缩珠【3】":"Charger Jewel 3",
    "研磨珠【1】":"Grinder Jewel 1",
    "破龙珠【1】":"Dragon Jewel 1",
    "破龙珠【2】":"Dragon Jewel 2",
    "耐冰珠【1】":"Ice Res Jewel 1",
    "耐寒珠【1】":"Cold Res Jewel 1",
    "耐寒珠【2】":"Cold Res Jewel 2",
    "耐暑珠【1】":"Heat Res Jewel 1",
    "耐暑珠【2】":"Heat Res Jewel 2",
    "耐毒珠【1】":"Antidote Jewel 1",
    "耐水珠【1】":"Water Res Jewel 1",
    "耐火珠【1】":"Fire Res Jewel 1",
    "耐痹珠【1】":"Paralysis Jewel 1",
    "耐眠珠【1】":"Pep Jewel 1",
    "耐粘珠【1】":"Tracker Jewel 1",
    "耐绝珠【1】":"Steadfast Jewel 1",
    "耐菌珠【1】":"Antibacterial Jewel 1",
    "耐雷珠【1】":"Thunder Res Jewel 1",
    "耐震珠【1】":"Tectonic Jewel 1",
    "耐龙珠【1】":"Dragon Res Jewel 1",
    "背水珠【1】":"High Stakes Jewel 1",
    "背水珠【2】":"High Stakes Jewel 2",
    "草药珠【1】":"Herb Jewel 1",
    "装填珠【2】":"Capacity Jewel 2",
    "观察珠【1】":"Perception Jewel 1",
    "贯通珠【1】":"Pierce Jewel 1",
    "跳跃珠【1】":"Jumping Jewel 1",
    "达人珠【1】":"Expert Jewel 1",
    "达人珠【2】":"Expert Jewel 2",
    "达人珠【3】":"Expert Jewel 3",
    "逆境珠【1】":"Fortitude Jewel 1",
    "逆境珠【2】":"Fortitude Jewel 2",
    "速射珠【1】":"Salvo Jewel 1",
    "重击珠【1】":"Destroyer Jewel 1",
    "重击珠【3】":"Destroyer Jewel 3",
    "铁壁珠【1】":"Ironwall Jewel 1",
    "铁壁珠【2】":"Ironwall Jewel 2",
    "锁气珠【1】":"Stun Lock Jewel 1",
    "锁气珠【3】":"Stun Lock Jewel 3",
    "防御珠【1】":"Defense Jewel 1",
    "防御珠【2】":"Defense Jewel 2",
    "防御珠【3】":"Defense Jewel 3",
    "防音珠【1】":"Earplug Jewel 1",
    "防音珠【3】":"Earplug Jewel 3",
    "防风珠【1】":"Wind Res Jewel 1",
    "防风珠【2】":"Wind Res Jewel 2",
    "陷阱珠【1】":"Trapmaster Jewel 1",
    "雷光珠【1】":"Bolt Jewel 1",
    "雷光珠【2】":"Bolt Jewel 2",
    "飞龙珠【1】":"Flying Wyvern Jewel 1",
    "食汉珠【1】":"Metabolism Jewel 1",
    "鱼龙珠【1】":"Piscine Wyvern Jewel 1",
    "鱼龙珠【2】":"Piscine Wyvern Jewel 2",
    "鸟龙珠【1】":"Bird Wyvern Jewel 1",
    "鸟龙珠【2】":"Bird Wyvern Jewel 2",
    "麻瓶珠【1】":"ParaPlus Jewel 1",
    "鼓笛珠【1】":"Sonorous Jewel 1",
};

function translate(text) {
    // if found, return translation
    if (text in translations) {
        return translations[text];
    }
    // otherwise the original text
    return text;
}
