function translate(text) {
	var out = text;
//Bow Coating
	if (text == '强击瓶') {out = 'Power Coating';};
	if (text == '毒瓶') {out = 'Poison Coating';};
	if (text == '麻瓶') {out = 'Para Coating';};
	if (text == '接击瓶') {out = 'C.Range Coating';};
	if (text == '眠瓶') {out = 'Sleep Coating';};
//Bow Lob
	if (text == '天型1级') {out = 'Arrow Rain Lv1';};
	if (text == '天型2级') {out = 'Arrow Rain Lv2';};
	if (text == '天型3级') {out = 'Arrow Rain Lv3';};
	if (text == '地型1级') {out = 'Arrow Bomb Lv1';};
	if (text == '地型2级') {out = 'Arrow Bomb Lv2';};
	if (text == '地型3级') {out = 'Arrow Bomb Lv3';};
//Sizes
	if (text == '小') {out = 'Small';};
	if (text == '中') {out = 'Med';};
	if (text == '大') {out = 'Large';};
	if (text == '慢') {out = 'Slow';};
	if (text == '快') {out = 'Fast';};
//Bowgun Ammo  
	if (text == '通常弹1级') {out = 'Normal S Lv1';};
	if (text == '通常弹2级') {out = 'Normal S Lv2';};
	if (text == '通常弹3级') {out = 'Normal S Lv3';};
	if (text == '通常弹Lv3') {out = 'Normal S Lv3';};
	if (text == '散弹1级') {out = 'Pellet S Lv1';};
	if (text == '散弹2级') {out = 'Pellet S Lv2';};
	if (text == '散弹3级') {out = 'Pellet S Lv3';};
	if (text == '贯通弹1级') {out = 'Pierce S Lv1';};
	if (text == '贯通弹2级') {out = 'Pierce S Lv2';};
	if (text == '贯通弹3级') {out = 'Pierce S Lv3';};
	if (text == '彻甲榴弹1级') {out = 'Crag S Lv1';};
	if (text == '彻甲榴弹2级') {out = 'Crag S Lv2';};
	if (text == '彻甲榴弹3级') {out = 'Crag S Lv3';};
	if (text == '麻痹弹') {out = 'Para S';};
	if (text == '致眠弹') {out = 'Sleep S';};
	if (text == '火焰弹') {out = 'Flaming S';};
	if (text == '猛毒弹') {out = 'Poison S';};
	if (text == '水冷弹') {out = 'Water S';};
	if (text == '电击弹') {out = 'Thunder S';};
	if (text == '冰结弹') {out = 'Freeze S';};
//Bowgun Secondary Title
	if (text == '速射2发') {out = 'Rapid ';};
	if (text == '速射3发') {out = 'Rapid ';};
	if (text == '蓄力') {out = 'Charge ';};
//Armor Skills
	if (text == '伏击') {out = 'Ambush';};
	if (text == '抗菌') {out = 'Anti-bacterial';};
	if (text == '攻击') {out = 'Attack';};
	if (text == '蝶舞') {out = 'Butterfly Dance';};
	if (text == '耐寒') {out = 'Cold Res';};
	if (text == '体术') {out = 'Constitution';};
	if (text == '匠') {out = 'Handicraft';};
	if (text == '拔刀会心') {out = 'Crit Draw';};
	if (text == '防御') {out = 'Defense';};
	if (text == '重击') {out = 'Destroyer';};
	if (text == '龙属性攻击') {out = 'Dragon Atk';};
	if (text == '食事') {out = 'Eating';};
	if (text == '回避距离') {out = 'Evade Dist';};
	if (text == '回避性能') {out = 'Evasion';};
	if (text == '达人') {out = 'Expert';};
	if (text == '集中') {out = 'FastCharge';};
	if (text == '剑术') {out = 'Fencing';};
	if (text == '火属性攻击') {out = 'Fire Atk';};
	if (text == '火耐性') {out = 'Fire Res';};
	if (text == '吃货') {out = 'Gluttony';};
	if (text == '防御性能') {out = 'Guard';};
	if (text == '防御强化') {out = 'Guard Up';};
	if (text == '根性') {out = 'Guts';};
	if (text == '体力') {out = 'Health';};
	if (text == '听觉保护') {out = 'Hearing';};
	if (text == '耐暑') {out = 'Heat Res';};
	if (text == '药王') {out = 'Herb King';};
	if (text == '荷尔蒙') {out = 'Hormone';};
	if (text == '饥饿感') {out = 'Hunger';};
	if (text == '冰属性攻击') {out = 'Ice Atk';};
	if (text == '冰耐性') {out = 'Ice Res';};
	if (text == '会心术') {out = 'Knowing Technique';};
	if (text == 'KO术') {out = 'KO';};
	if (text == '装填术') {out = 'Loading';};
	if (text == '耐泥雪') {out = 'Mud/Snow';};
	if (text == '通常弹强化') {out = 'Normal Up';};
	if (text == '麻痹抵抗') {out = 'Paralysis';};
	if (text == '散弹强化') {out = 'Pellet Up';};
	if (text == '观察眼') {out = 'Perception';};
	if (text == '贯通弹强化') {out = 'Pierce Up';};
	if (text == '毒抵抗') {out = 'Poison';};
	if (text == '底力') {out = 'Potential';};
	if (text == '加护') {out = 'Protection';};
	if (text == '千里眼') {out = 'Psychic';};
	if (text == '回复速度') {out = 'Rec Speed';};
	if (text == '反动') {out = 'Recoil';};
	if (text == '快速装填') {out = 'Reload Spd';};
	if (text == '强韧') {out = 'Resilience';};
	if (text == '气息') {out = 'Sense';};
	if (text == '研磨师') {out = 'Sharpener';};
	if (text == '锋利度') {out = 'Sharpness';};
	if (text == '睡眠抵抗') {out = 'Sleep';};
	if (text == '高速设置') {out = 'SpeedSetup';};
	if (text == '斗魂') {out = 'Spirit';};
	if (text == '耐力回复') {out = 'Stam Recov';};
	if (text == '特殊攻击') {out = 'Status';};
	if (text == '气绝抵抗') {out = 'Stun';};
	if (text == '逆境') {out = 'Survivor';};
	if (text == '痛击') {out = 'Tenderizer';};
	if (text == '刺伤') {out = 'Bleeding';};
	if (text == '雷耐性') {out = 'Thunder Res';};
	if (text == '雷属性攻击') {out = 'ThunderAtk';};
	if (text == '耐震') {out = 'Tremor Res';};
	if (text == '倒地之力') {out = 'Tripping Power';};
	if (text == '无伤') {out = 'Unscathed';};
	if (text == '水属性攻击') {out = 'Water Atk';};
	if (text == '广域化') {out = 'Wide-Range';};
	if (text == '风压抵抗') {out = 'Wind Res';};
	if (text == '甲壳猎人') {out = 'Crustaceans Hunter';};
	if (text == '鸟龙猎人') {out = 'Bird Dragons Hunter';};
	if (text == '飞龙猎人') {out = 'Dragons Hunter';};

	if (text == '眠弹增加') {out = 'Sleep C+';};
	if (text == '耐力消耗下降') {out = 'Endurance Consumption Down';};
	if (text == '猎人生活') {out = 'Hunter Life';};
	if (text == '水耐性') {out = 'Water Res';};
	if (text == '龙耐性') {out = 'Dragon Res';};
	if (text == '恢复量') {out = 'Recovery Amount';};
	if (text == '速射') {out = 'Rapid Fire';};
	if (text == '笛') {out = 'Flute';};
	if (text == '炮术') {out = 'Artillery';};
	if (text == '古龙猎人') {out = 'Cologne Hunter';};
	if (text == '鱼龙猎人') {out = 'Ichthyosaur Hunter';};
	if (text == '牙兽猎人') {out = 'Tooth Beast Hunter';};


	if (text == '真晓风') {out = 'True Dawnwind';};

//Monster Names
	if (text == '灰晶蝎') {out = '<a href="/monsters/akura-jebia/" target="_blank">Akura Jebia</a>';};
	if (text == '尾晶蝎') {out = '<a href="/monsters/akura-vashimu/" target="_blank">Akura Vashimu</a>';};
	if (text == '苍火龙') {out = '<a href="/monsters/azure-rathalos/" target="_blank">Azure Rathalos</a>';};
	if (text == '鬼狩蛛') {out = '<a href="/monsters/baelidae/" target="_blank">Baelidae</a>';};
	if (text == '岩龙') {out = '<a href="/monsters/basarios/" target="_blank">Basarios</a>';};
	if (text == '铠龙') {out = '<a href="/monsters/basarios/" target="_blank">Basarios?</a>';};
	if (text == '雪狮子王') {out = '<a href="/monsters/blangonga/" target="_blank">Blangonga</a>';};
	if (text == '青怪鸟') {out = '<a href="/monsters/blue-yian-kut-ku/" target="_blank">Blue Yian Kut-Ku</a>';};
	if (text == '大野猪王') {out = '<a href="/monsters/bulldrome/" target="_blank">Bulldrome</a>';};
	if (text == '河狸兽') {out = '<a href="/monsters/caeserber/" target="_blank">Caeserber</a>';};
	if (text == '沙龙王') {out = '<a href="/monsters/cephadrome/" target="_blank">Cephadrome</a>';};
	if (text == '沙雷鸟') {out = '<a href="/monsters/chramine/" target="_blank">Chramine</a>';};
	if (text == '烈焰女王') {out = '<a href="/monsters/conflagration-rathian/" target="_blank">Conflagration Rathian</a>';};
	if (text == '烈焰雌火龙') {out = '<a href="/monsters/conflagration-rathian/" target="_blank">Conflagration Rathian</a>';};
	if (text == '桃毛兽王') {out = '<a href="/monsters/congalala/" target="_blank">Congalala</a>';};
	if (text == '晶岩龙') {out = '<a href="/monsters/crystal-basarios/" target="_blank">Crystal Basarios</a>';};
	if (text == '大名盾蟹') {out = '<a href="/monsters/daimyo-hermitaur/" target="_blank">Daimyo Hermitaur</a>';};
	if (text == '角龙') {out = '<a href="/monsters/diablos/" target="_blank">Diablos</a>';};
	if (text == '祸星龙') {out = '<a href="/monsters/doom-estrellian/" target="_blank">Doom Estrellian</a>';};
	if (text == '骇狩蛛') {out = '<a href="/monsters/dread-baelidae/" target="_blank">Dread Baelidae</a>';};
	if (text == '星龙') {out = '<a href="/monsters/estrellian/" target="_blank">Estrellian</a>';};
	if (text == '黄速龙王') {out = '<a href="/monsters/gendrome/" target="_blank">Gendrome</a>';};
	if (text == '战鬼河狸兽') {out = '<a href="/monsters/ghost-caeserber/" target="_blank">Ghost Caeserber</a>';};
	if (text == '白速龙王') {out = '<a href="/monsters/giadrome/" target="_blank">Giadrome</a>';};
	if (text == '金毛兽王') {out = '<a href="/monsters/gold-congalala/" target="_blank">Gold Congalala</a>';};
	if (text == '金眠鸟') {out = '<a href="/monsters/gold-hypnocatrice/" target="_blank">Gold Hypnocatrice</a>';};
	if (text == '红莲砦蟹') {out = '<a href="/monsters/guren-shen-gaoren/" target="_blank">Guren Shen Gaoren</a>';};
	if (text == '毒怪鸟') {out = '<a href="/monsters/gypceros/" target="_blank">Gypceros</a>';};
	if (text == '眠鸟') {out = '<a href="/monsters/hypnocatrice/" target="_blank">Hypnocatrice</a>';};
	if (text == '冰雷鸟') {out = '<a href="/monsters/ice-chramine/" target="_blank">Ice Chramine</a>';};
	if (text == '红速龙王') {out = '<a href="/monsters/iodrome/" target="_blank">Iodrome</a>';};
	if (text == '电龙') {out = '<a href="/monsters/khezu/" target="_blank">Khezu</a>';};
	if (text == '钢龙') {out = '<a href="/monsters/kushala-daora/" target="_blank">Kushala Daora</a>';};
	if (text == '电甲虫') {out = '<a href="/monsters/lightenna/" target="_blank">Lightenna</a>';};
	if (text == 'NBY') {out = '<a href="/monsters/lightenna/" target="_blank">Lightenna</a>';};
	if (text == '荒厄龙') {out = '<a href="/monsters/merphistophelin/" target="_blank">Merphistophelin</a>';};
	if (text == 'NB5') {out = '<a href="/monsters/merphistophelin/" target="_blank">Merphistophelin</a>';};
	if (text == '一角龙') {out = '<a href="/monsters/monoblos/" target="_blank">Monoblos</a>';};
	if (text == '独耳黑狼鸟') {out = '<a href="/monsters/one-eared-yian-garuga/" target="_blank">One-Eared Yian Garuga</a>';};
	if (text == '片耳黑狼鸟') {out = '<a href="/monsters/one-eared-yian-garuga/" target="_blank">One-Eared Yian Garuga</a>';};
	if (text == '樱火龙') {out = '<a href="/monsters/pink-rathian/" target="_blank">Pink Rathian</a>';};
	if (text == '水龙') {out = '<a href="/monsters/plesioth/" target="_blank">Plesioth</a>';};
	if (text == '紫毒鸟') {out = '<a href="/monsters/purple-gypceros/" target="_blank">Purple Gypceros</a>';};
	if (text == '雄火龙') {out = '<a href="/monsters/rathalos/" target="_blank">Rathalos</a>';};
	if (text == '雌火龙') {out = '<a href="/monsters/rathian/" target="_blank">Rathian</a>';};
	if (text == '红电龙') {out = '<a href="/monsters/red-khezu/" target="_blank">Red Khezu</a>';};
	if (text == '砂岩龙') {out = '<a href="/monsters/sandstone-basarios/" target="_blank">Sandstone Basarios</a>';};
	if (text == '断刃一角龙') {out = '<a href="/monsters/shattered-monoblos/" target="_blank">Shattered Monoblos</a>';};
	if (text == '断角一角龙') {out = '<a href="/monsters/shattered-monoblos/" target="_blank">Shattered Monoblos</a>';};
	if (text == '砦蟹') {out = '<a href="/monsters/shen-gaoren/" target="_blank">Shen Gaoren</a>';};
	if (text == '老山蟹') {out = '<a href="/monsters/shen-gaoren/" target="_blank">Shen Gaoren</a>';};
	if (text == '将军镰蟹') {out = '<a href="/monsters/shogun-ceanataur/" target="_blank">Shogun Ceanataur</a>';};
	if (text == '银眠鸟') {out = '<a href="/monsters/silver-hypnocatrice/" target="_blank">Silver Hypnocatrice</a>';};
	if (text == '剑极狼') {out = '<a href="/monsters/slicemargl/" target="_blank">Slicemargl</a>';};
	if (text == 'NBX') {out = '<a href="/monsters/slicemargl/" target="_blank">Slicemargl</a>';};
	if (text == '剑豪镰蟹') {out = '<a href="/monsters/swordmaster-shogun-ceanataur/" target="_blank">Swordmaster Shogun Ceanataur</a>';};
	if (text == '吞渊龙') {out = '<a href="/monsters/tartaronis/" target="_blank">Tartaronis</a>';};
	if (text == '初阶吞渊龙') {out = '<a href="/monsters/tartaronis/" target="_blank">Tartaronis</a>';};
	if (text == '铠岩砦蟹') {out = '<a href="/monsters/tepekki-shen-gaoren/" target="_blank">Tepekki Shen Gaoren</a>';};
	if (text == '轰龙') {out = '<a href="/monsters/tigrex/" target="_blank">Tigrex</a>';};
	if (text == '蓝速龙王') {out = '<a href="/monsters/velocidrome/" target="_blank">Velocidrome</a>';};
	if (text == '沙狸兽') {out = '<a href="/monsters/yellow-caeserber/" target="_blank">Yellow Caeserber</a>';};
	if (text == '黑狼鸟') {out = '<a href="/monsters/yian-garuga/" target="_blank">Yian Garuga</a>';};
	if (text == '大怪鸟') {out = '<a href="/monsters/yian-kut-ku/" target="_blank">Yian Kut-Ku</a>';};
	if (text == '红莲砦蟹，铠岩砦蟹') {out = '<a href="/monsters/guren-shen-gaoren/" target="_blank">Guren Shen Gaoren</a>, <a href="/monsters/tepekki-shen-gaoren/" target="_blank">Tepekki Shen Gaoren</a>';};
	if (text == '镰蟹') {out = '<a href="/monsters/shogun-ceanataur/" target="_blank">Ceanataur</a>';};
	if (text == '盾蟹') {out = '<a href="/monsters/daimyo-hermitaur/" target="_blank">Hermitaur</a>';};
	if (text == '雄火龙，苍火龙') {out = '<a href="/monsters/rathalos/" target="_blank">Rathalos</a>, <a href="/monsters/azure-rathalos/" target="_blank">Azure Rathalos</a>';};

	if (text == '特殊铳枪') {out = 'Yian Kut-Ku + Bulldrome';};
	if (text == '新手') {out = 'Velociprey';};
	if (text == '骨') {out = 'Bones';};
	if (text == '铁') {out = 'Rocks';};
	if (text == '特殊枪') {out = 'Gendrome + Bulldrome';};
	if (text == 'sunaku') {out = 'Congalala + Velocidrome';};
	if (text == '鄂') {out = 'Congalala + Gendrome';};
	if (text == 'kurimu') {out = 'Gendrome';};
	if (text == 'subaku') {out = 'Bulldrome + Congalala';};
	if (text == 'hali') {out = 'Congalala';};
	if (text == '特殊笛') {out = 'Baelidae + Yian Kut-Ku';};
	if (text == '野性') {out = 'Congalala';};
	if (text == '爬虫') {out = 'Bones';};
	if (text == '十字枪') {out = 'Rocks';};

	//Monster Names No Links
	if (text == 'nl灰晶蝎') {out = 'Akura Jebia';};
	if (text == 'nl尾晶蝎') {out = 'Akura Vashimu';};
	if (text == 'nl苍火龙') {out = 'Azure Rathalos';};
	if (text == 'nl鬼狩蛛') {out = 'Baelidae';};
	if (text == 'nl岩龙') {out = 'Basarios';};
	if (text == 'nl铠龙') {out = 'Basarios?';};
	if (text == 'nl雪狮子王') {out = 'Blangonga';};
	if (text == 'nl青怪鸟') {out = 'Blue Yian Kut-Ku';};
	if (text == 'nl大野猪王') {out = 'Bulldrome';};
	if (text == 'nl河狸兽') {out = 'Caeserber';};
	if (text == 'nl沙龙王') {out = 'Cephadrome';};
	if (text == 'nl沙雷鸟') {out = 'Chramine';};
	if (text == 'nl烈焰女王') {out = 'Conflagration Rathian';};
	if (text == 'nl桃毛兽王') {out = 'Congalala';};
	if (text == 'nl晶岩龙') {out = 'Crystal Basarios';};
	if (text == 'nl大名盾蟹') {out = 'Daimyo Hermitaur';};
	if (text == 'nl角龙') {out = 'Diablos';};
	if (text == 'nl祸星龙') {out = 'Doom Estrellian';};
	if (text == 'nl骇狩蛛') {out = 'Dread Baelidae';};
	if (text == 'nl星龙') {out = 'Estrellian';};
	if (text == 'nl黄速龙王') {out = 'Gendrome';};
	if (text == 'nl战鬼河狸兽') {out = 'Ghost Caeserber';};
	if (text == 'nl白速龙王') {out = 'Giadrome';};
	if (text == 'nl金毛兽王') {out = 'Gold Congalala';};
	if (text == 'nl金眠鸟') {out = 'Gold Hypnocatrice';};
	if (text == 'nl红莲砦蟹') {out = 'Guren Shen Gaoren';};
	if (text == 'nl毒怪鸟') {out = 'Gypceros';};
	if (text == 'nl眠鸟') {out = 'Hypnocatrice';};
	if (text == 'nl冰雷鸟') {out = 'Ice Chramine';};
	if (text == 'nl红速龙王') {out = 'Iodrome';};
	if (text == 'nl电龙') {out = 'Khezu';};
	if (text == 'nl钢龙') {out = 'Kushala Daora';};
	if (text == 'nl电甲虫') {out = 'Lightenna';};
	if (text == 'nl荒厄龙') {out = 'Merphistophelin';};
	if (text == 'nl一角龙') {out = 'Monoblos';};
	if (text == 'nl独耳黑狼鸟') {out = 'One-Eared Yian Garuga';};
	if (text == 'nl樱火龙') {out = 'Pink Rathian';};
	if (text == 'nl水龙') {out = 'Plesioth';};
	if (text == 'nl紫毒鸟') {out = 'Purple Gypceros';};
	if (text == 'nl雄火龙') {out = 'Rathalos';};
	if (text == 'nl雌火龙') {out = 'Rathian';};
	if (text == 'nl红电龙') {out = 'Red Khezu';};
	if (text == 'nl砂岩龙') {out = 'Sandstone Basarios';};
	if (text == 'nl断刃一角龙') {out = 'Shattered Monoblos';};
	if (text == 'nl砦蟹') {out = 'Shen Gaoren';};
	if (text == 'nl将军镰蟹') {out = 'Shogun Ceanataur';};
	if (text == 'nl银眠鸟') {out = 'Silver Hypnocatrice';};
	if (text == 'nl剑极狼') {out = 'Slicemargl';};
	if (text == 'nl剑豪镰蟹') {out = 'Swordmaster Shogun Ceanataur';};
	if (text == 'nl吞渊龙') {out = 'Tartaronis';};
	if (text == 'nl铠岩砦蟹') {out = 'Tepekki Shen Gaoren';};
	if (text == 'nl轰龙') {out = 'Tigrex';};
	if (text == 'nl蓝速龙王') {out = 'Velocidrome';};
	if (text == 'nl沙狸兽') {out = 'Yellow Caeserber';};
	if (text == 'nl黑狼鸟') {out = 'Yian Garuga';};
	if (text == 'nl大怪鸟') {out = 'Yian Kut-Ku';};
	if (text == 'nl红莲砦蟹，铠岩砦蟹') {out = 'Tepekki Shen Gaoren';};
	if (text == 'nl镰蟹') {out = 'Ceanataur';};
	if (text == 'nl盾蟹') {out = 'Hermitaur';};
	if (text == 'nl雄火龙，苍火龙') {out = 'Azure Rathalos';};
//Body Parts
	if (text == '头部') {out = 'Head';};
	if (text == '腹部') {out = 'Abdomen';};
	if (text == '左右手（钳）') {out = 'Left and Right Hands (Pincers)';};
	if (text == '壳') {out = 'Shell';};
	if (text == '背部') {out = 'Back';};
	if (text == '躯干（本体/胴体）') {out = 'Torso (Body/Carcass)';};
	if (text == '面部') {out = 'Face';};
	if (text == '左右翼') {out = 'Wings';};
	if (text == '左,右翼') {out = 'Wings';};
	if (text == '尾部（尻尾）') {out = 'Tail (Rump)';};
	if (text == '右手（钳）') {out = 'Right Hand (Pincer)';};
	if (text == '左,右手（钳）') {out = 'Left and Right Hand (Pincers)';};
	if (text == '左/右臂') {out = 'Arms';};
	if (text == '左/右翼') {out = 'Wings';};
//Places
	if (text == '大型怪物狩猎') {out = 'Large Monster Hunting';};
	if (text == '大型怪物狩猎挑战难度、王立委托、王立精英委托') {out = 'Large Monster Hunting Difficult Challenge, HR Hunting, HR Elite Hunting';};
	if (text == '王立委托、王立精英、极限') {out = 'HR Hunting, HR Elite, Limit Mode';};
	if (text == '王立委托、王立精英委托') {out = 'HR Hunting, HR Elite Hunting';};
	if (text == '活动') {out = 'Raid';};
	if (text == '王立精英委托') {out = 'HR Elite Hunting';};
	if (text == '王立委托') {out = 'HR Hunting';};
	if (text == '大湖围猎祭') {out = 'Great Lakes Hunting Festival';};
//Armor Skills
	if (text == '回复速度+1、观察眼、大胃王') {out = 'Rec Speed +1、Capture Guru、Gourmand';};
	if (text == '探知、速食') {out = 'Detect、Speed Eating';};
	if (text == '气绝减半、草药达人') {out = 'Halve Stun、Herbal Daren';};
	if (text == '砥石使用高速化、防御力提升（小）') {out = 'Speed Sharpening、Defense Up (S)';};
	if (text == '通常弹&连射矢强化、防御力提升（小）') {out = 'Normal/Rapid Up、Defense Up (S)';};
	if (text == '攻击力提升（小）、火属性耐性强化+1') {out = 'Attack Up (S)、Fire Res +1';};
	if (text == '麻痹免疫、状态异常攻击+1') {out = 'Negate Paralysis、Status Atk +1';};
	if (text == 'KO术、砥石使用高速化、挑衅') {out = 'KO King、Speed Sharpening、Taunt';};
	if (text == 'KO术、散弹/矢强化、挑衅') {out = 'KO King、Pellet/Spread Up、Taunt';};	
	if (text == '耐泥雪、陷阱师') {out = 'Mud/Snow、Trap Master';};
	if (text == '毒减半、雷属性耐性强化+1') {out = 'Halve Poison、Thunder Atk +1';};
	if (text == '抗菌、速食、饥饿感增加') {out = 'Anti-bacterial、Speed Eating、Raise Hunger';};
	if (text == '风压（小）无效、无伤') {out = 'Windproof (Lo)、Peak Performance';};
	if (text == '耐暑、暴击') {out = 'Heat Cancel、Violent Strike';};
	if (text == '防御力提升（小）、风压（小）无效、雷属性攻击弱化') {out = 'Defense Up (S)、Windproof (Lo)、Thunder Atk Down';};
	if (text == '见切+1、火属性攻击强化+1、体力弱化-1') {out = 'Critical Eye +1、Fire Atk +1、Health -1';};
	if (text == '回复速度+3、气绝倍化') {out = 'Rec Speed +3、Double Stun';};
	if (text == '睡眠免疫、防御等级+1、麻痹倍化') {out = 'Negate Sleep、Guard +1、Double Paralysis';};
	if (text == '睡眠免疫、上弹速度强化+1、麻痹倍化') {out = 'Negate Sleep、Reload Spd +1、Double Paralysis';};
	if (text == '睡眠免疫、吸引、耐力回复迟缓-1') {out = 'Negate Sleep、Attract、Stam Recov -1';};
	if (text == '火事场力+1、破坏王、防御力降低（小）') {out = 'Adrenaline +1、Partbreaker、Defense Down (S)';};
	if (text == '毒减半、麻痹免疫、睡眠倍化') {out = 'Halve Poison、Negate Paralysis、Double Sleep';};
	if (text == '气绝免疫、风压（小）无效、恶灵加持') {out = 'Negate Stun、Windproof (Lo)、Evil Blessing';};
	if (text == '业物、砥石使用高速化、体力弱化-2') {out = 'Sharp、Speed Sharpening、Health -2';};	
	if (text == '贯通弹/矢强化、上弹速度强化+1、体力弱化-2') {out = 'Pierce/Pierce Up、Reload Spd +1、Health -2';};
	if (text == '耐泥雪、耐寒、冰属性攻击强化+1、气绝倍化') {out = 'Mud/Snow、Cold Res、Ice Itk +1、Double Stun';};
	if (text == '化蝶、隐秘、见切-1') {out = 'Butterfly Form、Sneak、Critical Eye -1';};
	if (text == '通常弹&连射矢强化 、防御力提升（小）') {out = 'Normal/Rapid Up 、Defense Up (S)';};
	if (text == '体力强化+1、攻击力提升（小）') {out = 'Health +1、Attack Up (S)';};
	if (text == 'KO术、上弹速度强化+1、挑衅') {out = 'KO King、Reload Spd +1、Taunt';};
	if (text == '耐泥雪、陷阱师、回复速度+1') {out = '';};
	if (text == 'Mud/Snow、Trap Master、Rec Speed +1') {out = '';};
	if (text == '毒无效、雷属性耐性强化+1、饥饿感增加') {out = 'Negate Poison、Thunder Atk +1、Raise Hunger';};
	if (text == '抗菌、速食、看破+1、饥饿感增加') {out = 'Anti-bacterial、Speed Eating、See Through +1、Raise Hunger';};
	if (text == '风压（大）无效、无伤、耐力回复迟缓-1') {out = 'Windproof (Hi)、Peak Performance、Stam Recov -1';};
	if (text == '毒减半、体力强化+2、气绝倍化') {out = 'Halve Poison、Health +2、Double Stun';};
	if (text == '见切+1、状态异常攻击+1、火属性攻击强化+1、体力弱化-1') {out = 'Critical Eye +1、Status Atk +1、Fire Atk +1、Health -1';};
	if (text == '回复速度+3、雷属性攻击强化+1、气绝倍化') {out = 'Rec Speed +3、Thunder Atk +1、Double Stun';};
	if (text == '睡眠免疫、体术+1、吸引、耐力回复迟缓-1') {out = 'Negate Sleep、Constitution +1、Attract、Stam Recov -1';};
	if (text == '火事场力+1、破坏王、抗菌、防御力降低（小）') {out = 'Adrenaline +1、Partbreaker、Anti-bacterial、Defense Down (S)';};
	if (text == '毒无效、麻痹免疫、状态异常攻击+1、睡眠倍化') {out = 'Negate Poison、Negate Paralysis、Status Atk +1、Double Sleep';};
	if (text == '气绝免疫、风压（小）无效、耐力急速回复+1、恶灵加持') {out = 'Negate Stun、Windproof (Lo)、Stam Recov +1、Evil Blessing';};
	if (text == '冰属性攻击强化+1、耐寒、耐震、气绝倍化') {out = 'Ice Itk +1、Cold Res、Tremor Res、Double Stun';};
	if (text == '耐泥雪、探知、冰属性耐性强化+1、火属性耐性弱化') {out = 'Mud/Snow、Detect、Ice Res +1、Fire Res Down';};
	if (text == '砥石使用高速化、冰属性攻击强化+1、心眼、毒倍化') {out = "Speed Sharpening、Ice Itk +1、Mind's Eye、Double Poison";};
	if (text == '睡眠免疫、吸引、状态异常攻击+1、火属性耐性弱化') {out = 'Negate Sleep、Attract、Status Atk +1、Fire Res Down';};
	if (text == '不屈、根性、回复速度+1、耐力回复迟缓-1') {out = 'Fortify、Guts、Rec Speed +1、Stam Recov -1';};
	if (text == '见切+2、暴击、气绝倍化') {out = 'Critical Eye +2、Violent Strike、Double Stun';};
	if (text == '防御强化、速食、耐泥雪、攻击力降低（小）') {out = 'Guard Boost、Speed Eating、Mud/Snow、Attack Down (S)';};
	if (text == '散弹/矢强化、速食、耐泥雪、攻击力降低（小）') {out = 'Pellet/Spread Up、Speed Eating、Mud/Snow、Attack Down (S)';};
	if (text == '防御等级+1、攻击力提升（小）、状态异常攻击-1') {out = 'Guard +1、Attack Up (S)、Status Atk Down';};
	if (text == '上弹速度强化+1、攻击力提升（小）、状态异常攻击-1') {out = 'Reload Spd +1、Attack Up (S)、Status Atk Down';};
	if (text == '业物、见切+1、防御力降低（小）') {out = 'Sharp、Critical Eye +1、Defense Down (S)';};
	if (text == '贯通弹/矢强化、见切+1、防御力降低（小）') {out = 'Pierce/Pierce Up、Critical Eye +1、Defense Down (S)';};
	if (text == '广域化+1、耐力急速回复+1、回复速度-1') {out = 'Wide-Range +1、Stam Recov +1、Rec Speed -1';};
	if (text == '挑战者、火事场力+1、恶灵加持') {out = 'Challenger、Adrenaline +1、Evil Blessing';};
	if (text == '集中、破坏王、体力弱化-2') {out = 'Concentrate、Partbreaker、Health -2';};
	if (text == '毒减半、体力强化+2、探知') {out = 'Halve Poison、Health +2、Detect';};
	if (text == '耳栓、状态异常攻击+1、砥石使用高速化、回复速度-1') {out = 'Earplugs、Status Atk +1、Speed Sharpening、Rec Speed -1';};
	if (text == '耳栓、状态异常攻击+1、反动减轻+1、回复速度-1') {out = 'Earplugs、Status Atk +1、Recoil Down +1、Rec Speed -1';};
	if (text == '体术+1、弱点特效、挑衅') {out = 'Constitution +1、Weakness Exploit、Taunt';};
	if (text == '心眼、火属性攻击强化+2、防御力降低（小）') {out = "Mind's Eye、Fire Atk +2、Defense Down (S)";};
	if (text == '刺杀术+1、火属性攻击强化+2、防御力降低（小）') {out = 'Assassin Tech +1、Fire Atk +2、Defense Down (S)';};
	if (text == '火事场力+1、绊术、速食、回复速度-1') {out = 'Adrenaline +1、Tripping Power、Speed Eating、Rec Speed -1';};
	if (text == '耐震、根性、水属性攻击强化+1、慢食') {out = 'Tremor Res、Guts、Water Atk +1、Slow Eater';};
	if (text == '攻击力提升（大）、火属性攻击强化+1、体力弱化-1') {out = 'Attack Up (L)、Fire Atk +1、Health -1';};
	if (text == '心眼、回复速度+1、火属性攻击强化+1、钝刀') {out = "Mind's Eye、Rec Speed +1、Fire Atk +1、Blunt Edge";};
	if (text == '弱点特效、回复速度+1、火属性攻击强化+1、上弹速度强化-1') {out = 'Weakness Exploit、Rec Speed +1、Fire Atk +1、Reload Spd -1';};
	if (text == '耳栓、速食、防御力提升（小）、砥石使用低速化') {out = 'Earplugs、Speed Eating、Defense Up (S)、Slow Sharpening';};
	if (text == '耳栓、速食、防御力提升（小）、反动增大') {out = 'Earplugs、Speed Eating、Defense Up (S)、Recoil Up';};
	if (text == '回复速度+2、业物、挑战者+2、刺伤无效、降低耐力回复速度-1') {out = 'Rec Speed +2、Sharp、Challenger+2、Negate Thorns、Stam Recov -1';};
	if (text == '回复速度+2、业物、挑战者+2、刺伤无效、降低耐力回复速度-6') {out = 'Rec Speed +2、Sharp、Challenger+2、Negate Thorns、Stam Recov -1';};
	if (text == '不屈，特殊攻击+2，广域化+1') {out = 'Fortify，Status Atk +2，Wide-Range +1';};
	if (text == '拔刀术，耐震，耐力回复+1，砥石使用低速化') {out = 'Critical Draw，Tremor Res，Stam Recov +1，Slow Sharpening';};
	if (text == '上弹速度强化+1，贯通弹/矢强化，耐力回复+1，状态异常攻击-1') {out = 'Reload Spd +1，Pierce/Pierce Up，Stam Recov +1，Status Atk Down';};
	if (text == '雷属性攻击强化+1，回避性能，精灵的守护，砥石使用低速化') {out = 'Thunder Atk +1，Evasion，Holy Blessing，Slow Sharpening';};
	if (text == '雷属性攻击强化+1，回避性能，精灵的守护，上弹速度强化-1') {out = 'Thunder Atk +1，Evasion，Holy Blessing，Reload Spd -1';};
	if (text == '见切+2，耳栓，业物，体力弱化-1') {out = 'Critical Eye +2，Earplugs，Sharp，Health -1';};
	if (text == '见切+2，耳栓，通常弹&连射矢强化，体力弱化-1') {out = 'Critical Eye +2，Earplugs，Normal/Rapid Up，Health -1';};
	if (text == '耳栓，甲壳杀手，回复速度+1，体力弱化-1') {out = 'Earplugs，Crustaceans Killer，Rec Speed +1，Health -1';};
	if (text == '回避性能+2，集中，毒倍化') {out = 'Evasion+2，Concentrate，Double Poison';};
	if (text == 'KO术，集中，看破+1，耐力回复-1') {out = 'Knockout King，Concentrate，See Through +1，Stam Recov -1';};
	if (text == '体术+2，睡眠免疫，鸟龙杀手，防御力降低（小）') {out = 'Constitution +2，Negate Sleep，Bird Dragons Killer，Defense Down (S)';};
	if (text == '火事场力+2，风压（大）无效，火属性攻击强化+1') {out = 'Adrenaline +2，Windproof (Hi)，Fire Atk +1';};
	if (text == '破坏王，耐震，弱点特效，耐力回复-1') {out = 'Partbreaker，Tremor Res，Weakness Exploit，Stam Recov -1';};

	if (text == '山青虫') {out = 'Mountain Budworm';};
	if (text == '蓝速龙的鳞') {out = 'Velociprey Scale';};
	if (text == '圆蚂蚱') {out = 'Round Grasshopper';};
	if (text == '龙骨【小】') {out = 'Monster Bone S';};
	if (text == '棒状之骨') {out = 'Bone';};
	if (text == '兽骨【小】') {out = 'Brute Bone S';};
	if (text == '原盘石') {out = 'Disk Stone';};
	if (text == '圆盘石') {out = 'Disk Stone';};
	if (text == '小石子') {out = 'Stone';};
	if (text == '铁矿石') {out = 'Iron Ore';};
	if (text == '温暖的毛皮') {out = 'Warm Pelt';};
	if (text == '河狸兽的爪') {out = 'Caeserber Claw';};
	if (text == '蓝速龙王的皮') {out = 'Velocidrome Hide';};
	if (text == '蓝速龙王的爪') {out = 'Velocidrome Claw';};
	if (text == '大野猪王的鬃') {out = 'Bulldrome Mane';};
	if (text == '大野猪王的牙') {out = 'Bulldrome Tusk';};
	if (text == '鬼狩蛛的毛') {out = 'Baelidae Hair';};
	if (text == '鬼狩蛛的盾爪壳') {out = 'Baelidae Shield Claw';};
	if (text == '毒怪鸟的头') {out = 'Gypceros Head';};
	if (text == '变异的光水晶') {out = 'Weird Lightcrystal';};
	if (text == '低压的电气袋') {out = 'Electro Sac';};
	if (text == '白化里脊肉') {out = 'Pale Steak';};
	if (text == '绿色的粘液') {out = 'Green Mucus';};
	if (text == '沙雷鸟的嗉囊') {out = 'Chramine Crop';};
	if (text == '青怪鸟的背甲') {out = 'Blue Kut-Ku Shell';};
	if (text == '青怪鸟的耳') {out = 'Blue Kut-Ku Ear';};
	if (text == '燕雀石') {out = 'Machalite Ore';};
	if (text == '岩龙的甲壳') {out = 'Basarios Shell';};
	if (text == '岩龙的尾巴') {out = 'Basarios Tail';};
	if (text == '眠鸟的羽毛') {out = 'Hypnocatrice Feather';};
	if (text == '眠鸟的喙') {out = 'Hypnocatrice Beak';};
	if (text == '大地结晶') {out = 'Earth Crystal';};
	if (text == '金毛兽王的大骨') {out = 'G.Congalala Bone';};
	if (text == '金毛兽王的爪') {out = 'G.Congalala Claw';};
	if (text == '黏着白蚁') {out = 'Glueglopper';};
	if (text == '骇狩蛛的毛') {out = 'D.Baelidae Hair';};
	if (text == '骇狩蛛的盾爪壳') {out = 'D.Baelidae Shield Claw';};
	if (text == '雪狮子的毛') {out = 'Blango Pelt';};
	if (text == '雪狮子的尾巴') {out = 'Blangonga Tail';};
	if (text == '星龙的甲壳') {out = 'Estrellian Shell';};
	if (text == '星龙的爪') {out = 'Estrellian Claw';};
	if (text == '杀人蜂幼虫') {out = 'Snakebee Larvae';};
	if (text == '古龙之血') {out = 'Ancient Blood';};
	if (text == '吞渊龙的腕甲') {out = 'Tartaronis Wristguards';};
	if (text == '红角蝶') {out = 'Red-Horned Butterfly';};
	if (text == '银喵玉') {out = 'Silver Meow Sphere';};
	if (text == '剑豪镰蟹的坚钳') {out = 'S.Shogun Ceanataur Clamp+';};
	if (text == '剑豪之锋镰') {out = 'S.Shogun Ceanataur Scythe+';};
	if (text == '土蜂幼虫') {out = 'Earth Bee Larvae';};
	if (text == '金喵玉') {out = 'Golden Meow Sphere';};
	if (text == '亮蓝色的粘液') {out = 'Bright Blue Mucus';};
	if (text == '冰雷鸟的苍白鼻') {out = 'I.Chramine Pale Beak';};
	if (text == '兽骨【大】') {out = 'Brute Bone L';};
	if (text == '强光的电气袋') {out = 'Thunder Sac+';};
	if (text == '红色霜降肉') {out = 'Red Frosted Meat';};
	if (text == '龙骨【大】') {out = 'Monster Bone L';};
	if (text == '断刃一角龙的坚甲') {out = 'S.Monoblos Carapace+';};
	if (text == '断刃一角龙的靭尾') {out = 'S.Monoblos Tough Tail+';};
	if (text == '独耳黑狼鸟的韧翼膜') {out = 'One-Eared Garuga Edge Webbing';};
	if (text == '独耳黑狼鸟的刚翼') {out = 'One-Eared Garuga Wing+';};
	if (text == '光水晶') {out = 'Lightcrystal';};
	if (text == '尾晶蝎的紫晶') {out = 'A.Vashimu Amethyst+';};
	if (text == '尾晶蝎的巨钳') {out = 'A.Vashimu Giant Clamp';};
	if (text == '银眠鸟的银羽毛') {out = 'S.Hypnocatrice Feather+';};
	if (text == '银眠鸟的牙喙') {out = 'S.Hypnocatrice Beak+';};
	if (text == '荒厄龙的剑鳞') {out = 'Merphistrophelin Sword Scale';};
	if (text == '荒厄龙的骨翼') {out = 'Merphistrophelin Bone Wing';};
	if (text == '�厄的宝珠') {out = 'Disaster Orb';};
	if (text == '钢龙的宝玉') {out = 'Daora Gem';};
	if (text == '龙骨【中】') {out = 'Monster Bone M';};
	if (text == '兽骨【中】') {out = 'Brute Bone M';};
	if (text == '大野猪的皮') {out = 'Bullfango Hide';};
	if (text == '冰结晶') {out = 'Ice Crystal';};
	if (text == '迷之骨') {out = 'Mystery Bone';};
	if (text == '河狸兽的牙') {out = 'Caeserber Fang';};
	if (text == '河狸兽的皮') {out = 'Caeserber Hide';};
	if (text == '磨损的门牙') {out = 'Worn Incisor';};
	if (text == '蓝速龙王的牙') {out = 'Velocidrome Fang';};
	if (text == '蓝速龙王的头冠') {out = 'Velocidrome Head';};
	if (text == '大野猪王的蹄') {out = 'Bulldrome Hoof';};
	if (text == '大野猪王的卷曲牙') {out = 'Bulldrome Curved Fang';};
	if (text == '怪鸟的背甲') {out = 'Kut-Ku Shell';};
	if (text == '怪鸟的翼') {out = 'Kut-Ku Wing';};
	if (text == '怪鸟的耳') {out = 'Kut-Ku Ear';};
	if (text == '怪鸟的爪') {out = 'Kut-Ku Claw';};
	if (text == '怪鸟的鳞') {out = 'Kut-Ku Scale';};
	if (text == '破损的喙') {out = 'Broken Beak';};
	if (text == '黄速龙王的爪') {out = 'Gendrome Claw';};
	if (text == '黄速龙的鳞') {out = 'Genprey Scale';};
	if (text == '黄速龙王的麻痹牙') {out = 'Gendrome Fang';};
	if (text == '黄速龙王的皮') {out = 'Gendrome Hide';};
	if (text == '黄速龙王的头冠') {out = 'Gendrome Head';};
	if (text == '黄速龙王的尾巴') {out = 'Gendrome Tail';};
	if (text == '鬼狩蛛的爪') {out = 'Baelidae Claw';};
	if (text == '鬼狩蛛的甲壳') {out = 'Baelidae Shell';};
	if (text == '鬼狩蛛的体液') {out = 'Baelidae Fluid';};
	if (text == '鬼狩蛛的复眼') {out = 'Baelidae Eye';};
	if (text == '鬼狩蛛的蛛丝') {out = 'Baelidae Silk';};
	if (text == '沙狸兽的爪') {out = 'Y.Caeserber Claw';};
	if (text == '沙狸兽之皮') {out = 'Y.Caeserber Hide';};
	if (text == '储沙囊') {out = 'Sand Bladder';};
	if (text == '沙狸兽的牙') {out = 'Y.Caeserber Fang';};
	if (text == '沙狸兽的尾甲') {out = 'Y.Caeserber Tail';};
	if (text == '沙狸兽的门牙') {out = 'Y.Caeserber Worn Incisor';};
	if (text == '毒怪鸟的皮') {out = 'Gypceros Hide';};
	if (text == '毒怪鸟的嘴') {out = 'Gypceros Beak';};
	if (text == '橡胶质的尾巴') {out = 'Gypceros Tail';};
	if (text == '毒怪鸟的翼') {out = 'Gypceros Wing';};
	if (text == '桃毛兽王的牙') {out = 'Congalala Fang';};
	if (text == '桃毛兽王的大骨') {out = 'Congalala Bone';};
	if (text == '桃毛兽王的爪') {out = 'Congalala Claw';};
	if (text == '桃毛兽王的皮') {out = 'Congalala Pelt';};
	if (text == '淡彩色的毛') {out = 'Bright Pelt';};
	if (text == '桃毛兽的毛') {out = 'Conga Pelt';};
	if (text == '火红的鬃毛') {out = 'Red Mane';};
	if (text == '沙雷鸟的皮') {out = 'Chramine Hide';};
	if (text == '沙雷鸟的翼') {out = 'Chramine Wing';};
	if (text == '沙雷鸟的红鼻') {out = 'Chramine Red Beak';};
	if (text == '沙龙王的皮') {out = 'Cephadrome Hide';};
	if (text == '沙龙的鳞') {out = 'Cephalos Scale';};
	if (text == '沙龙王的牙') {out = 'Cephadrome Fang';};
	if (text == '沙龙王的储砂袋') {out = 'Cephadrome Sand Sac';};
	if (text == '弯月之头冠') {out = 'Cephadrome Head';};
	if (text == '桃色的鳞') {out = 'Pink Scale';};
	if (text == '盾蟹的爪') {out = 'Daimyo Hermitaur Claw';};
	if (text == '盾蟹的甲壳') {out = 'Daimyo Hermitaur Shell';};
	if (text == '盾蟹的脚') {out = 'Daimyo Hermitaur Leg';};
	if (text == '黑珍珠') {out = 'Black Pearl';};
	if (text == '盾蟹的小壳') {out = 'Small Hermitaur Shell';};
	if (text == '盾蟹的钳') {out = 'Daimyo Hermitaur Clamp';};
	if (text == '青怪鸟的爪') {out = 'Blue Kut-Ku Claw';};
	if (text == '青怪鸟的鳞') {out = 'Blue Kut-Ku Scale';};
	if (text == '青怪鸟的翼') {out = 'Blue Kut-Ku Wing';};
	if (text == '巨大的青鸟喙') {out = 'Blue Kut-Ku Beak';};
	if (text == '电龙的牙') {out = 'Khezu Fang';};
	if (text == '电龙的翼') {out = 'Khezu Wing';};
	if (text == '柔软的皮') {out = 'Pearly Hide';};
	if (text == '电龙的吸盘') {out = 'Khezu Sucker';};
	if (text == '岩龙的头壳') {out = 'Basarios Skull';};
	if (text == '岩龙的背壳') {out = 'Basarios Carapace';};
	if (text == '岩龙的泪') {out = 'Basarios Tear';};
	if (text == '岩龙的翼') {out = 'Basarios Wing';};
	if (text == '岩龙的腹甲') {out = 'Basarios Breastplate';};
	if (text == '眠鸟的爪') {out = 'Hypnocatrice Claw';};
	if (text == '稀释的眠液') {out = 'Diluted Sleep Solution';};
	if (text == '破损的眠袋') {out = 'Broken Sleep Sac';};
	if (text == '七色的尾羽') {out = 'Rainbow Feather';};
	if (text == '眠鸟的胃石') {out = 'Hypnocatrice Gastrolith';};
	if (text == '金毛兽王的毛') {out = 'G.Congalala Hair+';};
	if (text == '金毛兽王的皮') {out = 'G.Congalala Pelt';};
	if (text == '金毛兽王的牙') {out = 'G.Congalala Fang';};
	if (text == '淡金色的毛') {out = 'Pale Gold Hair';};
	if (text == '骇狩蛛的甲壳') {out = 'D.Baelidae Shell';};
	if (text == '骇狩蛛的眼') {out = 'D.Baelidae Eye';};
	if (text == '骇狩蛛的体液') {out = 'D.Baelidae Fluid';};
	if (text == '骇狩蛛的爪') {out = 'D.Baelidae Claw';};
	if (text == '骇狩蛛的蛛丝') {out = 'D.Baelidae Silk';};
	if (text == '毒鸟的紫翼') {out = 'P.Gypceros Wing';};
	if (text == '橡胶质的紫皮') {out = 'P.Rubbery Hide';};
	if (text == '紫毒鸟的嘴') {out = 'P.Gypceros Beak';};
	if (text == '毒鸟的紫头') {out = 'P.Gypceros Head';};
	if (text == '诡异的光水晶') {out = 'Strange Lightcrystal';};
	if (text == '橡胶质的绿尾') {out = 'P.Gypceros Tail';};
	if (text == '镰蟹的爪') {out = 'Shogun Ceanataur Claw';};
	if (text == '镰蟹的甲壳') {out = 'Shogun Ceanataur Carapace';};
	if (text == '镰蟹的脚') {out = 'Shogun Ceanataur Leg';};
	if (text == '镰蟹的小壳') {out = 'Ceanataur Shell';};
	if (text == '龙头壳') {out = 'Wyvern Scalp';};
	if (text == '金真珠') {out = 'Gold Pearl';};
	if (text == '雪狮子的爪') {out = 'Blangonga Claw';};
	if (text == '雪狮子的皮') {out = 'Blangonga Hide';};
	if (text == '雪狮子的大骨') {out = 'Blangonga Large Bone';};
	if (text == '雪狮子的髭') {out = 'Blangonga Mustache';};
	if (text == '雪狮子的牙') {out = 'Blangonga Fang';};
	if (text == '星龙的角') {out = 'Estrellian Horn';};
	if (text == '星羽蝶的羽翅') {out = 'Estrellian Wing Feather';};
	if (text == '微光的体液') {out = 'Shimmering Body Fluid';};
	if (text == '星龙的腹甲') {out = 'Estrellian Breastplate';};
	if (text == '星之龙鳞') {out = 'Estrellian Scale';};
	if (text == '河狸兽的尖爪') {out = 'Caeserber Claw+';};
	if (text == '河狸兽的优质皮') {out = 'Caeserber Hide+';};
	if (text == '河狸兽的尖牙') {out = 'Caeserber Fang+';};
	if (text == '历战的门牙') {out = 'Veteran Incisor';};
	if (text == '辉龙石') {out = 'Dragonite Ore';};
	if (text == '优质的毛皮') {out = 'High-Quality Pelt';};
	if (text == '蓝速龙王的尖爪') {out = 'Velocidrome Claw+';};
	if (text == '蓝速龙的优质鳞') {out = 'Velociprey Scale+';};
	if (text == '蓝速龙王的尖牙') {out = 'Velocidrome Fang+';};
	if (text == '蓝速龙王的大头冠') {out = 'Velocidrome Head+';};
	if (text == '蓝速龙王的优质皮') {out = 'Velocidrome Hide+';};
	if (text == '大野猪的硬皮') {out = 'Bullfango Hide+';};
	if (text == '大野猪王的硬蹄') {out = 'Bulldrome Hoof+';};
	if (text == '大野猪王的曲刚牙') {out = 'Bulldrome Curved Fang+';};
	if (text == '大野猪王的尖牙') {out = 'Bulldrome Tusk+';};
	if (text == '大野猪王的硬鬃') {out = 'Bulldrome Mane+';};
	if (text == '怪鸟的刚翼') {out = 'Kut-Ku Wing+';};
	if (text == '怪鸟的坚背甲') {out = 'Kut-Ku Carapace';};
	if (text == '怪鸟的地狱耳') {out = 'Kut-Ku Ear+';};
	if (text == '怪鸟的尖爪') {out = 'Kut-Ku Claw+';};
	if (text == '怪鸟的优质鳞') {out = 'Kut-Ku Scale+';};
	if (text == '漂亮的喙') {out = 'Beautiful Beak';};
	if (text == '黄速龙王的尖爪') {out = 'Gendrome Claw+';};
	if (text == '黄速龙的优质鳞') {out = 'Genprey Scale+';};
	if (text == '黄速龙王的麻痹尖牙') {out = 'Gendrome Fang+';};
	if (text == '黄速龙王的优质皮') {out = 'Gendrome Hide+';};
	if (text == '黄速龙王的大头冠') {out = 'Gendrome Head+';};
	if (text == '黄速龙王的韧尾') {out = 'Gendrome Tail+';};
	if (text == '鬼狩蛛的尖爪') {out = 'Baelidae Claw+';};
	if (text == '鬼狩蛛的坚壳') {out = 'Baelidae Shell+';};
	if (text == '鬼狩蛛的浓液') {out = 'Baelidae Broth';};
	if (text == '鬼狩蛛的鬼眼') {out = 'Baelidae Eye+';};
	if (text == '鬼狩蛛的刚毛') {out = 'Baelidae Hair+';};
	if (text == '鬼狩蛛的韧蛛丝') {out = 'Baelidae Silk+';};
	if (text == '沙狸兽的坚爪') {out = 'Y.Caeserber Claw+';};
	if (text == '沙狸兽重皮') {out = 'Y.Caeserber Hide+';};
	if (text == '沙狸兽的尖牙') {out = 'Y.Caeserber Fang+';};
	if (text == '厚实的储沙囊') {out = 'Heavy Sand Bladder';};
	if (text == '沙狸兽的坚尾甲') {out = 'Y.Caeserber Tail+';};
	if (text == '沙狸兽的尖门牙') {out = 'Y.Caeserber Veteran Incisor';};
	if (text == '毒怪鸟的刚翼') {out = 'Gypceros Wing+';};
	if (text == '毒怪鸟的优质皮') {out = 'Gypceros Hide+';};
	if (text == '毒怪鸟的坚硬嘴') {out = 'Gypceros Beak+';};
	if (text == '橡胶质的韧尾') {out = 'Gypceros Tail+';};
	if (text == '变异的新星水晶') {out = 'Weird Novacrystal';};
	if (text == '毒怪鸟的坚硬头') {out = 'Gypceros Head+';};
	if (text == '桃毛兽王的尖牙') {out = 'Congalala Fang+';};
	if (text == '桃毛兽王的坚骨') {out = 'Congalala Bone+';};
	if (text == '桃毛兽王的尖爪') {out = 'Congalala Claw+';};
	if (text == '桃毛兽王的优质皮') {out = 'Congalala Pelt+';};
	if (text == '极彩色的毛') {out = 'Vibrant Pelt';};
	if (text == '桃毛兽的刚毛') {out = 'Conga Pelt+';};
	if (text == '赤红的刚鬃') {out = 'Red Mane+';};
	if (text == '沙雷鸟的优质皮') {out = 'Chramine Hide+';};
	if (text == '沙雷鸟的刚翼') {out = 'Chramine Wing+';};
	if (text == '亮绿色的粘液') {out = 'Bright Green Mucus';};
	if (text == '沙雷鸟的厚实嗉囊') {out = 'Chramine Crop+';};
	if (text == '沙雷鸟的赤红鼻') {out = 'Chramine Crimson Beak';};
	if (text == '沙龙的优质鳞') {out = 'Cephalos Scale+';};
	if (text == '沙龙王的尖牙') {out = 'Cephadrome Fang+';};
	if (text == '桃色的优质鳞') {out = 'Pink Scale+';};
	if (text == '沙龙王的优质皮') {out = 'Cephadrome Hide+';};
	if (text == '沙龙王的大储砂袋') {out = 'Cephadrome Sand Sac+';};
	if (text == '新月之头冠') {out = 'Cephadrome Head+';};
	if (text == '盾蟹的尖爪') {out = 'Daimyo Hermitaur Claw+';};
	if (text == '盾蟹的坚壳') {out = 'Daimyo Hermitaur Shell+';};
	if (text == '盾蟹的长脚') {out = 'Daimyo Hermitaur Leg+';};
	if (text == '漆黑大珍珠') {out = 'Black Pearl+';};
	if (text == '盾蟹的小坚壳') {out = 'Small Hermitaur Shell+';};
	if (text == '盾蟹的巨钳') {out = 'Daimyo Hermitaur Clamp+';};
	if (text == '红速龙的优质鳞') {out = 'Iodrome Scale+';};
	if (text == '红速龙王的尖牙') {out = 'Iodrome Fang+';};
	if (text == '红速龙王的猛毒腺') {out = 'Iodrome Fierce Venom';};
	if (text == '红速龙王的尖爪') {out = 'Iodrome Claw+';};
	if (text == '红速龙王的优质皮') {out = 'Iodrome Hide+';};
	if (text == '红速龙王的大头冠') {out = 'Iodrome Crown+';};
	if (text == '青怪鸟的优质翼') {out = 'Blue Kut-Ku Wing+';};
	if (text == '青怪鸟的坚背甲') {out = 'Blue Kut-Ku Shell+';};
	if (text == '青怪鸟的地狱耳') {out = 'Blue Kut-Ku Ear+';};
	if (text == '青怪鸟的尖爪') {out = 'Blue Kut-Ku Claw+';};
	if (text == '青怪鸟的优质鳞') {out = 'Blue Kut-Ku Scale+';};
	if (text == '华丽的青鸟喙') {out = 'Blue Kut-Ku Beak+';};
	if (text == '电龙的优质翼') {out = 'Khezu Patagium+';};
	if (text == '珍珠色的柔皮') {out = 'Pearly Hide+';};
	if (text == '电龙的尖牙') {out = 'Khezu Fang+';};
	if (text == '高压的电气袋') {out = 'High-voltage Electro Sac';};
	if (text == '白化霜降肉') {out = 'Pearly Frosted Meat';};
	if (text == '电龙的强力吸盘') {out = 'Khezu Sucker+';};
	if (text == '岩龙的优质翼') {out = 'Basarios Wing+';};
	if (text == '岩龙的坚头壳') {out = 'Basarios Skull+';};
	if (text == '岩龙的坚背壳') {out = 'Basarios Shell+';};
	if (text == '岩龙的晶泪') {out = 'Basarios Tear+';};
	if (text == '岩龙的坚壳') {out = 'Basarios Armor+';};
	if (text == '岩龙的坚腹甲') {out = 'Basarios Breastplate+';};
	if (text == '完整的眠袋') {out = 'Sleep Sac';};
	if (text == '眠鸟的橙羽毛') {out = 'Hypnocatrice Orange Feather';};
	if (text == '多彩的尾羽') {out = 'Colorful Feather';};
	if (text == '眠鸟的尖爪') {out = 'Hypnocatrice Sharp Claw';};
	if (text == '浓缩的眠液') {out = 'Concentrated Sleep Solution';};
	if (text == '眠鸟的稀胃石') {out = 'Rare Bezoar';};
	if (text == '金毛兽王的刚毛') {out = 'G.Congalala Hair+';};
	if (text == '金毛兽王的优质皮') {out = 'G.Congalala Pelt+';};
	if (text == '金毛兽王的尖牙') {out = 'G.Congalala Fang+';};
	if (text == '金色的毛') {out = 'Golden Hair';};
	if (text == '金毛兽王的坚骨') {out = 'G.Congalala Bone+';};
	if (text == '金毛兽王的尖爪') {out = 'G.Congalala Claw+';};
	if (text == '骇狩蛛的坚壳') {out = 'D.Baelidae Shell+';};
	if (text == '骇狩蛛的复眼') {out = 'D.Baelidae Eye+';};
	if (text == '骇狩蛛的浓液') {out = 'D.Baelidae Broth';};
	if (text == '骇狩蛛的尖爪') {out = 'D.Baelidae Claw+';};
	if (text == '骇狩蛛的刚毛') {out = 'D.Baelidae Hair+';};
	if (text == '骇狩蛛的韧蛛丝') {out = 'D.Baelidae Silk+';};
	if (text == '毒鸟的紫刚翼') {out = 'P.Gypceros Wing+';};
	if (text == '橡胶质的紫柔皮') {out = 'P.Rubbery Hide+';};
	if (text == '紫毒鸟的坚硬嘴') {out = 'P.Gypceros Beak+';};
	if (text == '橡胶质的绿韧尾') {out = 'P.Gypceros Tail+';};
	if (text == '诡异的新星水晶') {out = 'Strange Novacrystal+';};
	if (text == '毒鸟的紫坚硬头') {out = 'P.Gypceros Head+';};
	if (text == '镰蟹的尖爪') {out = 'Shogun Ceanataur Claw+';};
	if (text == '镰蟹的坚壳') {out = 'Ceanataur Shell+';};
	if (text == '镰蟹的长脚') {out = 'Shogun Ceanataur Leg+';};
	if (text == '镰蟹的小坚壳') {out = 'Ceanataur Shell+';};
	if (text == '坚龙头壳') {out = 'Wyvern Scalp+';};
	if (text == '极上金真珠') {out = 'Large Gold Pearl+';};
	if (text == '雪狮子的尖爪') {out = 'Blangonga Claw+';};
	if (text == '雪狮子的优质皮') {out = 'Blangonga Hide+';};
	if (text == '雪狮子的坚骨') {out = 'Blangonga Strong Bone';};
	if (text == '雪狮子的刚髭') {out = 'Blangonga Mustache+';};
	if (text == '雪狮子的刚毛') {out = 'Blango Pelt+';};
	if (text == '雪狮子的尖牙') {out = 'Blangonga Fang+';};
	if (text == '星龙的尖角') {out = 'Estrellian Horn+';};
	if (text == '星龙的坚壳') {out = 'Estrellian Shell+';};
	if (text == '星羽蝶的薄羽翅') {out = 'Estrellian Wing Feather+';};
	if (text == '星光的体液') {out = 'Starlight Body Fluid';};
	if (text == '星龙的坚腹甲') {out = 'Estrellian Breastplate+';};
	if (text == '降星之龙鳞') {out = 'Estrellian Scale+';};
	if (text == '白速龙王的尖爪') {out = 'Giadrome Claw+';};
	if (text == '白速龙的优质鳞') {out = 'Giaprey Scale+';};
	if (text == '白速龙王的尖牙') {out = 'Giadrome Fang+';};
	if (text == '白速龙王的冻结腺') {out = 'Giadrome Frozen Gland';};
	if (text == '白速龙王的大头冠') {out = 'Giadrome Large Crown+';};
	if (text == '白速龙王的优质皮') {out = 'Giadrome Hide+';};
	if (text == '冰雷鸟的优质皮') {out = 'I.Chramine Hide+';};
	if (text == '冰雷鸟的刚翼') {out = 'I.Chramine Wing+';};
	if (text == '冰雷鸟的厚实嗉囊') {out = 'I.Chramine Crop+';};
	if (text == '湛蓝的刚鬃') {out = 'Blue Mane+';};
	if (text == '银眠鸟的尖爪') {out = 'S.Hypnocatrice Claw+';};
	if (text == '晶莹的眠液') {out = 'Crystal Clear Sleep Solution';};
	if (text == '圆鼓鼓的眠袋') {out = 'Bulging Sleep Sac';};
	if (text == '秘银尾羽') {out = 'Silver Tail+';};
	if (text == '银眠鸟的稀胃石') {out = 'Rare Silver Bezoar';};
	if (text == '剑豪镰蟹的尖爪') {out = 'S.Shogun Ceanataur Claw+';};
	if (text == '剑豪镰蟹的坚壳') {out = 'S.Shogun Ceanataur Hard Shell';};
	if (text == '剑豪镰蟹的坚脚') {out = 'S.Shogun Ceanataur Leg+';};
	if (text == '剑豪镰蟹的金色大真珠') {out = 'S.Shogun Ceanataur Gold Pearl+';};
	if (text == '尾晶蝎的尖爪') {out = 'A.Vashimu Claw+';};
	if (text == '尾晶蝎的刚毛') {out = 'A.Vashimu Hair+';};
	if (text == '尾晶蝎的坚壳') {out = 'A.Vashimu Shell+';};
	if (text == '尾晶蝎的大颚') {out = 'A.Vashimu Giant Jaw+';};
	if (text == '尾晶蝎的毒刚毛') {out = 'A.Vashimu Poison Hair+';};
	if (text == '黑狼鸟的优质鳞') {out = 'Garuga Scale+';};
	if (text == '黑狼鸟的坚壳') {out = 'Garuga Shell+';};
	if (text == '黑狼鸟的刚髭') {out = 'Garuga Mustache+';};
	if (text == '黑狼鸟的刚翼爪') {out = 'Garuga Claw+';};
	if (text == '黑狼鸟的韧翼膜') {out = 'Garuga Webbing+';};
	if (text == '黑狼鸟的地狱耳') {out = 'Garuga Hell Ear+';};
	if (text == '红电龙的刚翼') {out = 'R.Khezu Wing+';};
	if (text == '魅惑色的柔皮') {out = 'Alluring Hide+';};
	if (text == '红电龙的尖牙') {out = 'R.Khezu Fang+';};
	if (text == '红电龙的强力吸盘') {out = 'R.Khezu Sucker+';};
	if (text == '独耳黑狼鸟的刚翼爪') {out = 'One-Eared Garuga Claw+';};
	if (text == '独耳黑狼鸟的优质鳞') {out = 'One-Eared Garuga Scale+';};
	if (text == '独耳黑狼鸟的坚壳') {out = 'One-Eared Garuga Shell+';};
	if (text == '独耳黑狼鸟的刚髭') {out = 'One-Eared Garuga Mustache+';};
	if (text == '独耳黑狼鸟的地狱耳') {out = 'One-Eared Garuga Hell Ear+';};
	if (text == '断刃一角龙的坚壳') {out = 'S.Monoblos Hard Shell+';};
	if (text == '断刃一角龙的延髓') {out = 'S.Monoblos Medulla';};
	if (text == '断刃一角龙的脉动心脏') {out = 'S.Monoblos Pulsating Heart';};
	if (text == '断刃一角龙的刚翼') {out = 'S.Monoblos Wing+';};
	if (text == '剑极狼的刚毛') {out = 'Slicemargl Fur+';};
	if (text == '剑极狼的上腕甲') {out = 'Slicemargl Wristguard+';};
	if (text == '剑极狼的锐牙') {out = 'Slicemargl Fang+';};
	if (text == '剑极狼的凶戾眼') {out = 'Slicemargl Brutal Eye+';};
	if (text == '剑极狼的尖爪') {out = 'Slicemargl Claw+';};
	if (text == '剑极狼的獠齿') {out = 'Slicemargl Hunting Tooth';};
	if (text == '苍火龙的刚翼') {out = 'A.Rathalos Wing+';};
	if (text == '苍蓝的爆炎袋') {out = 'Pale Azure Flame Sac+';};
	if (text == '苍火龙的延髓') {out = 'A.Rathalos Medulla';};
	if (text == '苍火龙的上鳞') {out = 'A.Rathalos Scale+';};
	if (text == '苍火龙的坚壳') {out = 'A.Rathalos Shell+';};
	if (text == '苍火龙的逆鳞') {out = 'A.Rathalos Plate+';};
	if (text == '灰晶蝎的尖爪') {out = 'A.Jebia Claw+';};
	if (text == '灰晶蝎的刚毛') {out = 'A.Jebia Hair+';};
	if (text == '灰晶蝎的坚壳') {out = 'A.Jebia Carapace+';};
	if (text == '灰晶蝎的毒刚毛') {out = 'A.Jebia Poison Hair+';};
	if (text == '灰晶蝎的辉晶石') {out = 'A.Jebia Spar+';};
	if (text == '灰晶蝎的大颚') {out = 'A.Jebia Giant Jaw+';};
	if (text == '砂岩龙的坚头壳') {out = 'S.Basarios Skull+';};
	if (text == '砂岩龙的坚背壳') {out = 'S.Basarios Armor+';};
	if (text == '砂岩龙的沙泪') {out = 'S.Basarios Tear+';};
	if (text == '砂岩龙的坚壳') {out = 'S.Basarios Shell+';};
	if (text == '砂岩龙的优质翼') {out = 'S.Basarios Wing+';};
	if (text == '砂岩龙的坚腹甲') {out = 'S.Basarios Breastplate+';};
	if (text == '樱火龙的上鳞') {out = 'P.Rathian Scale+';};
	if (text == '樱火龙的坚壳') {out = 'P.Rathian Shell+';};
	if (text == '樱火龙的上棘') {out = 'P.Rathian Webbing+';};
	if (text == '樱火龙的逆鳞') {out = 'P.Rathian Spike+';};
	if (text == '樱红的爆炎袋') {out = 'P.Rathian Inferno Sac';};
	if (text == '樱火龙的延髓') {out = 'P.Rathian Marrow+';};
	if (text == '灰晶蝎的靭尾') {out = 'A.Jebia Tough Tail+';};
	if (text == '灰晶蝎的巨钳') {out = 'A.Jebia Clamp+';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};
	if (text == '') {out = '';};

	return out;
}